### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by ozky** [tsujan/FeatherPad#1]
I try to build this but face build problems.
I won't compile against qt 5.4 and gcc 4.9.2 and upgade gcc to 5.3 still it fails to build .
It should be compile with gcc 5.x with -Werror=format-security should fix that but no,i faced this same problem with monav-light with gcc.
https://github.com/M4rtinK/monav-light/issues/1
https://github.com/M4rtinK/monav-light/pull/2
[featherpad.txt](https://github.com/tsujan/FeatherPad/files/232859/featherpad.txt)

**Comment by tsujan** [comment]
Thanks a lot for being the first person trying to use it! I'm developing and using it for 2 years and it has been indispensable to me, especially when coding. But no one can test an app with regard to all of its possible usages alone.

The problem you mentioned is not gcc but your Qt5's version. Some changes in Qt5 weren't backward compatible. The minimum required version is 5.5 but I would NOT recommend you to upgrade you Qt5 installation just for this. Fortunately, I have a Kubuntu 15.10 on VirtualBox. I'll try to make the code compatibale with Qt 5.4 and tell you.

**Comment by ozky** [comment]
No problem i have looked plain text editor qt5,all those juffed and tea and others are full of program coder features and not very usable as normal text editor.
I try to compile it against qt community binaries but there is problem still
libicuuc.so.54, needed by and libicuuc.so.54 these are libicuuc.so.53 libicuuc.so.53 in Mageia 5.
https://download.qt.io/archive/qt/5.5/5.5.1/

**Comment by tsujan** [comment]
Where is you system Qt5's qmake? In Debian-based systems it is `/usr/lib/x86_64-linux-gnu/qt5/bin/qmake` so that this command should work for compilation against Qt-5.4 too:
````
/usr/lib/x86_64-linux-gnu/qt5/bin/qmake && make
````
If not, please replace the qmake path with its path on your system.

If you still cannot compile it, tell me and I could give you a link to an older version of FeatherPad, which should be compiled easily. It has most of the features of the latest version.

**Comment by tsujan** [comment]
Please also use `make distclean` before compilation with another qmake path.

**Comment by ozky** [comment]
Yeah i got it compiled.

**Comment by tsujan** [comment]
> Yeah i got it compiled.

Great! Suggestions and bug reports are welcome.

**Comment by ozky** [comment]
I used checkinstall to generate rpm package,it's so good that qt community have provided pre compiled binarys to install newer qt. Only thing needed to do was symlink kvantum from existing qt 5.4 to 5.5 and add to /etc/profile export and overide theme. Ofcourse suggestion are welcome if have better way to do it.
export QT_STYLE_OVERRIDE
QT_STYLE_OVERRIDE="kvantum"

**Comment by tsujan** [comment]
> I used checkinstall....

In old days, when I had Fedora, I used it too. It was handy. With Debian, I didn't need it anymore. However, in the case of FeatherPad, there are only a few files that are installed with `sudo make install`, so an rpm wouldn't be needed really.

> ... and add to /etc/profile export and overide theme

I think you could add them to `~/.profile` instead but I'm not sure because I haven't had rpm based systems for a long time. `/etc/profile` always works.

Anyway, the Qt5/gcc problem will be resolved in your distro with an update soon.

**Comment by ozky** [comment]
That overide is to auto use kvantum engine if i use different account don't need to manually change it.
Mageia. Anyway profile is same in all distros it's not releated to rpm or deb.

**Comment by ozky** [comment]
I managed to build it against qt5.6 as it's more recommend to use it because it's lts version so support is very long time.

**Comment by tsujan** [comment]
Yes! I have a Manjaro with Qt-5.6 on my older computer and use FeatherPad there. In fact, it's even compatible with Qt-5.4 but the full qmake path should be used for building because systems with Qt-5.4 may still set their default qmake to qmake-qt4.

**Comment by ozky** [comment]
Build fine against mine brand new Mageia 6 dev1 qt5.6,was just going to answer you can close this bug.

**Comment by tsujan** [comment]
@ozky Thank you! I was almost sure about that; now I'm completely sure :)

**Comment by ozky** [comment]
Only thing i needed to make little change to makefile,-Wformat-security off and replace it with -w otherwise it did fail to build it.
Is this because Mageia development version Cauldron aka next stable version 6 use 5.3.x version gcc ?.

**Comment by tsujan** [comment]
I don't know. Here, on Debian Testing, gcc is 5.3.1 and `qmake && make` works without any problem. I've had no trouble on Manjaro/Arch either.
