### ISSUE TITLE
Removal of trailing whitespaces is partial wrong with markdown

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#105]
https://github.com/atom/whitespace/issues/137 and others

two trailing spaces mark a new line in markdown

**Comment by tsujan** [comment]
So, it means, for md, if there's only one trailing space, it should be removed but otherwise, 2 spaces should remain and the rest should be removed. Am I right?

**Comment by agaida** [comment]
Totally right

**Comment by agaida** [comment]
ok, dunno how relevant it is, but https://gist.github.com/shaunlebron/746476e6e7a4d698b373
it don't matter if it is \s\s or \s\s\s - its a new line - and ok, github flavoured markdown is a little bit different :D

**Comment by tsujan** [comment]
Thanks! That saved me a confusion.

**Comment by tsujan** [comment]
Done.

A trailing tab is treated as a space -- no markdown doc that I saw was specific in this regard.

When markdown is saved as another format (who saves md as sh?!), the trailing double spaces will be kept until the doc is saved again. I think there's no need to hairsplitting in such a rare case ;)

BTW, I'll make the next release in 30 March. Please tell me if you find any issue until then!

**Comment by agaida** [comment]
ok, will do so - i only stumbled over this when editing our READMEs - so i guess i had to reformat them :D

**Comment by tsujan** [comment]
If there's a problem, it should be rare because I constantly use FP for coding.
