### ISSUE TITLE
Keyboard [Insert] key to toggle between Insert/Replace modes.

### ISSUE THREAD

**Issue by aramazano** [tsujan/FeatherPad#116]
Currently there is only "insert" mode (no replace mode).

**Comment by aramazano** [comment]
I mean the usual text editing in insertion or replacement mode. In insret mode, what you type is inserted at the cursor position. In replace mode, your typing overwrites the the text. Oh, I see now, I should have used "overwrite" mode instead of "replace" mode, as the term replace can mean a lot of things.

On most all text editors, Insert/Overwrite mode is usually toggled by the [Ins] key.

**Comment by tsujan** [comment]
OK. I got it now. Thanks!

**Comment by tsujan** [comment]
Implemented in https://github.com/tsujan/FeatherPad/commit/e05ac1072b96d9fdeb3575d9232050812292b147.

Yes, its name is exactly "overwrite mode"; I should have guessed what you meant; seeing the word "replace" made me think about the replace doc ;) Strange that I'd forgotten to add those 2 lines of code before!
