### ISSUE TITLE
Feature: Close with the last open file

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#117]
i often edit a set of files like fpad debian/* - and i don't need the editor open any longer as when the last file from this set is closed. So it would be helpful if fpad just disappear if the last file is closed.

**Comment by tsujan** [comment]
You mean closing the window on closing its last tab? That can be added as an option.

**Comment by tsujan** [comment]
BTW, I'll release V0.8.1 two weeks after this and won't add a feature meanwhile.

**Comment by aramazano** [comment]
But I wonder how it would fit in with the situation where featherpad is launched with an empty session. In that case we shall have an editor with no sessions, but opening some files and then closing them, i.e. returning to our starting point (of having no sessions), will close the application. I wonder if this can be considered as conflicting behaviour. I haven't given it an in depth thought, but on the face value it struck me as some kind of conflicting/confusing behavior.

P.S. Taking a cue from how popular browsers behave in a similar situation might be worthwhile.

**Comment by agaida** [comment]
@tsujan - tried fpad as nano replacement in devscripts - don't work well :( - you remember the discussion about saving not changed files. As it turns out nano does exactly that, not sure about vim and :wq

**Comment by tsujan** [comment]
> you remember the discussion about saving not changed files.

I don't. A hint?

**Comment by tsujan** [comment]
Ah, I remembered! But how that can be a problem? Please explain!

**Comment by agaida** [comment]
an example would be debians devscripts - one can define an edior of choice in ~/.devscripts
```
editor={vi;nano;fpad} 
```
if i call dch (debchange) it opens the changelog in a temporary file changelog.dch - depending on the given options with a new entry or changed entry - however, if i leave the editor with the file untouched the changes wouldn't it make back to the original file - so in vi it would be; :q discard the changes by scripting :qw write back the changes in the processing after. So saving a file with no changes only would change the time stamp aka touch the file. In fpad it would be cool if the complete saving procedure of removing trailing whitespaces, save the file etc would occour.

**Comment by tsujan** [comment]
OK. I reopen the report in question.

**Comment by agaida** [comment]
hmm - maybe more clear: 
* dch -r  (open a not released changelog and set the target distro from UNRELEASED to $foo) and the date - normally no other changes will be made. I save the file and be done with. Right now not possible.
* dch -bpo (create a backport changelog entry, normally no manual changes are needed, only have a look and save the result explicitely)

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/e2b185ecfa3887952000e8098297af315d811561

The option is under Preferences → Window (near the end).
