### ISSUE TITLE
Please re-map Ctrl-W

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#118]
Normally Ctrl-W close the focussed tab or the active document:
* Firefox
* Chrome
* Midori
* pcmanfm-qt
* Libre Office

**Comment by tsujan** [comment]
FP has a good shortcut editor and `Ctrl+W` can be customized in it.

I see no relation between the letter "W" and the word "Close", while it's the default shortcut for "Wrapping". Maybe Midori, Firefox, etc had exhausted logical choices ;) Anyhow, the default isn't so important when customization is possible.

**Comment by agaida** [comment]
Oh - and i forget about common used editors and programs like juffed, atom, geany, beyond compare, inkscape, gimp - only to name a few not so common apps - in all apps closes  Ctrl-W  the current document or tab. Sure, i could remap this  or deliver a matching configuration in my package. But in general i would like to have the key-mapping as i would expect the mappings (same as for the old pseudo standard introduced by wordstar Ctrl-C, Ctrl-V, Ctrl-X ...

**Comment by agaida** [comment]
and the relation is directly in front of you - have a look at your keyboard QWERT and YXCVB ...

**Comment by tsujan** [comment]
To me, having a simple/logical shortcut to toggle wrapping was/is more important than following what others do. Enforcing a bad default shortcut for it just because 100 apps do so is not an option; and, perhaps, most of those apps don't have to deal with toggling line wrapping.

**Comment by agaida** [comment]
ok, thats whats downstream patches are for

**Comment by tsujan** [comment]
> ok, thats whats downstream patches are for

Of course, I neither have control over that nor recommend it.

As you surely know, Firefox, Midori, Chrome, pcmanfm-qt,... don't deal with line wrapping; the comparison is wrong. And I don't think I'm responsible for that silent "w" at the beginning of "wrap" in English ;)

**Comment by agaida** [comment]
i understand your reasons - but i don't agree - maybe some editors like atom, geany, juffed don't have such wrapping - but they have all in common that Ctrl-W close the current/active tab. And to be true - nano vs vim sucks enough as the uncommon shortcuts prevent me to use more advanced things - back in time (1991) i get a 20 page short manual for vi - i hate vi since than. So at least modern apps should have the same shortcuts for basic operations - but thats only my 2 ¢

**Comment by agaida** [comment]
Btw - while we are at it - how to remove a shortcut (unset) a shortcut in the UI?

**Comment by tsujan** [comment]
There's no way for it. What's the benefit (just asking)?

**Comment by tsujan** [comment]
Actually, I intentionally removed that possibility in the shortcut editor ;)

**Comment by agaida** [comment]
thats easy - i tinkered a little bit with and made some moronic shortcuts - and wanted to remove them. ok, one can do this in the config file, while the application is not running. Intuitive and user friendly :P

**Comment by agaida** [comment]
more serious, sometimes i want to disable certain shortcuts - and the standard ways is just to remove the bound key combination

**Comment by tsujan** [comment]
There's a `Default` button when there's a mess (for example, when the shortcuts are ambiguous and the user doesn't have time to check them).

> sometimes i want to disable certain shortcuts

Why? Any real benefit?

**Comment by tsujan** [comment]
You could use `Ctrl` in such shortcut editor and the shortcut will be removed but in the case of FeatherPad, it will come back alongside a message. All that is intentional and I had a hard time to make an "inteligent" shortcut editor.

**Comment by agaida** [comment]
real benefit - working much with nano  and other editors - so i mostly disable STRG-Q/STRG-W - because STRG-W is search in nano :D

**Comment by tsujan** [comment]
I completely agree, but not when I see myself (= developer) doing them ;) Joking aside, that old saying shows genius. The more fear of doing wrong things, the less IQ.

**Comment by agaida** [comment]
```cpp
#ifndef Q_OS_WIN
    // Check whether we are running as root
    if (getuid() == 0) {
        std::cout << "Executing Dolphin as root is not possible." << std::endl;
        return EXIT_FAILURE;
    }
#endif
```
as long we consider not to do such utter crap like that all things are fine - M. Flöser (former known as M. Graesslin in dolphin and kate)

**Comment by tsujan** [comment]
> as long we consider not to do such utter crap

Oh, NEVER! That was absolute crap, like what Gnome devs do ("à la mode" nowadays?) You know how much I hate such things. I use FeatherPad as root a lot.

Let me explain something:

The app shouldn't forbid "stupid" things, as we agree, but *can* give some hints to the user. When there are many shortcuts -- as is the case with FP -- it's better to do that. On the other hand, it was a challenge and I took it happily ;)
