### ISSUE TITLE
Custom darkScheme Colors?

### ISSUE THREAD

**Issue by githububub** [tsujan/FeatherPad#12]
The default of white on black provides too much contrast and increases eye strain during long editing sessions. Is there a setting to set the bg to #222 and fg to #eee?

**Comment by tsujan** [comment]
The darkness of the background is carefully chosen so that, with syntax highlighting, all colored texts are seen easily. It's not just about black and white.

However, with a default background color of `#0f0f0f`, adding a darkness setting to the Preferences dialog won't do any harm. I'll figure out the best way of doing it.

**Comment by tsujan** [comment]
BTW, `#eee` isn't dark at all ;)

**Comment by githububub** [comment]
Awesome. Also, how do we force the syntax highlighting of files? For example `.profile` and/or `.dashrc`?

**Comment by tsujan** [comment]
Syntax highlighting can't be forced but can be turned off. Files should have a mime type other than `text/plain` for syntax highlighting to work. Many common programming languages are covered but, of course, not all.

However, I've covered some special `text/plain` files too, like `.xprofile`, `.directory`, etc. I'll add `.profile` and `.dashrc` to the list. Do you know of any other special `text/plain` file with a *fixed programming language* that isn't covered?

**Comment by githububub** [comment]
.mkshrc and the Zsh config files (e.g. .zprofile, .zshrc).

**Comment by tsujan** [comment]
All right. It may take some time but I'll add them before the next release. Thanks for the suggestions!

**Comment by githububub** [comment]
No worries. I found what I needed in `syntax.cpp`. Thanks for listening, great work on FeatherPad. Definitely lean and mean. It is now my default plain text editor across two stations :)

**Comment by tsujan** [comment]
Added an option for the color value of the dark scheme bg. The max is 50 and the default is 15. Please test!

**Comment by githububub** [comment]
I have it set to 35 right now and will author a few web pages at night with a few others. I already note reduced eye strain with the dark scheme under daylight conditions. Absolutely fantastic!

**Comment by githububub** [comment]
25-40 seems to be the sweet spot for most of our boxes which includes a mix of color calibrated desktops and laptops with varying monitor specs. Allowing us to gain/reduce contrast within the application without having to modify monitor contrast has improved the accessibility of featherpad. Awesome job.

**Comment by excalibur1234** [comment]
i am using the "20" setting for the dark background.

well done!

**Comment by tsujan** [comment]
Glad to know that you've found this new option useful. I use 27.
