### ISSUE TITLE
Search history as popup

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#120]
Just used fpad for a relative big change with much searching - marking the search string with mouse, empty the search field and paste with ctrl+k ctrl+v is fine and work like charm - the only annoying thing is that i don't have a history, so i can't look, what i have searched some minutes ago :)

**Comment by tsujan** [comment]
Each tab has its own search history. You could see them by using `Ctrl+Z` when the search line-edit has focus. Actually, a year or 2 ago, I made tab search histories independent from each other because I was interested in the search history.

**Comment by agaida** [comment]
oha - cool, thanks

**Comment by tsujan** [comment]
BTW, that's not the case with pcmanfm-qt's filter-bar. I noticed it at that time but didn't see any need for tab-dependent filter histories with pcmanfm-qt.

**Comment by agaida** [comment]
for pcmanfm-qt it is fine i think - but for such changes i need all help i can get:
https://salsa.debian.org/lxqt-team/libfm-qt/commit/636c0537ae56991d496fa510aec7c8805e6bb699#3470a6970a4b7ede68420f02bada8189a894b7a0
https://salsa.debian.org/lxqt-team/libfm-qt/commit/da5049a84982abae2526b7391c506aba72ef6c7a#3470a6970a4b7ede68420f02bada8189a894b7a0

fpad is fine for such jobs :P

**Comment by tsujan** [comment]
In the case of search, we use FP in similar ways. When reading/checking codes, I need to search for many function names in several source files (did it for Krita's issue hours ago) and then find some functions I searched for before, while I may not remember their names.

**Comment by agaida** [comment]
ever thought of cursor down and up to scroll through the history and on history end just empty the the search field? i like this in atom

**Comment by tsujan** [comment]
The history list as a popup? I'll think about it.

**Comment by tsujan** [comment]
This is veeeery tricky. Everything in `QLineEdit` is against it. A big subclass is needed. My plan is a small arrow on the right of the search line-edit but inside it, which, if clicked, shows a men/popup containing the last n (n ≤ 20) undo items. The items should be updated constantly.... I don't know how long it'll take.

**Comment by tsujan** [comment]
OK, Qt makes everything too easy -- no surprise that Qt programmers are so lazy ;) It's a piece of cake:

![combo](https://user-images.githubusercontent.com/981076/39102107-1afb8424-46b6-11e8-91bc-8b41aa26c510.png)

However, before making a commit, I should do 2 things:
(1) Release  V0.8.1; and
(2) Decide about long and, especially, multi-line searches.

Fortunately, Qt doesn't make (2) easy and I could do some real work.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/b3fefc1b7ff44a95b5c27c606c6bc1ef33c68b5a

`Ctrl+Z` and `Shift+Ctrl+Z` -- inside the search-bar -- are still for the typed text but the tab-specific history of the last 40 searched texts is on the popup. I didn't see a need for more than 40 items but tell me if you think more are needed.

It looks practical but I'll test it for a while.
