### ISSUE TITLE
Deletion via [Backspace] doesn't update registered cursor position

### ISSUE THREAD

**Issue by aramazano** [tsujan/FeatherPad#122]
As a test case we have these two lines:
("_" represents the cursor)

123_4567890
1234567890

Press [Backspace] thrice, now we have:

_4567890
1234567890

Press [Down] arrow, and it will be:

4567890
123_4567890

Whereas it should have been:

4567890
_1234567890

Deletion via [Del] key doesn't have this issue.

**Comment by tsujan** [comment]
I'm aware of it. It should be how `QPlainTextEdit` works -- I did nothing about it in the code.

Although it's a little strange to me too, I don't know whether it's a good idea to "correct" it. Since the position of Backspace is preserved, some users might consider it like a feature -- and, IMO, they would have right.

**Comment by aramazano** [comment]
Not a big problem. As all the other editors I have used behaved the other way, this behavior has caused me to mis-edit neighbor lines a lot. This forces me to be extra careful when typing, which in turn slows down editing speed a bit - but not much.

Nevertheless, I feel that keeping up with cursor position with back-deletes would make featherpad more streamlined with the rest of text editors.

**Comment by tsujan** [comment]
I have no problem with its removal -- as I said, the first time I saw it, it was counter-intuitive to me.

Let's get rid of it! If someone sees it as a feature, I'll ask how.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/b3fefc1b7ff44a95b5c27c606c6bc1ef33c68b5a

While working on it, it became clear to me that it should be a Qt bug, not a feature. Thank you for this reminder!

At the same time, the idea of `Shift+Ctrl+Up/Down` for moving line(s) upward and downward occurred to me and I implemented it. Several lines can also be selected from any positions of the first and last ones and moved in this way. Added it to Help too.

Although Help explains the hidden shortcuts, since it's too long to be translated, a separate translatable dialog might be needed for them at some point. I may add it before releasing V0.8.1.

**Comment by aramazano** [comment]
@tsujan

Thank you. And I think the Shift+Ctrl+Up/Down is also a cool addition. :)

I haven't tested the patch (still using 0.8 on Debian) but I have just found a similar behavior with [Enter] key here.

Original 2 lines: ("_" is the cursor)

1234567890_
1234567890

Press [Enter] :

1234567890
_
1234567890

Press [Down] arrow :

1234567890

1234567890_

Whereas it should have been:

1234567890

_1234567890

I don't know if the latest fix covers this as well.

**Comment by tsujan** [comment]
> I don't know if the latest fix covers this as well.

Yes, it fixes all such cases, which are related to Up/Down keys.

I didn't know about the `Enter` case at all. This is definitely a Qt bug and I know where it is (in Qt's cursor movement code). I'll report it if I have time. Anyhow, FeatherPad has its workaround now.

> And I think the Shift+Ctrl+Up/Down is also a cool addition

It's useful. I found it by chance, when I was making the workaround.

A "Text Shortcuts" menu-item with a translatable dialog is needed for users to get familiar with such shortcuts.

**Comment by agaida** [comment]
@aramazano - you might have a look at https://lxqt.debian.net ...

**Comment by aramazano** [comment]
@tsujan thank you, it's good news that a single fix closes multiple issues. Yay! :)

@agaida thank you both for maintaining the repo and tipping me on about it. :)

Added below stanza to apt preferences:

Package: *
Pin: origin "lxqt.debian.net"
Pin-Priority: 10

**Comment by agaida** [comment]
pinning is much to complicated and overrated - just use it with the standard priority :P - most of the time it is safe. And if you are running testing or sid you should be used to read apt output :P

**Comment by aramazano** [comment]
@agaida I am running testing and have given priority 10 to experimental repo (unstable=20) so that only the packages I explicitly specify will install from them (no auto upgrades). Otherwise all my LXQt environment would get upgraded to experimental level at the next upgrade, and since LXQt is my "production" environment, it can affect my everyday usage.

In case a package I cherry pick to install/upgrade from experimental depends on yet another experimental package, then the installation will fail and then I can retry it by explicitly giving the failed packages along with the one I want. This way, I can install/upgrade what I want, holding back the others.

(I am assuming there are no packages with undeclared inter-dependencies in the experimental repo.)

This scheme allows me to follow LXQt components with 1 to 3 month's lag, striking a conservative compromise between testing the latest features and having a stable work environment. As for the packages I am focused on and want to test the bleeding edge, I can always install them explicitly from experimental.

This was my reason for pinning down the experimental.

However, I can assign default priority to experimental if there would be no frequent/major stability issues with it. I can't foresee that without trying (or having been told :)

**Comment by agaida** [comment]
thats the reason for this repo - its built against sid and contain only LXQt and related packages - and i recommend sid, faster and shorter breakages and better security.

**Comment by aramazano** [comment]
> its built against sid

Yet pitting experimental-snapshots against Testing didn't cause any problems so far. Anyway, dependency resolution would either allow me to use dependencies from Testing, or force me to install an odd dependency from Sid. I am depending on dependency resolution. :)

> BTW - the distribution is experimental-snapshots - and has nothing to do with experimental

Oh yes, sorry it was my sloppy writing. I was too lazy to type the full name, so I used "experimental" as a shorthand, but it creates ambiguity with the real Debian/Experimental distribution.

Alright, I removed the pinning from LXQt experimental-snapshots and did a fresh update + distupgrade. Now I am fully on experimental LXQt. Expect some more bug reports. :)

BTW, I wonder why 0.8.1 (according to Help->About) is versioned as 0.9~24-g33f37c2-1 in experimental-snapshots?

**Comment by tsujan** [comment]
@aramazano You and I were both wrong about this. The backspace scenario was really a feature, not a bug. It's useful when the user wants to remove a character in several lines. I remembered that I did so sometimes.

I'll revert all these changes soon.

**Comment by tsujan** [comment]
I restored Qt's default behavior.

If someone wants to remove all a's manually from this text:
```
a     b
a    c
a   d
```
That'll be easy with Qt's default behavior, which we wrongly saw as an issue.

**Comment by aramazano** [comment]
My approach was from behavioral consistency point of view. As long as the neighbor line structure permits, Up and Down keys should move the cursor vertically, IMO. Of course it is up to you to decide how it should behave.

As for this specific example, I use Del.

**Comment by tsujan** [comment]
I wanted to remove some "-" signs from a copy-pasted diff file quickly, as I'd done several times, but noticed it wasn't possible. Other users may do similar things out of habit. Qt developers should have had a good reason for this.
