### ISSUE TITLE
full path in window title again

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#124]
Can we make this optional please? The current state sucks a little bit :p

fpad $(grep -rl github.com/lxde \*/\*/debian/copyright | uniq) result in:

```
compton-conf/compton-conf/debian/copyright
liblxqt/liblxqt/debian/copyright
libqtxdg/libqtxdg/debian/copyright
libsysstat/libsysstat/debian/copyright
lximage-qt/lximage-qt/debian/copyright
lxqt-about/lxqt-about/debian/copyright
lxqt-admin/lxqt-admin/debian/copyright
lxqt-branding/lxqt-themes-extra/debian/copyright
lxqt-build-tools/lxqt-build-tools/debian/copyright
lxqt-common-deprecated/lxqt-common/debian/copyright
lxqt-config/lxqt-config/debian/copyright
lxqt-globalkeys/lxqt-globalkeys/debian/copyright
lxqt-l10n/lxqt-l10n/debian/copyright
lxqt-notificationd/lxqt-notificationd/debian/copyright
lxqt-openssh-askpass/lxqt-openssh-askpass/debian/copyright
lxqt-panel/lxqt-panel/debian/copyright
lxqt-policykit/lxqt-policykit/debian/copyright
lxqt-powermanagement/lxqt-powermanagement/debian/copyright
lxqt-qtplugin/lxqt-qtplugin/debian/copyright
lxqt-runner/lxqt-runner/debian/copyright
lxqt-session/lxqt-session/debian/copyright
lxqt-sudo/lxqt-sudo/debian/copyright
lxqt-themes/lxqt-themes/debian/copyright
lxqt-wm-helper/lxqt-wm-helper/debian/copyright
obconf-qt/obconf-qt/debian/copyright
pavucontrol-qt/pavucontrol-qt/debian/copyright
pcmanfm-qt/pcmanfm-qt/debian/copyright
qterminal/qterminal/debian/copyright
```
not so much files, but i was forced to do the */snapshot/debian/copyright in a separated batch, just to don't get confused

![](http://i.imgur.com/ixfbk5y.png)

**Comment by tsujan** [comment]
It should be easy but please tell me why you think the *instant* tooltips of tabs aren't enough. Force of habit or something practical? With tooltips, you even don't need to switch tabs to know the path and they instantly show up. What's the practical advantage of paths on titlebar?

**Comment by tsujan** [comment]
OK, you don't want to put the cursor on the tab ;) I understand. Will implement it.

**Comment by agaida** [comment]
right :P

**Comment by tsujan** [comment]
I hadn't thought about the already active tab. You're right; I wouldn't have time to move the cursor over it either ;)

Now, I'm trying to do something "impossible" elsewhere; will do this as soon as that's finished.

**Comment by agaida** [comment]
It's not only about the time - one work on things, got distracted - and with the full path in the window title one knows which file one is messing up right now :P

**Comment by tsujan** [comment]
Full Ack.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/3ab4ca3bbae47c60002db8e68333d0036951daec

I didn't add the file name to the path because it's shown on the tab and may be long. If needed, the window manager will be responsible for eliding.
