### ISSUE TITLE
[Up] and [Down] behavior in wrapped lines

### ISSUE THREAD

**Issue by aramazano** [tsujan/FeatherPad#125]
I believe this is introduced by upgrading to 0.9~28-g3ab4ca3-1

On my previous featherpad version (0.9~24-g33f37c2-1), in wrapped (multi) lines, [Home] and [End] keys were sending the cursor respectively to start and end of the physical (partial) line, whereas [Up] and [Down] arrows were sending the cursor to the same column position on previous and next _**physical/partial**_ lines.

Now with this version (0.9~28-g3ab4ca3-1) [Home] and [End] keys behave the same, but [Up] and [Down] keys are sending the cursor to the same column position on previous and next _**logical/whole**_ lines.

That means I can no more easily go about within a wrapped multi-line line by keyboard.

##### System Information
* Distribution & Version: LXQt [experimental-snapshots](https://lxqt.debian.net/) on top of Debian Testing (Buster)
* Kernel: 4.9.0-4-amd64
* Qt Version: 5.10.1
* libqtxdg Version: libqt5xdg3 / 3.1.1~13-gb5ddbd4-1
* qtermwidget Version: 0.8.1~24-g4cc05f9-1
* lxqt-build-tools Version: Not installed
* FeatherPad version: 0.9~28-g3ab4ca3-1

**Comment by tsujan** [comment]
That's a side effect of the workaround I added for Backspace+Up/Dow. It seems I should find a totally different approach :(

Thanks for reporting!

**Comment by tsujan** [comment]
OK, this can be fixed easily by modifying the workaround  :) It's enough to work with lines, instead of "blocks" -- something I should have done from the beginning. Will make a commit today, as soon as I get home.

**Comment by tsujan** [comment]
Killed four birds with one stone in https://github.com/tsujan/FeatherPad/commit/ccdb2f5602d086ddf3cf4ae029cc2d68de739301 ; hence the delay.

(1) The issue reported here is fixed;
(2) `Ctrl+Up/Down` is added for scrolling by one wrapped line without moving the cursor;
(3) `Meta+Up/Down` is added for going to the same position in the previous/next *unwrapped* line (= block); and
(4) If `Meta+Shift+Up/Down` is pressed, the text will be also selected in addition to going to previous/next unwrapped line.

I added a short explanation to Help too.

@agaida From @aramazano's attached info, I guess the package you make has version "0.9~..." but the next release will be 0.8.1. Won't that cause a problem later?

@aramazano You could wait until @agaida updates the deb package but if you want to test the changes without installing FeatherPad, you could open a terminal inside the latest source, issue `qmake && make`, and after the compilation is finished, open FP with `./featherpad/featherpad` in the same terminal. Of course, all instances of your installed FP should be closed before that.

**Comment by aramazano** [comment]
Thank you! That's amazing. Delay? It's a same-day fix. :D

**Comment by agaida** [comment]
@tsujan - you know that i'm lazy - so i have prepared a nice and lazy solution for the snapshot packages :smile: - in debians lxqt-build-tools is a script called git-snapshot and in the snapshots packages is a file called debian/repository.spec - so all one must do is to enter the source path and type git snapshot;; debuild -j$n and after all things are compiled apt install ../*deb :D

**Comment by tsujan** [comment]
@agaida Yes, you and I are the "laziest" LXQt members, as facts show ;) And I thought only *I* was hyperactive.....

As for 0.9, there's no problem anymore because I'll make it 0.9.0 with the next release.

**Comment by agaida** [comment]
i wouldn't call it hyperactive - there are reasons why i bought the piledriver and will switch to a current i7-8xxx soon - i think it's called ~ENOTIME && ~EMUCHTODO - so having tools that speed up some things is a fine thing. Thats why i in love with featherpad. featherpad is the only editor i know that have the speed and is able enough to fully replace nano some day.
