### ISSUE TITLE
featherpad doesn't create new tabs with nonexistent files

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#127]
![screenshot](http://i.imgur.com/16hHGN8.png)
^^ something goes south

latest git ~29-gccdb2f5-1

**Comment by tsujan** [comment]
Please be a little more specific. You mean you click the new-tab toolbar/menu item and no new tab is created? That isn't the case here.

**Comment by agaida** [comment]
i tried fo open an file that not yet exists - on  cli as in the picture above - expected have libqt5xdg-dev.example opend instead of untitled

**Comment by tsujan** [comment]
> i tried fo open an file that not yet exists

Oh, that's the expected behavior. When the file doesn't exist, no empty tab will be created.

**Comment by agaida** [comment]
please try nano foo | geany foo | kate foo | atom foo | mousepad foo - if the file not exists it should be created

**Comment by agaida** [comment]
use case - i maintain some projects, something change - in that special case i bumped debhelpers to >= 11~. That introduced a new behaviour - now debhelper search and install examples and give a warning if examples are not installed - next step: fix it and install the examples

To do so i need a new file and type: featherpad $packagename.examples and expect that i just have to write examples/* into it - saving the result with Ctrl-S, Ctrl-Q and be done with

**Comment by tsujan** [comment]
OK. That's a good use case I hadn't thought about. Will implement it soon. Thanks for the explanation!

I wonder in how many ways a text editor can be used ;)

**Comment by agaida** [comment]
and we are just at the begin of that journey :)

**Comment by tsujan** [comment]
BTW, with so many changes, I'll increase the version number to 0.9.

**Comment by tsujan** [comment]
OK, I will.

**Comment by tsujan** [comment]
@agaida Before I do it, could you tolerate the message `The file does not exist.` on the message bar? The message bar is at the bottom and doesn't interfere with text editing but it reappears whenever the page gains focus. I think it's a good sign showing that the file isn't saved yet.

If you say "no, I can't tolerate it," my work will be hard ;)

**Comment by tsujan** [comment]
And, is `Die Datei existiert nicht.` a correct German translation for it (file → Datei, in computer?)

**Comment by agaida** [comment]
a) i can tolerate it - np
b) it is

**Comment by tsujan** [comment]
Very nice! The code structure already has room for this; just a few things should be changed with care...

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/bb9ee0cce483fb41cbab8dd576adb9a7ed8ad11b

It was too easy; as if my unconscious had thought about it before. Please test!
