### ISSUE TITLE
Partial Syntax Highlighting

### ISSUE THREAD

**Issue by githububub** [tsujan/FeatherPad#13]
Code and/or markup is only partially highlighted upon opening a page. For example, out of 72 visible lines only 48 are syntax highlighted. Syntax highlighting only completes as the page is scrolled. This is repeatable across multiple workstations.

**Comment by tsujan** [comment]
I can't reproduce this. Do you use the latest github version?

If you use the latest version, what's your distro, desktop environment and *especially* Qt5 version?

Please also paste your `~/.config/featherpad/fp.conf` here!

**Comment by githububub** [comment]
Commit c733e3c and fbb90ff. Arch. dwm. All Qt modules are 5.8.0. See [GIMP  PKGBUILD](http://i.imgur.com/zccX6kw.png). 

>[text]
darkBgColorValue=40
darkColorScheme=true
font="Noto Mono,10,-1,5,50,0,0,0,0,0,Regular"
lineNumbers=true
maxSHSize=2
noIndent=false
noSyntaxHighlighting=false
noWrap=false
scrollJumpWorkaround=false

>[window]
hideSearchbar=true
noMenubar=false
noToolbar=true
showStatusbar=false
size=none
startSize=@Size(700 500)
sysIcon=true
tabPosition=0
tabWrapAround=false

Could it be the start size whereby only lines within the vertical 500 are highlighted?

**Comment by githububub** [comment]
Currently working around the issue with generic 4K pixel parameters `startSize=@Size(3840 2160)` though this may not be feasible with floating WMs.

**Comment by tsujan** [comment]
Wow! Now I can reproduce it with 744x1000! Will fix it soon. Thanls for reporing.

**Comment by tsujan** [comment]
It was about a very ridiculous kind of typo, as if I was drunk!! -- but I wasn't ;) Please test the latest commit!

If you didn't have a 4k monitor, I wouldn't know about it. Thanks again! And please report if there's any other problem of this kind!

**Comment by githububub** [comment]
Using the original `fp.conf` posted above and every page I test is fully highlighted. So far, so good 👍 .  Close the issue if you like :)
