### ISSUE TITLE
Creating pipes for GWakeup: Too many open files

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#133]
ok, maybe a bit to much
```
agaida@ramme ~/work/code/pkg-main/calamares/upstream (git)-[master] % find src | wc
    856     856   36391
agaida@ramme ~/work/code/pkg-main/calamares/upstream (git)-[master] % fpad $(find src)               

(process:25961): GLib-ERROR **: 15:41:38.118: Creating pipes for GWakeup: Too many open files

[1]    25961 trace trap  fpad $(find src
```

**Comment by agaida** [comment]
ok - my fault - fpad $(find src -type f) with 654 files work just fine - so it seems that fpad don't like the mixed in directories

**Comment by tsujan** [comment]
> fpad $(find src -type f) with 654 files work just fine

654?! Can it have any use? The GWakeup message may be related to trying to open thousands of files and, if that's the case, it should happen with other apps too.

> it seems that fpad don't like the mixed in directories

Please explain that. If there's a problem, it should be fixed.

**Comment by agaida** [comment]
ok - 856 or 654 is of no use - just opend the wrong path, didn't know it was that big :D

ok, it was the calamares src dir, at the first attemt i opend it with
```
fpad $(find src)
```
after GWakeup message and the trap i was stubborn enough to filter out the directories
```
fpad $(find src -type f)
```
That opens the 654 files, not the best of all ideas, but it works without problems. The only problem was a extra long file with minified code i guess that couldn't be rendered because of a to long line

**Comment by tsujan** [comment]
>  it was the calamares src dir

I'll get its source to see that first hand.

**Comment by tsujan** [comment]
Here, `fpad $(find src)` worked. I think that depends on the computer.

I should add the number of opened tabs somewhere; it's an important info. I found 2 small problems too; will look into them.

**Comment by tsujan** [comment]
BTW, doing `kate $(find src)` was an impossible task, which never ended and took about 1 GiB of memory (Featherpad used ~100 MiB after the job was finished).

**Comment by tsujan** [comment]
There are many non-text files (especially, PNG images) among them. Opening them is costly. A mechanism is needed for filtering them out. The easiest way is using the extension because checking mimetypes may be expensive on loading. I should think about whether this should be done on the command-line level or as a setting,

Your thoughts?

**Comment by agaida** [comment]
how costly is a mime check?

**Comment by tsujan** [comment]
Haven't tried it at this stage. FeatherPad checks it after opening the file only if there's no extension; if there's an extension, it'll be accepted and no mime check will be done.

I think there's a another way to exclude non-text files altogether. Should get my hands dirty to know that for sure.

**Comment by tsujan** [comment]
I'll go with this, unchecked by default:

![nontext](https://user-images.githubusercontent.com/981076/39410332-6f087594-4c0c-11e8-9081-079b93a9a988.png)

FeatherPad usually needs to read only 4 characters to know that a file isn't a text file. Actually, all of those ~600 files are read in a very short interval (in a separate thread); it's the Qt GUI that takes the time to load them as texts.

I think there may be no need to set a limit to the number of opened files. If it's too great, GLib will show a warning as in your case (why not for me, I don't know). And the user knows he's going to open 600 files, so he'll wait.

As for the number of pages, I didn't find a good place for it -- the status-bar is for each page. I don't think it's important -- unless for debugging, in which case a line of code could be added temporarily.

**Comment by agaida** [comment]
looks good

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/05af5d0f752fab41932b8aba21f30da1df173445

I also found a good place for the number of pages (>1) and added it there, namely the tab/side-item context menu and as a top label on it. Also, fixed a small issue.

**Comment by tsujan** [comment]
Related to the terminal warning:

In `/proc/sys/fs/file-max` I have 1600880; perhaps, yours was smaller or, for some reason, you already had many opened files with some processes.

**Comment by agaida** [comment]
% cat /proc/sys/fs/file-max 
3251016

**Comment by tsujan** [comment]
Then, there might be a wild process.
