### ISSUE TITLE
disable trim trailing whitespaces when working with diffs

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#139]
really, removing these things from a diff is not the best of all ideas :grinning:

**Comment by tsujan** [comment]
Telepathy?! Today, I encountered the same problem and decided to make an exception for diff files :)

**Comment by agaida** [comment]
PR 186 libfm-qt :P

**Comment by tsujan** [comment]
Exactly! We're both pragmatic ;)

**Comment by tsujan** [comment]
Will fix it after seeing the last episode of Longmire; just started.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/d74e596c9cf12e749bfad6870a535103d11dcb54
