### ISSUE TITLE
URIs in Comments Highlighted as URIs

### ISSUE THREAD

**Issue by githububub** [tsujan/FeatherPad#14]
Currently, a commented URI (e.g. file:// https://) is highlighted as a URI. The expectation for any string which follows a `#` comment to be highlighted as a comment. Is featherpad syntax highlighting designed to have URIs take precedence over comments?

**Comment by tsujan** [comment]
That's intentional -- I've added lines of code for it. I wanted url's to be picked up easily inside comments. I don't think it could cause any mistake (it hasn't for me).

**Comment by githububub** [comment]
Understood. It has not caused any problems outside of what I had expected. Case closed on this one as well :)
