### ISSUE TITLE
Make the cursor better visible

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#146]
Maybe with a thicker vetical bar or so:  
U+02759 ‭ ❙  GC=So SC=Common       MEDIUM VERTICAL BAR - maybe this one.   
Working with featherpad become stressful for the eyes after a few hours.

**Comment by agaida** [comment]
bah, nonsense - just make it one or two pixel thicker if possible

**Comment by tsujan** [comment]
3 pixels look too thick to me but a 2-pixel cursor looks good. An option may be needed for it. I'll think about it.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/7437800022a94bde428839f665658b15e033b47e
