### ISSUE TITLE
show tab bar only for multiple tabs

### ISSUE THREAD

**Issue by excalibur1234** [tsujan/FeatherPad#15]
i would like an option to show the tab bar only when opening a second tab.
there is not really a need for a tab bar when i have only 1 tab open.

80% of the time, i have only 1 tab open. in those cases i do not need to see a tab bar.
20% of the time, i have 2 or more tabs open. in those cases, i really need a tab bar to switch between those tabs.

**Comment by tsujan** [comment]
Good idea! I wanted to publish the next release -- but not before implmenting this ;) Will add an option for that.

**Comment by tsujan** [comment]
Done. Please test!

**Comment by excalibur1234** [comment]
i have just tested it on an xfce system. it works!

i will test on my main lxqt system tonight and report back.
