### ISSUE TITLE
wishlist for kwrite users...

### ISSUE THREAD

**Issue by excalibur1234** [tsujan/FeatherPad#16]
i have switched to featherpad-git from kwrite. well done!

the only feature in kwrite i miss in featherpad is the "document preview" in a thick vertical scroll bar.
it is really useful for quick jumping to a place in long documents.

if there is an easy option in qt5 for including something like this, please do so.
if this would require a lot of work (or even worse: require kde dependencies), please mark this issue as "won't fix" and close it.

**Comment by tsujan** [comment]
Actually, I dislike it ;) But since FeatherPad isn't just for me, I'll think about it after the next release. I have to see if it doesn't require lots of extra code because otherwise, it'll change FeatherPad to IronPad ;)

**Comment by tsujan** [comment]
Sorry for the long delay! A long time has passed and several practical features are added to FeatherPad. As for this one, I don't think it would be practical or worth the amount of code, time and extra resources. Finding (single or several) lines in a long doc is as simple as scrolling; or if the strings are known, as simple as using the search bar ;)

**Comment by tsujan** [comment]
Or if the visual form of lines is remembered (which is the case with "document preview"), Ctrl + mouse wheel could be used for zooming out and finding the pattern -- then Ctrl+0 could be for un-zooming.
