### ISSUE TITLE
line highlighting and active line endings

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#161]
Wrong
![](https://i.imgur.com/6mT1oqS.png)
Right
![](https://i.imgur.com/YZSMSDO.png)
if the whole line is highlighted, even this minimal highlighting is visible and useful

**Comment by tsujan** [comment]
Bad news:

This seems like a Qt bug. I checked the code: `QTextFormat::FullWidthSelection` is set correctly, which means the full width should be highlighted in all cases, whether new-lines are shown or not. I tried several workarounds but none of them worked.

**Comment by agaida** [comment]
10 or 11?

**Comment by tsujan** [comment]
Good news:

I polished the unusual workaround and was surprised to see it working :)

**Comment by agaida** [comment]
thats nice - i'm a bit de-motivated today - so closed the light-locker bug (left a screencast) and will play a bit with some really insane git things and translations :)

**Comment by tsujan** [comment]
> i'm a bit de-motivated today

While you provided me with a big motivation.

This report showed a hidden Qt issue that I even don't know how to report to Qt bug tracker-- and I won't because (1) I found an exciting workaround for it and (1) I hate denials or replies like, "please provide a simple code...." (which seems impossible).

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/f425f4d6233caf550aa5d6e28018ec5d27b5fdc0

**Comment by tsujan** [comment]
@agaida Although I use nothing but FeatherPad, I hadn't seen this issue. I should admit that your observational faculty is sharper than mine. Please keep telling me about such minute details!
