### ISSUE TITLE
Featherpad always open a file in a separate window

### ISSUE THREAD

**Issue by pierretom** [tsujan/FeatherPad#164]
Hi,

To reproduce:
- Open Featherpad.
- Verifiy "Always open in separate windows" is disabled in preferences.
- Reduce Featherpad in taskbar.
- Open a file from a file manager.

Result: it opens in a new window.
Note that if Featherpad is kept open (not reduced), it will open in the same window.

Featherpad 0.9.0.
Taskbar : tested with LXPanel and LXQt panel.

**Comment by tsujan** [comment]
> Reduce Featherpad in taskbar.

You mean "minimized". That's by design. A new tab should never be opened in a minimized (hidden) window; otherwise, it'll be useless.

**Comment by pierretom** [comment]
Hi tsujan,

I thought about what you said and in my opinion, the application should respect user preferences.
e.g. If a user has disabled "Always open in separate windows" in preferences, then the application should not open in a separate window, even if it's iconified in the taskbar.

**Comment by tsujan** [comment]
IMO, the app should be *usable*, in the first place.

This is not the only example that FeatherPad opens a new window. If the current FeatherPad window has an open dialog, the next file will be opened in a new window on the same desktop. The reason is as above: usability.

**Comment by pierretom** [comment]
You are overriding user preferences to make the application usable, it should not happen.

**Comment by tsujan** [comment]
> You are overriding user preferences to make the application usable, it should not happen.

Actually, opening a file in a hidden window would be an annoying bug and that's what should not happen.

**Comment by tsujan** [comment]
BTW -- maybe you don't know about this feature -- tabs can be dragged from one window and dropped into another. The new window could be merged into the old one in this way.
