### ISSUE TITLE
building on OS X failed due to x11extras

### ISSUE THREAD

**Issue by 3lackrush** [tsujan/FeatherPad#168]
Error message: 
Project ERROR: Unknown module(s) in QT: x11extras
make: *** [sub-featherpad-make_first] Error 3

**Comment by tsujan** [comment]
Currently, FeatherPad is only for Linux/*BSD. With some changes, I think it could work under OS X too but I don't have OS X to test.

**Comment by shlyakpavel** [comment]
>  but I don't have OS X to test.

I guess I can help you setting a VM if you need :)

**Comment by tsujan** [comment]
> I guess I can help you setting a VM if you need :)

Actually, this is fixed for a while and you completed the fix by introducing Mac support.

I install various Linux distros and FreeBSD on VirtualBox but I have no knowledge about Mac. If I find enough free time, I'll think about it and ask you for help :)
