### ISSUE TITLE
Option to have full path of file in titlebar

### ISSUE THREAD

**Issue by xircon** [tsujan/FeatherPad#18]
Could the title bar include the full path of the file being edited?

Two reasons: 
- When editing two files of the same name but different paths, it would help distinguish which file I am editing
- I have an idea about my previous request for a run file option, this would help me not hardcode a path.

**Comment by tsujan** [comment]
I've put the paths on *tab tooltips* and made those tooltips show up *without delay* exactly for the purpose you mentioned. Moreover, you could copy both file name and file path by right clicking on a tab.

FeatherPad is made in such a way that it's both compact and informative. The needed info is put in different places: window name, tab tooltips and statusbar (which can be shown by default through Preferences or with Ctrl+Shift+D). You would just need to get familiar with FeatherPad by using it more and more ;)

**Comment by tsujan** [comment]
And I didn't understand what you meant by "run file option".

**Comment by xircon** [comment]
I asked if it was possible to run a file from featherpad, you said no, I said I was lazy :D So I have written a script to run the file in the title bar, but I have had to hard code the path :(

```
#!/bin/bash
line=`xdotool search  --class featherpad getwindowname %@ | grep -vn featherpad |cut -f1 -d:`
title=`xdotool search  --class featherpad getwindowname %$line`
run="/home/steve/scripts/Roku-Remote/$title" 
eval "$run"
```
Assign to a hot key (I run plasma and use super+r) it will launch the script **if it has a shebang & is a gui based script**  The above runs the roku remote I am writing in python from featherpad.

Line 4 has a hard coded path - I would like to pick this up from the title bar.

It should be straightforward to adapt to non-gui scripts, to say, launch a terminal, compile, run.

Hope that makes sense.

**Comment by tsujan** [comment]
Does adding of commandline options solve your problem? For example, `featherpad --currentPath`, `featherpad --currentName` and `featherpad --currentFile`?

**Comment by tsujan** [comment]
Please see: Those options don't exist yet. I mean do they solve your problem if I add them?

**Comment by xircon** [comment]
Yes they would, thank you very much.

**Comment by xircon** [comment]
Would probably need both:
e.g.
/path/to/file.name

**Comment by tsujan** [comment]
I'll try to add CL options for:
(1) Path;
(2) Name; and
(3) File (which means `Path/Name`).

Theoretically, they should give the needed info for the active tab of the *last focused window*. That may require a lot of changes. I'll tell you if I succeed in implementing it.

**Comment by xircon** [comment]
Again, many thanks for your program and your assistance.

**Comment by tsujan** [comment]
You're very welcome! Actually, I am the one who should thank because:

Now that those options are going to be added, it's better to be more thorough and add more CL options (extension, name without extension, word count, encoding, etc.). All options could be seen with `featherpad -h` or `featherpad --help`. The idea seems great but its implementation may take some time.

**Comment by tsujan** [comment]
After playing with various options, I decided to take a much simpler approach, namely, that of adding a keyboard shortcut (ctlr+E) for running executable shell, python,... files, directly or in a terminal emulator chosen by the user (in Preferences). This is almost what you wanted at https://github.com/tsujan/FeatherPad/issues/17.

Contrary to what I though before, it had no effect on FeatherPad's lightness, while the method I'd planned here was too complex.

Please test! See the Preferences dialog for options and explanations (as tootip or WhatsThis).

**Comment by xircon** [comment]
Brief test - works well, late here will test more extensively tomorrow.

**Comment by tsujan** [comment]
> Brief test - works well, late here will test more extensively tomorrow.

Then please test wit the latest version -- several changes are made in hours.

**Comment by tsujan** [comment]
With the latest commit, all outputs (both ordinary outputs and error messages) will appear on an appropriate dialog if no terminal command is added. The dialog uses a scrollable text-edit so that there's no limit to the amount of the information and the script file(s) can be edited and run indefinitely.

I'm getting addicted to this way of editing/writing bash scripts -- it's feels so comfortable ;)

**Comment by xircon** [comment]
Apologies for not getting back to you.  I was on days off (I work for the health service), but was called into work to cover a colleague's sickness, so now am not off till Sunday, but then not back till Thursday, so will have plenty of time soon.

Will update with pacaur now, got an hour to have my breakfast before work :)

**Comment by xircon** [comment]
Again very brief test - absolute genius!  Time to get ready for work............
