### ISSUE TITLE
Support for non-X11 platforms?

### ISSUE THREAD

**Issue by khallebal** [tsujan/FeatherPad#185]
Hi,
This editor is too cool, and i'd love to see it running in Haiku, and have it as my main development  editor, i tried to compile it on Haiku but the X11 code get in the way of successful build, can we hope to see support for the non-X11 platforms in the near future?  guarding the X11 code and adding pure Qt code would be great!
Thanks for reading.

**Comment by tsujan** [comment]
I added the option `WITHOUT_X11`, so that FeatherPad can be compiled without X11 as:
```
qmake WITHOUT_X11=YES
make
```
The result will have all features except for virtual desktop awareness.

However, I don't know whether Haiku has a unix like structure; if it doesn't, compilation might still not be possible on Haiku. Please tell me if so!

**Comment by tsujan** [comment]
> If that's what you mean you're right, it doesn't, haiku does not have /usr or /share, but qmake adapts itself to any platform it supports and will find the environment to compile

Interesting!

> the only thing that won't work is the "make install" routine, unless i patch the .pro file.

Can it be done in a cross-platform way? If not, I might be able to add another option specifically for Haiku (like `ON_HAIKU=YES`) but I first need to know what changes you have in mind.

I may try Haiku on virtualbox whenever I find the time. I'd tried it many years ago, when it was in the early stages of its development, but it was rather like a demo in those times.

Looking forward to your test results.

**Comment by khallebal** [comment]
Well, it builds (almost) out of the box in haiku, 
I tried first with the "WITHOUT_X11+YES" flag
And a second build by adding " :!haiku " to
else:unix:!macx:!haiku {
  QT += x11extras
  SOURCES += x11.cpp
  HEADERS += x11.h
  LIBS += -lX11
  DEFINES += HAS_X11
}
But without the "WITHOUT_X11+YES" flag, and in both cases it compiled smoothly.

> Can it be done in a cross-platform way? If not, I might be able to add another option specifically for Haiku (like ON_HAIKU=YES) but I first need to know what changes you have in mind.

The general convention in Beos/haiku is that gui apps are installed into a folder with the same name as the app, the binary is put directly inside without the "bin" subfolder, and any data, plugins, translations and/or libs that are only needed by that app are put in subfolders inside the main folder(usualy they're called "data", "plugins", "translations" and "lib"), but often these paths are hardcoded to meet the unix structure, in these cases patching the source is required in order for the app to  find them and work properly.
in the case of FeatherPad, moving the "share" dir to the app dir seems to be enough, but moving the translations dir to the app dir and the help file to a "data" didn't work, i guess they're hardcoded to the "share" dir path.

> I may try Haiku on virtualbox whenever I find the time.

If you don't need the legay compatibility with Beos, you may want to grab the 64 bit instead of the 32 bit one, and don't use the alpha4 which is way out dated, use the nightllies or the beta which is du to be released soon.
Sorry for the long post, and thanks again for your help.
ps: if you have more questions please let me know.
Reagards.

**Comment by tsujan** [comment]
> But without the "WITHOUT_X11+YES" flag, and in both cases it compiled smoothly.

That was what I wanted to know. So, there *is* a `haiku` variable with qmake. The remaining thing is installation. If you find the correct paths, please tell me!

I tried nightly build of 64-bit Haiku in VirtualBox yesterday. FreeBSD users say if you have Linux you don't need FreeBSD. I'd tried FreeBSD and saw that first hand. The same may be true for Haiku. I have no reason to migrate away from Linux but trying other OS's and working with them under VirtualBox is fun :)

BTW, doesn't using Qt with Haiku contradict Haiku's philosophy? In https://www.haiku-os.org/about/faq/#why-not-linux, it's said:

> Linux-based distributions stack up software – the Linux kernel, the X Window System, and various DEs with disparate toolkits such as GTK+ and Qt...
>
> Instead, Haiku has a single focus on personal computing and is driven by a unified vision for the whole OS...
