### ISSUE TITLE
No v0.9.2 release?

### ISSUE THREAD

**Issue by khallebal** [tsujan/FeatherPad#190]
Hi @tsujan,
 The version in the src has been bumped to 0.9.2, but there is no release..., is this on purpose?
I need a new release tag so i can create a haikuports recipe, will there be soon a release? i can wait if that's the case.
Regards.

**Comment by jubalh** [comment]
The last release is just 10 days old.

> The version in the src has been bumped to 0.9.2, but there is no release..., is this on purpose?

Bumping in the code is good practise so it wont be forgotten when the next release happens.

> I need a new release tag so i can create a haikuports recipe

These are the only changes since 0.9.1:
https://github.com/tsujan/FeatherPad/compare/V0.9.1...master

I highly doubt you need them to create a recipe ;)

**Comment by tsujan** [comment]
Hi,

After each release, I bump version to show what will be the next release -- as @jubalh explained.

It won't take a very long time before I release V0.9.2 because it contains an important fix -- at least, in my opinion.

**Comment by khallebal** [comment]
> The last release is just 10 days old.

Oh..?, i've been using v0.9.1 already for a month!, i already have a recipe of it which uses its release tag in the url.
Anyway, that"s okay i'll wait for v0.9.2 release, thanks for the great work.
