### ISSUE TITLE
Build error: format security on singleton.cpp

### ISSUE THREAD

**Issue by yochenhsieh** [tsujan/FeatherPad#2]
Please fix format-security related errors on line 66, 83, 89 of singleton.cpp:
https://wiki.mageia.org/en/Packaging_problems_and_solutions#format_not_a_string_literal_and_no_format_arguments

**Comment by tsujan** [comment]
Thank you! I'll look into it.

**Comment by tsujan** [comment]
Fixed by https://github.com/tsujan/FeatherPad/pull/3.
