### ISSUE TITLE
Line Sorting

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#205]
Hi, just stumbled over it - can we have something like "sort selected lines asc/desc"  in the edit menu? Or maybe later a line submenu if there are other needful things like UPPER/lowercase selected lines?

**Comment by tsujan** [comment]
It should be possible but what would be its use? In most kinds of texts, changing the order of lines can create a wrong doc. Do you know of a text editor that changes lines order?

**Comment by tsujan** [comment]
OK, it may be useful in sorting lists inside ordinary texts. Will think about but I'm still curious to know if another text editor has it, although that wouldn't change anything.

**Comment by agaida** [comment]
![](https://i.imgur.com/tbvSBuM.jpg)

**Comment by tsujan** [comment]
It was a piece of cake:

![sorting](https://user-images.githubusercontent.com/981076/48970200-e404b900-f01e-11e8-99ef-df5feaa37833.png)

I think ignoring case-sensitivity isn't useful and bloats the GUI.

Now, the boring job is finding 2 shortcuts and including them in shortcut customization.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/aaf815ef2bb08a50f97668cd51efa7a39ffab9af. Didn't add shortcuts though; the items appear in the right-click menu (or are enabled in the Edit menu) with multi-line selections.
