### ISSUE TITLE
Enhancement Request: Preference for Tab Spacing

### ISSUE THREAD

**Issue by githububub** [tsujan/FeatherPad#21]
I use two, four (FeatherPad default) and eight, depending on the document. Would it be possible to add a preference to set tab spacing?

**Comment by tsujan** [comment]
In short, the answer is "no!"

More specifically, the nearest QStyle parameter to tab spacing is `QStyle::PM_TabBarTabOverlap`, whose value is set by the active style engine (Fusion, Breeze, Kvantum, ...) and shouldn't be changed by apps. Of course, apps can have their internal tab styles (or stylesheets) but, contrary to what some might believe, it's impossible to change this or that parameter and have a tab shape consistent with all style engines.

**Comment by tsujan** [comment]
Found a way to expand tabs to fill the available horizontal space. Would that be good?

**Comment by tsujan** [comment]
Never mind! It's of no practical use and adds an extra reading on startup. Closing this.
