### ISSUE TITLE
Packages not being updated in Debian?

### ISSUE THREAD

**Issue by stevenpusser** [tsujan/FeatherPad#220]
Don't know why, but I've been updating them for MX Linux and in my OBS repo, at least:
https://build.opensuse.org/package/show/home:stevenpusser:Featherpad/featherpad

**Comment by tsujan** [comment]
Seeing the title, at first I thought it couldn't be compiled on Debian ;) Debian rarely has the latest version of anything, unless in its experimental repository. Moreover, there's less activity everywhere in these days of the year, understandably.

I think your package should be usable under Debian too.
