### ISSUE TITLE
Multitouch support

### ISSUE THREAD

**Issue by shlyakpavel** [tsujan/FeatherPad#223]
Hello.
It looks like the program doesn't handle simple gestures like two-finger zoom or tab switching. Would be nice to have :)

**Comment by tsujan** [comment]
> the program doesn't handle simple gestures like two-finger zoom or tab switching

Two-finger tab switching is already possible by scrolling inside the tab bar; it doesn't need special handling.

As for two-finger zooming, it's a good idea but I should see if it's worth the extra code; have never handled touch events separately.

**Comment by tsujan** [comment]
Unfortunately, touch events are translated into mouse events here, although I followed Qt doc. Whether this is a problem in Qt or depends on the platform, I don't know. I can do nothing until Qt does what Qt doc says it does.

I might wrestle with this problem later. Until then, Ctrl+two-finger scrolling works for text zooming.
