### ISSUE TITLE
No longer compiles (not your fault!!!!!) 

### ISSUE THREAD

**Issue by xircon** [tsujan/FeatherPad#23]
I run Manjaro (Arch based), Arch have just changed the Mesa Stack and it has filtered down to Manjaro, which seems to be causing me problems compiling:
```
g++ -Wl,-rpath-link,/usr/lib -o featherpad main.o singleton.o fpwin.o encoding.o tabwidget.o lineedit.o textedit.o tabbar.o x11.o highlighter.o find.o replace.o pref.o config.o brackets.o syntax.o highlighter-html.o highlighter-patterns.o vscrollbar.o loading.o qrc_fp.o moc_singleton.o moc_fpwin.o moc_tabwidget.o moc_lineedit.o moc_textedit.o moc_tabbar.o moc_highlighter.o moc_vscrollbar.o moc_filedialog.o moc_config.o moc_pref.o moc_loading.o moc_messagebox.o   -lX11 -lQt5PrintSupport -lQt5Svg -lQt5Widgets -lQt5X11Extras -lQt5Gui -lQt5Network -lQt5Core -lGL -lpthread 
/usr/bin/ld: cannot find -lGL
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:439: featherpad] Error 1
make[1]: Leaving directory '/home/steve/.cache/pacaur/featherpad-git/src/build/featherpad'
make: *** [Makefile:43: sub-featherpad-make_first] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
:: failed to build featherpad-git package(s)
```
(Hope that is enough info)  I am assuming ```/usr/bin/ld: cannot find -lGL``` is due to this.  This is way above my level of knowledge, I assume I need to sym link something to make it work - any ideas?  Will post on the Manjaro forum shortly.

Steve

**Comment by tsujan** [comment]
I run Manjaro too but don't have this issue -- maybe because my Manjaro is "Testing" and yours is "Unstable". Tomorrow I'll think about those messages. For now, I don't think it's a FeatherPad issue.

**Comment by xircon** [comment]
Agreed.  Just a cry for help :D 
So you are aware of the approaching storm at least.

Have posted on the forum for help.  Bottom post https://forum.manjaro.org/t/mesa-stack-breaking-unstable/19366

**Comment by tsujan** [comment]
Since FeatherPad's dependencies are minimal, many Qt apps should have got this problem too. Anyway, tomorrow I'll examine the problem. Thanks for telling me!

**Comment by xircon** [comment]
Bloody hell!!! I have sorted it -
```
sudo ln -s /usr/lib/libGL.so.1 /usr/lib/libGL.so
```
Now compilesfrom AUR.

**Comment by tsujan** [comment]
Good to know that.

BTW, soon a big update will come. It's rather about the structure of the code. After it, I have plans for a better session management. Now I'm rereading the big change and will push it in 2-3 days, after some tests. Your tests would be very appreciated.

**Comment by xircon** [comment]
That was why I re-compiled - to see what/if you had pushed the new code base out, that is when I found the problem.  Whilst symbolic linking is not ideal at least it works.

I linked - ran yaourt - it worked.

I removed link - ran yaourt - it failed.

so it is the lack of libGL.so (it moved to so.1) that is the problem, do not know enough c++ - just enough!

Glad to meet another Manjarian in the wild.  I also recognised @excalibur1234 as well, it was his mention of your program that led me here ;)

**Comment by tsujan** [comment]
> Glad to meet another Manjarian in the wild.

Oh, I like Manjaro very much. After 8 years of using Debian, enough was enough (for many reasons)! About a year ago, I decided to go to Arch but didn't have time for its manual installation. So, I chose Manjaro. Its installer was the most intelligent one I'd ever seen in Linux. Manjaro is superb, especially for dev work :)

**Comment by xircon** [comment]
Ran Debian briefly (Linux Mint Debian) Nice group of people, but not for me.  Anyway, keep up the good work.  I am off work Wednesday & Thursday, can help then, if you push the code out.  If you want specific tests done let me know.

**Comment by tsujan** [comment]
The "big commit" is pushed. No big change may be seen on the surface but the code is more robust now. Tabs are made independent with regard to search and the search history is preserved for all of them.

I don't know how many times I read and tested the code ;) Hopefully no regression is introduced but if you see any problem, please tell me!

As for saving sessions, I think the current option is more practical than what can be found in other text editors because if a file isn't modified, it couldn't be of much interest. That's my opinion for now but I may add support for saving/restoring the list of all opened files too.

**Comment by xircon** [comment]
So far so good, but I got home from work at 22:30 UK time, off tomorrow and Thursday, so will test tomorrow.  One thing that confused me - the window class changed to featherpad.FeatherPad - screwed up my hotkey launcher :D All fixed now.

I still think (if easily done), a recent files (regardless of change state) section would be good, if it is easy to implement.  The wonders of Linux mean we are editing or viewing not just programs, but system files, then rebooting or log off/in.

Often I launch featherpad from a terminal, in the directory I am working in, then reboot - it would be good to have a quick way to retrieve the file - I may not have changed it though............

**Comment by tsujan** [comment]
> the window class changed to featherpad.FeatherPad

Yes! In Qt terms, the application name is FeatherPad now.

> I still think (if easily done), a recent files (regardless of change state) section would be good

OK. I 'll think about it but I don't want to lose "Recently Modified".

**Comment by tsujan** [comment]
Let's continue our discussion about recent files and session manager at https://github.com/tsujan/FeatherPad/issues/22.
