### ISSUE TITLE
Feature request: soft tab

### ISSUE THREAD

**Issue by hmollercl** [tsujan/FeatherPad#233]
It would be good to have the option to use soft tab (spaces instead of tabs) for indenting. it's faster than pressing the space key several times, and there are some conventions which require spaces instead of tabs.

**Comment by tsujan** [comment]
It's already implemented. Use `Ctrl+TAB` instead of `TAB`; see Help → "Extra (Hidden) Shortcuts:"

**Comment by hmollercl** [comment]
Nice!! And thanks for quick response.
Anyway, maybe a checkbox for using it as default tab (w/o ctrl) could be useful. That's the way I've seen implemented in other text editor.

**Comment by jk-85** [comment]
> Nice!! And thanks for quick response. Anyway, maybe a checkbox for using it as default tab (w/o ctrl) could be useful. That's the way I've seen implemented in other text editor.

Seems it's still not implemented? It's really annoying to use CTRL+TAB every time. I come from notepad++ on windows.

**Comment by tsujan** [comment]
> Seems it's still not implemented?

It will never.

> It's really annoying to use CTRL+TAB every time.

As I'm tired of reading such comments. Use an editor that doesn't annoy you.
