### ISSUE TITLE
Some observations

### ISSUE THREAD

**Issue by AcarBurak** [tsujan/FeatherPad#234]
Hi tsujan,

I like featherpad and would like to use it (for almost every kind of writing, except for coding as I'm not a coder), but whenever I try it, while appreciating the improvements, I'm forced to go back to qtcreator with frustration. Surely, not a great loss for FP, but some points below may be relevent for other users as well. 

1. The one, big show stopper is the find/search/replace implementation. If you excuse my frankness, it's not only considerably un-intuitive, it's dangerous as well, especially in the first shocking encounter!

There're two Find boxes. Confusing clutter. And surprising too, considering this clunkiness against your care for esthetics as the developer of kvantum.

It's getting much worse. In the find & replace operation, there's a curious, single icon next to the Find box, implying Previous. Yet it doesn't move us to a previous occurence of the search term, but it replaces it with the replace term.

Even one forces him/herself to get used to this procedure, it's still not really functional.

Suppose, I want to replace some (or all) occurences of qtcreator with featherpad in a document, but I want to do it step by step, as I may not want to replace some/all occurences.

I enter qtcreator into the Find box and featherpad into the Replace box. But that would not do, I need to enter qtcreator into the other find box as well.

All right, now I've located the qtcreator occurences and, say, being in middle of the document I see a qtcreator occurence selected differently implying that it's current. YET, if I click Replace, that current qtcreator occurence is not replaced with featherpad, but another one, non-current one above or below is replaced. In order to replace the current one, first I need to click the other find prev or next and then accordingly click Replace prev or next!

That's not all either: then I want to see/replace the next occurence, but it's not visible in the page, so I can't blindly click Replace next; first I need to scroll down to see the next occurence. OK, now I see it, but, wait, since it's not painted as current, I can't be sure if it's going to be replaced or not when I click Replace… What would I click, the next icon or the prev icon… I'm trapped and sweating like hell!

Why not simply just make all of it something like

    Search [or Find]:.............. Prev    Next
    Replace:        :.............. Replace Replace & Find Replace All
    
2. I have multiple projects: ProjectA (Notes), ProjectB (Writings), ProjectC (Configs)… And, naturally, when I open a project's files I want to see only those files belonging to that project and I want to retain working at the point (the cursor position) I've left. In FPad this is possible either with sessions or the recently implemented feature, opening the last window files with the cursor positions retained.

I can't use sessions, because

a) To see only those files beloging to that project (session), everytime I need to close all the files before quiting FPad or openinig a session,
b) Opening a session itself requires too many clicks,
c) Adding a new file to an existent session riquires too many clicks.

So I like the other option, without messing around with the sessions, just launching FPad with the last window files retained. But this makes FPad a single project/session programme, unless you implement an option to launch FPad with different config files. This in itself would make a perfect sessions implementation.

3. Not a show stopper, but discouraging and annoying: FPad tells something, but does the opposite and forces its ways on me instead of doing what I choose: It doesn't reliably behave as a single instance programme. I open some documents, that is, I want to send them to the alread running (but minimized) FPad instance for later editing, but FPad launches another instance with the new document.

4. No whining this time. An option to find in open files would be a fine convenience.

5. As above, a custom shortcut key to enter file name into the filter bar in the side pane and create it if it doesn't already exist would be fine too.

6. All right, this is minor whining. Why does FPad open an already open file and turning red whine about it being alread open?

**Comment by tsujan** [comment]
I read you comment completely. I'm afraid your problem is that you want to use FeatherPad in the way you use Qt Creator or, perhaps, other text editors you're familiar with -- instead of finding and using FeatherPad's features.

None of your points was valid to me; in each case I knew a FeatherPad way, at least (which made me smile) -- and you'd find them if you wanted to. Sorry that I won't explain them. My reason is twofold: I've explained some of them in other places; and it would be futile to spend time for that when...

As I've said several times here and there:

(1) I *use* FeatherPad; and
(2) If I was satisfied with the current Qt or GTK+ text/code editors, I'd never make it.
(3) I'll never integrate replacement with search; that's a bad design mimicked by many developers without questioning. I dislike it.

All in all, it seems FeatherPad isn't yours; nothing can be done on my part.

**Comment by AcarBurak** [comment]
Sorry for hurting your feelings, but at least you get one thing correctly:
> it seems FeatherPad isn't yours

**Comment by tsujan** [comment]
It wasn't about my "feelings" -- let alone hurting them -- but about a self-contradictory attitude of yours: you don't want to use FeatherPad (if you did, you'd see many obvious things) but, at the same time, you wanted me to make you want it. Not appropriate for an issue tracker; hence closing.
