### ISSUE TITLE
When run with lxqt-sudo fp.conf gets own by root

### ISSUE THREAD

**Issue by hmollercl** [tsujan/FeatherPad#236]
Not sure if it's lxqt-sudo, featherpad or from other issue, but every time I run featherpad with lxqt-sudo the config file fp.conf gets owned by root. After that no changes are persistent when used non-sudo user until you chown fp.conf

**Comment by tsujan** [comment]
An old bug in `lxqt-sudo`, which was fixed a long time. You have an old version of `lxqt-sudo`; don't you? Please upgrade to its latest release!
