### ISSUE TITLE
search bar behavior

### ISSUE THREAD

**Issue by excalibur1234** [tsujan/FeatherPad#24]
i use the search bar in firefox like this:
- press CTRL+F and type "search word"
- read text / click on text and mark it
- press CTRL+F and type "anther search word"
the search bar never closes when i press CTRL+F

here is how feather pad works:
- press CTRL+F and type "search word"
- read text / click on text and mark it
- press CTRL+F and the search bar closes  (this is DIFFERENT compared to web browsers! )
- press CTRL+F again and type "anther search word"

as you can see, the behavior of the search bar is noticeably different to web browsers (i use firefox). IMHO, this is very confusing, because everybody is used to the search bar behavior of web browsers.

i see 2 solutions to the problem (please ask, if you do not understand exactly what i mean):
1. focus the search word in the search bar EVERY TIME when pressing CTRL+F. only close the search bar when CTRL+F is pressed AND the search word is in focus.
2. add a "close" button to the search bar and make it impossible to close the search bar by pressing CTRL+F. this would make the search bar behavior exactly the same as in web browsers.

please test the search bar behavior and compare it to the search bar in web browsers. what do you think about it?

p.s.: great job on the new tab-based preferences! i like them.

**Comment by tsujan** [comment]
OK. If `Ctrl+F` is supposed to work as in Firefox, it should never hide the searchbar. On the other hand, I don't like yet another button on the searchbar... I'll think about it.

**Comment by tsujan** [comment]
Actually, this can be seen as a bug. Thanks for reporting!

**Comment by excalibur1234** [comment]
i would like to see the first solution i proposed. but i do not know, whether this is possible.

how featherpad behaves now: 
- press CTRL+F and type "search word"
- read text / click on text
- press CTRL+F and the search bar closes.
- press CTRL+F again and type "anther search word"

how i expect featherpad to behave:
- press CTRL+F and type "search word"
- read text / click on text
- press CTRL+F and the search term in the search bar gets highlighted. i can start to type "anther search word" and search. when i press CTRL+F instead of searching, the search bar closes.

take your time and think about it. i actually do not care what solution you find as long as the search behavior is somewhat similar to web browsers. currently, it is different and this is annoying.

**Comment by tsujan** [comment]
It seems that your suggestion (1) is the best approach, namely `Ctrl+F` focuses (or shows) the searchbar when it doesn't have focus (or is hidden) and closes it when it does. In this way, neither an extra button nor another shortcut will be needed.

I'm working on saving/restoring sessions now and will also include the new behavior of `Ctrl+F` in the next commit.

**Comment by tsujan** [comment]
Done. Please test the latest version!

**Comment by excalibur1234** [comment]
it almost works as in the browser now.
much better! 
there is still a  little difference, though.

current featherpad search bar behavior:
- press CTRL+F and type "search word"
- read text / click on text
- press CTRL+F again and type "another search word".
- document is searched for "search wordanother search word".

web browser search bar behavior:
- press CTRL+F and type "search word"
- read text / click on text
- press CTRL+F again and type "another search word".
- document is searched for "another search word".

please take another look at it. personally, i like the search bar behavior of web browsers better. but if you like the featherpad's current behavior better, then keep it the way it is.

**Comment by tsujan** [comment]
You mean *selecting* the search entry with `Ctrl+F`. If so, I did it a few minutes ago. Please see if the browser search style is now implemented.

Frankly, that came to my mind when implementing the new behavior but, first, I didn't like it and second, there is a `Ctrl+K` for emptying the search entry. However, if the browser style is more familiar to many, why not.

**Comment by excalibur1234** [comment]
works like a charm. thanks!

but i like the current behavior really much:
- press CTRL+F and type "search word"
- read text / click on text
- press CTRL+F again and type "another search word".
- document is searched for "another search word".

but this also works at the moment (IMHO an important use case):
- press CTRL+F and type "search word"
- read text / click on text
- press CTRL+F again and hit ENTER key to continue the search for "search word"

when the search bar is in focus, it can be closed by pressing CTRL+F.
in my opinion, the search bar behavior is now perfect. i consider this issue fixed and closed.

**Comment by tsujan** [comment]
Thanks for your suggestions and tests! So, I close this.
