### ISSUE TITLE
Builds from latest git pull fail on Debian Stretch's gcc-6.3 and Qt 5.7.1

### ISSUE THREAD

**Issue by stevenpusser** [tsujan/FeatherPad#241]
This seems to be the error:
```

highlighter.cpp:2443:40: error: conversion from 'const char [2]' to 'QChar' is ambiguous
                 if (text.at (index) == "\"")
                                        ^~~~
```
I'm building packages in a vanilla Stretch environment using pbuilder.  Building on bare metal or with sbuild also fails with the same error.  A test build in a Debian testing pbuilder using gcc-8 and Qt 5.11 succeeds.
I've attached the build log; the error is at line 1415.

[featherpad_0.9.2+git20190130-0.1~mx17+1_amd64.build.txt](https://github.com/tsujan/FeatherPad/files/2814890/featherpad_0.9.2%2Bgit20190130-0.1.mx17%2B1_amd64.build.txt)

**Comment by tsujan** [comment]
Please replace `"\""` with `'\"'` *only there* and retry! If you could compile the latest git FeatherPad on Debian Stable after that, I'll change it in the source too. However, I think there are codes in the latest FeatherPad that require Qt > 5.8. Waiting for your test...

**Comment by agaida** [comment]
and btw - we are in transition freeze right now, next step will be on Feb. 12. - so the lifetime of stretch is limited.

**Comment by tsujan** [comment]
@agaida It's safe to make that change in the code and I'll do it tomorrow, although I'll be surprised if it makes a difference for Debian Stretch.

**Comment by agaida** [comment]
please don't forget - the freeze for Stretch starts in 2015 iirc

**Comment by tsujan** [comment]
If you said that to me, my knowledge about these things is null -- it was so too when I used my dear Debian Testing; just experienced the freezes.

**Comment by stevenpusser** [comment]
I made a patch to change line 2443 as advised, and the packages now build successfully and run on a Stretch base!  I'll send them up to the MX 17 test repo so the users can see if they fixed the <Ctrl><F> problem in German, etc. I'm not too concerned about the problem with the ancient MS Arial ttf...

Though Debian testing is frozen, it probably won't be released until at least September, too.

**Comment by stevenpusser** [comment]
Hey, I see the new warning bar when it's started as root or with sudo, but don't when it's started with pkexec, as with KDE Root Actions.  Since Buster is dropping gksu in favor of going with pkexec, or so I've heard, is that going to affect it there?

**Comment by tsujan** [comment]
> and the packages now build successfully

That was surprisingly good news.

> I'll send them up to the MX 17 test repo so the users can see if they fixed the problem in German, ..

If not, please tell me, although I'm sure the problem is not in FeatherPad's code.

> Hey, I see the new warning bar when it's started as root or with sudo, but don't when it's started with pkexec

Correct. They're different. I'll think about pkexec later.

> Since Buster is dropping gksu in favor of

`lxqt-sudo` is and will be alive. It needs a few LXQt dependencies.

**Comment by tsujan** [comment]
Made the change to the source: https://github.com/tsujan/FeatherPad/commit/45e5f77c52f84c58d73297413b6763d61628191e

**Comment by stevenpusser** [comment]
The problem with the Arial font and the Greek letters that showed up for
the font style was fixed by a upgraded backport of fontconfig from Debian
testing. However, starting Featherpad with

env LANG=de_DE.UTF-8 featherpad

Still results in the keybindings as blank except for F1 for help.

I tried a few other languages, such as Spanish, but those were OK.

**Comment by tsujan** [comment]
> However, starting Featherpad with...

Use:
```
LANGUAGE=de featherpad`
```
