### ISSUE TITLE
Tag a new release

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#243]
We should have a new release in the next two days if we want the latest and greatest in the upcoming debian stable.

**Comment by tsujan** [comment]
Will do it for FeatherPad and Kvantum. Ah, making release notes is so boring.....

**Comment by tsujan** [comment]
Done :) I always have a ready, detailed changelog.

**Comment by tsujan** [comment]
Oh, FeatherNotes also needs a release; several problems are found and fixed in it.

**Comment by agaida** [comment]
fine, thanks

**Comment by agaida** [comment]
@tsujan, please go ahed, we run out of time if it should hit stable

**Comment by tsujan** [comment]
@agaida, I did it for FeatherPad and Kvantum ~17 hours ago.

Now, I'm working on FeatherNotes; it shouldn't take long -- an hour, at most.

**Comment by agaida** [comment]
fine, just uploaded featherpad :p

**Comment by agaida** [comment]
``` 
2019-02-06  00:35:42 <BTS> featherpad 0.9.3-1 uploaded by Alf Gaida <agaida@siducti...> https://tracker.debian.org/featherpad
```
