### ISSUE TITLE
Enhancement - possible to have some sort of spell-checking in featherpad 

### ISSUE THREAD

**Issue by shirishag75** [tsujan/FeatherPad#244]
Would it possible to have it either use gtkspell or some other spell-checking library for featherpad ?

**Comment by tsujan** [comment]
Possible? Yes (of course, not with gtkspell). Probable? No! I don't want more dependencies for FeatherPad and won't clutter it with such functionalities.

Anyhow, thanks for the suggestion!

**Comment by tsujan** [comment]
Hunspell based spell checking was added to the git version about 2 months ago -- I forgot that the feature was mentioned here.

As for new dependencies, there's only one and it's Hunspell (`libhunspell-dev` in Debian or `hunspell` in Arch). It was worth adding.
