### ISSUE TITLE
Shift-Insert should not turn on overwrite mode

### ISSUE THREAD

**Issue by chang-zhao** [tsujan/FeatherPad#247]
Hi @tsujan, thank you for useful software!

I often use Shift-Insert to paste, when it's easier to press than Ctrl-V.
But in FeatherPad Shift-Insert turns ON the overwrite mode, which is quite uncomfortable for me.
Please could you make the switch to overwrite ONLY when Insert alone is pressed, without any other keys?
Otherwise, I would just disable overwriting (very rarely use it anyway). :)
Thank you in advance!
Amituofo.

**Comment by tsujan** [comment]
Oh, you're tight, it's a bug. I'll fix it soon, with the next commit (which will be about something else).

Thanks for your report!

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/49180c21fce3484f8a863f7e17bbdc076ee000fb . Please upgrade!

Although I use `Shift+Insert` in line-edits, I only use `Ctrl+V` in text-edits. So, if you didn't report this problem, I wouldn't find it soon. Thanks again!
