### ISSUE TITLE
missing link?

### ISSUE THREAD

**Issue by stefonarch** [tsujan/FeatherPad#249]
> If you would like to contribute to translation of FeatherPad, you need to register on this server.

I had to google it and found it [here](https://weblate.lxqt.org/projects/tsujan/featherpad/)

**Comment by tsujan** [comment]
It's the "engage" page; It's for registering or logging in. Then, all translations will be visible and a new translation could be added. I think it's the best address.

**Comment by stefonarch** [comment]
There is no link at all afaik, it talkes only about "this server". Or I am blind ;)

**Comment by tsujan** [comment]
OK, I'll change them, here and in other projects, and see how it'll look like on GitHub.

**Comment by tsujan** [comment]
Done and it's OK. Thanks!

**Comment by stefonarch** [comment]
Uhm, for me it isn't just clear that the screenshot is the link - I'd transform the text "this server" in link.

**Comment by tsujan** [comment]
> for me it isn't just clear that the screenshot is the link

"... on this server." can be changed to "... on the following server:"
