### ISSUE TITLE
make sure \n is last symbol

### ISSUE THREAD

**Issue by excalibur1234** [tsujan/FeatherPad#25]
when you create a text file without an extra line in the end, featherpad does not add an extra \n symbol at the end.
this means that some text editors can not open this file or mark it as corrupt (e.g. the github online editor).

i have never heard of that before, but apparently it is a thing.
currently, i cannot test this.

**Comment by tsujan** [comment]
OK. I'll try to find a way of adding `\n` on saving if it doesn't exist. It should be easy to implement.

**Comment by tsujan** [comment]
Added an option that, by default, appends an empty line on saving when the last line isn't empty.

Actually, a text editor that can't open a document without `\n` at the end has a bug and the above-mentioned option can be seen as a workaround for such cases. However, I always liked the last line to be empty automatically. Thanks for reminding me of that!

**Comment by excalibur1234** [comment]
it is turned on by default.
thanks!
