### ISSUE TITLE
where does featherpad save it settings ?

### ISSUE THREAD

**Issue by shirishag75** [tsujan/FeatherPad#258]
Where are the settings or preferences set ? I looked in both ~/.local as well as ~/.config but didn't find the answer in either place :(

**Comment by tsujan** [comment]
By default, most apps -- Qt or GTK+ -- write their user settings inside `~/.config`. If you can't find the directory`~/.config/featherpad`, you might have created a file with the same name or....

**Comment by agaida** [comment]
or sudo featherpad - in that case one could find the config in /root/.c*/featherpad

**Comment by tsujan** [comment]
Maybe, @shirishag75 has started to use FeatherPad but hasn't closed all of its windows yet -- that's the moment FeatherPad writes its user config (like pcmanfm-qt).

**Comment by shirishag75** [comment]
no, what is/was happening is that CTRL+T which I believe is for detach tab, detaches and expands the workarea of the editor so that the minimize, maximize and close window doesn't appear at all. I was looking that maybe it should be something like .config/qt/featherpad. It took me sometime to figure out 
that in Options > Preferences > uncheck remember window size while closing. Although featherpad detaching a tab even when it's a single one seems like a bug but that's a different thing altogether. Thanks to you was able to find where the configuration file stands. I will try to see if I can figure out what most of the .config variables are. Thank you all the same.

**Comment by tsujan** [comment]
> ...so that the minimize, maximize and close window doesn't appear at all.

That's a bug in the window manager you use.

> Although featherpad detaching a tab even when it's a single one

That never happens.
