### ISSUE TITLE
Find & Replace?

### ISSUE THREAD

**Issue by githububub** [tsujan/FeatherPad#27]
Commit ff5a07ce384506f6f1325833c380d4262dc8ffeb. How do we find and replace? The enter/submit option appears to be missing.

![2017-04-24-085648_1920x1200_scrot](https://cloud.githubusercontent.com/assets/20338556/25329640/2eb19e94-28cc-11e7-9981-53ccaedda70a.png)

**Comment by tsujan** [comment]
Either your icon theme doesn't have those three icons to the right of the Replace dock or you haven't installed `libqt5svg5`. First ensure that `libqt5svg5` is installed and, if it's installed, check Preferences → Window → Use own icons (which needs application restart for those three icon to the left of the replace dock to appear.

Submitting with ENTER is not for the Replace dock (intentionally).

**Comment by tsujan** [comment]
Sorry, I meant `qt5-svg` for Arch -- libqt5svg5 is for Debian.

**Comment by githububub** [comment]
I did not realize that I could hover over the icon location to reveal keyboard shortcuts.  Nice touch! No need for qt5-svg :)

![next-f7](https://cloud.githubusercontent.com/assets/20338556/25356919/962f21fe-292b-11e7-891f-aa285528ee19.png)

![all-f9](https://cloud.githubusercontent.com/assets/20338556/25356926/9aec9622-292b-11e7-88b5-ef19e3c28c62.png)

**Comment by tsujan** [comment]
> No need for qt5-svg (intentionally set to makedepends and not depends array)

Actually, `qt5-svg` should be in `depends`, not in `makedepends` because it is NOT a build dependency but is needed for showing the built-in icons (which are chosen to be SVG because of scaling and small size). Please see INSTALL!

**Comment by githububub** [comment]
I understand. I am now running a minimal version with minimal dependencies which builds without `qt5-svg`. Below is my latest working PKGBUILD as I prefer an icon-free, text-only experience.

>pkgname=featherpad
pkgver=0.5.8+94+gff5a07c
pkgrel=1
arch=(x86_64)
url="https://github.com/tsujan/FeatherPad"
license=(GPL3)
depends=(qt5-x11extras)
makedepends=(git qt5-tools)
_commit=ff5a07ce384506f6f1325833c380d4262dc8ffeb
source=(git+https://github.com/tsujan/FeatherPad.git#commit=$_commit)
sha256sums=(SKIP)

>pkgver() {
  cd FeatherPad
  git describe --tags | sed 's/^V//; s/-/+/g'
}

>prepare() {
  sed '/RESOURCES/d; s/ svg//; s/x11extras \\/x11extras/' -i FeatherPad/featherpad/featherpad.pro
  mkdir -p build
}

>build() {
  cd build
  qmake ../FeatherPad 
  make
}

>package() {
  cd build/$pkgname
  install -D -m755 $pkgname $pkgdir/usr/bin/$pkgname
}

**Comment by tsujan** [comment]
OK, that's your choice. I removed the texts of those buttons as a workaround for a nasty KDE bug (automatic mnemonics), so that they're distinguished only by their icons.

**Comment by tsujan** [comment]
I may add an option for iconlessness later.

**Comment by githububub** [comment]
That would be great. I don't know why FeatherPad is not getting more attention. It is the absolute best combination of GUI minimalism combined with a relatively full feature set. Builds fast, starts up fast and uses minimal resources with a responsive developer. IMO, it is the top text editor available today regardless of toolkit. Awesome job!

**Comment by tsujan** [comment]
> That would be great.

It should be easy to implement.

> I don't know why FeatherPad is not getting more attention...

Thank you! FeatherPad is relatively new (released in Oct 14, 2016) but people are starting to know about it. The last time I checked it was on the top of [Manjaro's list of Qt text editors](https://wiki.manjaro.org/index.php?title=List_of_Qt_Applications#Text_Editors).

**Comment by tsujan** [comment]
Added an iconless mode. With the latest version, if you enable the iconless mode in `Preferences` → `Window`, all search and replace buttons will have text.

**Comment by githububub** [comment]
Outstanding! 

![featherpad](https://cloud.githubusercontent.com/assets/20338556/25422362/3279c0c6-2a50-11e7-974d-c36d4909aa8e.png)

**Comment by tsujan** [comment]
Thanks for the screenshot! I wasn't sure that it would work without `qt5-svg` too; now I am :)
