### ISSUE TITLE
Build of the latest git (0.11.0) fails on Debian Stretch

### ISSUE THREAD

**Issue by stevenpusser** [tsujan/FeatherPad#274]
Seems to be pretty much the same issue as https://github.com/tsujan/FeatherPad/issues/241.
I made a patch, and the builds succeed with it and a backported libhunspell-dev 1.6.2. Apparently, Stretch's hunspell is too old.

[gcc-6_fix.patch.zip](https://github.com/tsujan/FeatherPad/files/3200166/gcc-6_fix.patch.zip)

**Comment by agaida** [comment]
To be honest: Who cares. Stretch will become soon oldstable, it is just dead. There will be no backports.

**Comment by tsujan** [comment]
@stevenpusser Thanks for your attention to this new feature! I made Hunspell 1.6 as the minimum version in `CMakeLists.txt` because Hunspell had deprecated its old functions and I didn't know whether the new ones existed in older versions. (I should do the same for `featherpad.pro`.)

However, as @agaida correctly said, the new Debian stable will have all the necessary packages and I don't think I could support oldstable in future.

As far as I've tested it — actually, I've been addicted to it ;) — it works fine but users will tell me about what I may have overlooked.

**Comment by tsujan** [comment]
Oh, and I'll apply a part of your patch about `at (0) == '\''` soon (it's a better than `at (0) == "\'"`).

**Comment by stevenpusser** [comment]
"To be honest: Who cares. Stretch will become oldstable soon, it is just dead. There will be no backports."

MX Linux gets the most click-throughs currently at Distrowatch currently, and is based on Stretch. We do loads of backports in order to keep it as current as possible until the next Buster-based release.

I built and installed the new version. I can't see any automatic underlining of unknown words, but I can check the spelling with the F2 key. Is that how it's supposed to work?

Debian's Thunderbird, which also uses hunspell, has these packages as Recommends to provide the dictionaries:   myspell-en-us | hunspell-dictionary | myspell-dictionary  They are virtual packages that an appropriate dictionary package provides, so doing the same for Featherpad seems the way to go.

**Comment by tsujan** [comment]
> ... but I can check the spelling with the F2 key. Is that how it's supposed to work?

Yes. Underlining could interfere with syntax highlighting. Moreover, it would require right clicking and the proposed list might be too long, etc.

I'm adding shortcuts (and tooltips) to the dialog buttons (F3 to F7) and arranging the Tab focus. Will make a commit soon.

**Comment by tsujan** [comment]
> Debian's Thunderbird, which also uses hunspell, has these packages as Recommends...

That shouldn't and can't be done in the source but when a deb/rpm/AUR... package is built.

**Comment by stevenpusser** [comment]
Yes, I built deb packages for MX users to experiment with, so it was a concern for me.
Do you recommend we switch to the cmake build now from the qmake one?

**Comment by tsujan** [comment]
> Yes, I built deb packages for MX users to experiment with

Nice!

> Do you recommend we switch to the cmake build now from the qmake one?

cmake has more details and is more precise than qmake — although making cmake files is harder sometimes (it gave me a headache with Hunspell). When you compile something with cmake, the terminal output is more useful compared to qmake. Also, they say that qmake will be abandoned with Qt6 (I don't remember where I read it). So, I decided to add cmake files to my other projects too but will keep qmake as long as it works.
