### ISSUE TITLE
Intent to package: Snaps are universal Linux packages

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [tsujan/FeatherPad#277]
Dear maintainer(s), 

[Snaps are universal Linux packages](https://snapcraft.io) that can be installed and run on many GNU+Linux distributions with ease.  I've been following the [Snapcrafters](https://forum.snapcraft.io/t/join-snapcrafters/1325) instructions and [have built a working snap on the Snap Store](https://snapcraft.io/featherpad), you may try it out by running the following commands after [installing snapd](https://docs.snapcraft.io/installing-snapd/6735):
 
    # snap install --channel=edge featherpad

I'm also looking forward to working with you to make the packaging work upstream (if you're interested).  You may want to check out the current [packaging recipe](https://github.com/Lin-Buo-Ren/featherpad-snap/blob/master/snap/snapcraft.yaml), the [documentation](https://docs.snapcraft.io), registering a developer account on the [Snap Store](https://snapcraft.io/store), and [get in touch with us](https://forum.snapcraft.io) to transfer the work under your control.

Thanks for your time and attention.

**Comment by tsujan** [comment]
Thanks but FeatherPad is already packaged for most distros and I'm not interested in snaps.

**Comment by Lin-Buo-Ren** [comment]
Acknowledged.  Do let me know if there's anything bothers you with the snap distribution.

**Comment by tsujan** [comment]
Nothing bothers me :) Here, there is simply no problem to be solved by snaps.
