### ISSUE TITLE
Wrong encoding detection

### ISSUE THREAD

**Issue by fulalas** [tsujan/FeatherPad#28]
This txt file should be read as western european, but it's not, so accents are broken: http://www.mediafire.com/file/xct9szlkgh8w8h9/enconding-issue.txt

Other editors, like Leafpad, auto detects the correct encoding.

**Comment by tsujan** [comment]
First, thanks for your report!

Encoding detection can never be an exact algorithm; it's partly based on trial-and-error. The encoding menu is added because of that; you could change the encoding by using it and afterward, save the doc, which will automatically result in a utf-8 text (the standard, nowadays).

The encoding code of FeatherPad was taken from Leafpad (which was taken from the old Kate, in its turn) and then improved in some cases. I'll see why, in this special case, they are different but can't guarantee that they will be always identical.

**Comment by fulalas** [comment]
Yeah, I'm aware of this issue with encoding detection -- I made a subtitle autofix using Qt :P

But this issue with Feather happens with lots of text files. I've just provided an example.

Thanks!

**Comment by tsujan** [comment]
> But this issue with Feather happens with lots of text files

Are they all about ISO-8859-15?

**Comment by fulalas** [comment]
Yep! :)

**Comment by tsujan** [comment]
That's good news. I remember that I made changes for better detection of some other encodings. Maybe that's the reason. The fix shouldn't be difficult.

**Comment by tsujan** [comment]
I made a change. Please try the latest git version and let me know the result!

Apparently, the problem was about the subtle distinction between `Cryllic-1251` and `ISO-8859-15`; I'd forgotten about the latter.

**Comment by fulalas** [comment]
It's working now. Thanks! :)

**Comment by fulalas** [comment]
Here's the sample: http://www.mediafire.com/file/h2n323dsusa5vrr/encoding-issues01.txt

The same issue: Cryllic-1251 detected instead of ISO-8859-15 -- Leafpad correctly detects it.

**Comment by tsujan** [comment]
Please test again! Thanks for the sample!

> Leafpad correctly detects it.

As I said before, distinguishing between Cryllic-1251 and ISO-8859-15 is difficult in some cases. Leafpad sees many Cryllic-1251 docs as ISO-8859-15.

If you encounter another ISO-8859-15 doc that's detected wrongly (which is quite possible), please give me more samples!

**Comment by fulalas** [comment]
Yeah! Now I think it's perfect. Thank you very much, man! :)

**Comment by tsujan** [comment]
You're welcome.

Your report made me to rethink some parts of encoding detection. It's far from complete but acceptable for a world with utf-8. Now I'm looking into Kate's code to know how it does it so well.

**Comment by tsujan** [comment]
I think this can be closed now.
