### ISSUE TITLE
Question sign in a description

### ISSUE THREAD

**Issue by MaxiDvy** [tsujan/FeatherPad#282]
https://github.com/tsujan/FeatherPad/blob/3e03d50de39eb835296d99bbf75d17e6f0e9ba68/featherpad/predDialog.ui#L866

@tsujan Is it correct to use a question mark at the end of that description?
When I did the translation into spanish I took it out because it was not necessary, maybe I do not understand it because of some limitation in my english level, but I wanted to inform you to be sure.

**Comment by tsujan** [comment]
Yes, the question mark is needed in English. It asks, "Should X be like Y when Z happens?" That will be the case when the box is checked.

However, the same concept can be expressed in various ways. As far as your translation conveys the same meaning to the native speaker, it's good. Different languages have different structures.

Thanks a lot for paying attention to details!
