### ISSUE TITLE
Drag and drop to another window/app cuts text

### ISSUE THREAD

**Issue by Vladimir-csp** [tsujan/FeatherPad#283]
When dragging selected text from Featherpad to another window, it gets cut. It probably should be cut only when dragging to another place in the same opened file.

**Comment by tsujan** [comment]
Good point.

That's how Qt does the job and I'm not sure how much work will be needed for changing it.

**Comment by tsujan** [comment]
Oh, I forgot that `Ctrl+Dragging` keeps the original text, whether dragging is done to another place or to the same view.

Technical problems aside, changing this behavior may not be desirable; many Qt users may have got used to it and their workflows might be broken if it's changed.
