### ISSUE TITLE
Better font dialog that distinguishes monospace

### ISSUE THREAD

**Issue by tsujan** [tsujan/FeatherPad#288]
The default Qt font dialog doesn't and has other problems too. Monospace is important when the text editor is used for coding.

**Comment by shlyakpavel** [comment]
You could support (as a build option) the dialog used in KDE. https://api.kde.org/frameworks/kwidgetsaddons/html/classKFontChooser.html

**Comment by shlyakpavel** [comment]
https://doc.qt.io/qt-5/qfontdialog.html#FontDialogOption-enum
I hope this can be also helpful

**Comment by tsujan** [comment]
> u could support (as a build option) the dialog used in KDE. 

I don't want KDE dependency for any of my Qt apps.

> https://doc.qt.io/qt-5/qfontdialog.html#FontDialogOption-enum

Thanks! I knew about it but, for whatever reason, it didn't work as expected.

This will be for V0.12.0. I might add some things to Qt font dialog or make a new font dialog. I still have no idea how easy/hard that will be but, so far, Qt hasn't let me down; for almost every Qt bug/flaw, there has been a good workaround :)

**Comment by tsujan** [comment]
I came up with this:

![fontDialog](https://user-images.githubusercontent.com/981076/62308127-1f069880-b49a-11e9-940e-c7ea4c11db55.png)

If "Suitable for codes" is checked (it is, by default), only monospace fonts are shown and they cannot be made bold or italic; otherwise, all fonts will be shown.

If it works as expected, I'll include it in V0.11.0.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/43a27cc1a939884a06c53189e864ba826e518df6
