### ISSUE TITLE
Fails to build on Debian GNU/Hurd

### ISSUE THREAD

**Issue by paulusasol** [tsujan/FeatherPad#290]
FeatherPad (commit 3e4a9a5a1c1b274c801ed6501c167d7956816eaa) fails to build on Debian GNU/Hurd.

The reason is line 23 in the file [`featherpad/x11.h`](https://github.com/tsujan/FeatherPad/blob/3e4a9a5a1c1b274c801ed6501c167d7956816eaa/featherpad/x11.h) which results in the header `X11/Xlib.h` only being included on some operating systems.

The simplest way to fix it is similiar to 0771908eed5f3a7e4e85d1aabbce61e6c109d6dc: Just append ` || defined Q_OS_HURD`.
I have tested the approach and FeatherPad compiled wtih this option seems to be usable on Debian GNU/Hurd, though I have not fully tested it.

Another way should be to replace the line with `#if defined HAS_X11` which is defined by the [`CMakeLists.txt`](https://github.com/tsujan/FeatherPad/blob/3e4a9a5a1c1b274c801ed6501c167d7956816eaa/featherpad/CMakeLists.txt), line 45.

Excerpt of the build log:

    [...]
    [  3%] Building CXX object featherpad/CMakeFiles/featherpad.dir/main.cpp.o
    In file included from /home/demo/featherpad/FeatherPad/featherpad/main.cpp:23:
    /home/demo/featherpad/FeatherPad/featherpad/x11.h:30:22: error: ‘Window’ was not declared in this scope
     long onWhichDesktop (Window window);
    [...]

**Comment by tsujan** [comment]
> The simplest way to fix it is similiar to 0771908: Just append || defined Q_OS_HURD.

Thanks for the info! I have no knowledge of Hurd but if supporting it requires `Q_OS_HURD`, it should be added to some other places too. I'll add it soon.

**Comment by agaida** [comment]
https://qa.debian.org/developer.php?login=pkg-lxqt-devel@lists.alioth.debian.org

Seems that Featherpad, Feathernotes, liblxqt and kvantum have the same problem. I suggest that the Hurd porters will fix and send patches upstream, will pick them up.

**Comment by tsujan** [comment]
I'll try to add support for Featherpad, Feathernotes and Kvantum but prefer no to touch liblxqt.

**Comment by agaida** [comment]
Good idea - and i'm not unkind, that's a Hurd porters thing. And i'm a lazy guy so i prefer to merge the needed things upstream :D - Ha, Linux was yesterday, next year will be the year of the Hurd desktop.

**Comment by tsujan** [comment]
Closed in https://github.com/tsujan/FeatherPad/pull/291

**Comment by agaida** [comment]
@paulusasol - with such porting things - feel free to open the bugs directly in Debian BTS - bonus points for writing Merge Requests in salsa. In between two chairs - if the fix is done upstream, i had to get it downstream and vice versa - but i bet it would be less work for you - and we should be known for merging Hurd patches fast :D (both upstream and Debian LXQt team)

**Comment by agaida** [comment]
2019-07-19  22:45:55 <BTS> featherpad 0.10.0-3 uploaded by Alf Gaida <agaida@siducti...> https://tracker.debian.org/featherpad

**Comment by tsujan** [comment]
Thanks! The more Hurd users, the sooner I'll know if there's a problem to fix with Hurd.

**Comment by agaida** [comment]
i don't want to depress you - but if we want more hurd users we should fix liblxqt asap - there are not so much DE's that build and run on Hurd - ok, i know nobody running the Hurd - also nobody who run this with a DE :) - but it is better to be prepared :smile:

**Comment by tsujan** [comment]
> i don't want to depress you

You don't :) If a program has potential to support more OS's, let's make it support them! When I started to write FeatherPad, I thought only about Linux. Now it supports *BSD, Haiku, manOS and Hurd, although maybe not completely (yet). That's the power of Qt.

**Comment by agaida** [comment]
meh - they should start their builder - anyways, can't test it :D
