### ISSUE TITLE
Can't build on Mac

### ISSUE THREAD

**Issue by shlyakpavel** [tsujan/FeatherPad#295]
Hello. Something has broken Mac OS support. 
What I get is
```use of undeclared identifier 'isWindowShaded' ```
And
```use of undeclared identifier 'unshadeWindow' ```
Everywhere in the code.
Apple clang version 11.0.0, Qt 5.13, Mac OS Mojave 10.14.6
Trying to build with qmake

**Comment by shlyakpavel** [comment]
So what's happening. https://github.com/tsujan/FeatherPad/blob/21e139d28d6df57e3401747d22eb2bd57020a46e/featherpad/fpwin.cpp#L50 
"x11.h" is not included
This function is never included https://github.com/tsujan/FeatherPad/blob/21e139d28d6df57e3401747d22eb2bd57020a46e/featherpad/x11.cpp#L143
However, it is referenced here(for example) without any preprocessor checks
https://github.com/tsujan/FeatherPad/blob/21e139d28d6df57e3401747d22eb2bd57020a46e/featherpad/fpwin.cpp#L2074

**Comment by shlyakpavel** [comment]
P.S. Other platforms (like Haiku) must be also affected

**Comment by tsujan** [comment]
Thanks a lot! I'll look into it. It seems that compiling without X11 is broken everywhere.

**Comment by shlyakpavel** [comment]
https://github.com/tsujan/FeatherPad/commit/a177c6b4a3020a7fb0221f96fc31e7ab2bfa4ff6
This seems to be the troublemaker

**Comment by tsujan** [comment]
> This seems to be the troublemaker

Yes. I should have tested it without X11 too.

**Comment by tsujan** [comment]
Fixed in https://github.com/tsujan/FeatherPad/commit/61987d96434965f4617bf99d1625e854f6b99c37

Please test the latest git. And thanks again!

**Comment by shlyakpavel** [comment]
@tsujan tested. It was pain in ass to build it with hunspell on Mac (I couldn't configure make to do that, cmake works fine)
<img width="812" alt="image" src="https://user-images.githubusercontent.com/19782228/63154184-ba5e4880-c018-11e9-9763-299c4d766418.png">

**Comment by tsujan** [comment]
> ... cmake works fine

Good to know that. CMAKE seems to be more multi-platform. That was one of reasons why I included it.
