### ISSUE TITLE
featherpad can't find hunspell

### ISSUE THREAD

**Issue by ayhanyalcinsoy** [tsujan/FeatherPad#298]
My system is OS: Pisi Linux QT: qt5.13.0 hunspell: 1.7.0
When I building featherpad-0.11.1 at Pisi Linux, I get following error. How can I get rid of it?

`/usr/bin/ld: cannot find -lhunspell
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:301: featherpad] Error 1
make[1]: Leaving directory '/var/pisi/featherpad-0.11.1-2/work/FeatherPad-0.11.1/featherpad'
make: *** [Makefile:47: sub-featherpad-make_first] Error 2
DEBUG: return value for "make -j5" is 2
Traceback (most recent call last):
  File "/git/main/desktop/lxqt/featherpad/actions.py", line 19, in build
    qt5.make()
  File "/usr/lib/pisilinux/pisi/actionsapi/qt5.py", line 71, in make
    cmaketools.make(parameters)
  File "/usr/lib/pisilinux/pisi/actionsapi/cmaketools.py", line 77, in make
    if system(command):
  File "/usr/lib/pisilinux/pisi/actionsapi/shelltools.py", line 255, in system
    error(_("Command \"%s\" failed, return value was %d.") % (command, retValue))
  File "/usr/lib/pisilinux/pisi/actionsapi/__init__.py", line 27, in error
    raise Error(msg)
pisi.actionsapi.Error: Command "make -j5" failed, return value was 2.
Action script error caught.
*** 1 error(s), 0 warning(s)                                                                                                          
Program terminated.                                                                                                                   
Please use 'pisi help' for general help.                                                                                              
3e6da112af65 ~ # pisi info hunspell-devel
Installed package:
Name                : hunspell-devel, version: 1.7.0, release: 6
`

**Comment by tsujan** [comment]
FeatherPad has no python source file and yet the message that you've attached tells about "/git/main/desktop/lxqt/featherpad/actions.py".

Use a clean source directory by extracting the `zip` or `tar.gz` file from https://github.com/tsujan/FeatherPad/releases/tag/V0.11.1, open a terminal inside the extracted folder and do:

```sh
mkdir build && cd build
cmake ..
make
```

Then, you could run it without installation with:

```sh
cd featherpad
./featherpad
```

Or install it with `sudo make install`.

**Comment by ayhanyalcinsoy** [comment]
I tried build it via qmake and it gave error. But cmake done. Thanks for answer.

**Comment by tsujan** [comment]
> But cmake done.

Good to know that! I don't know why qmake didn't work for you but cmake is more reliable.
