### ISSUE TITLE
Haiku/macOS: QMAKE: cannot find -lhunspell

### ISSUE THREAD

**Issue by shlyakpavel** [tsujan/FeatherPad#299]
When I'm trying to build the app with qmake I get `cannot find -lhunspell` on both Haiku and Mac.
cmake works fine on the same environments.
P. S. It works fine on Linux as far as I have tested...

**Comment by shlyakpavel** [comment]
On Mac I am able to fix this by changing `LIBS += -lhunspell` to  
```
LIBS += -L/usr/local/lib/ -lhunspell-1.7
```

**Comment by shlyakpavel** [comment]
`LIBS += -lhunspell-1.7` fixes the problem on Haiku

**Comment by tsujan** [comment]
Thanks for investigating it!

There is a problem here: we can't add a fixed version of hunspell to the pro file. Does it work without `-1.7`?

**Comment by shlyakpavel** [comment]
> There is a problem here: we can't add a fixed version of hunspell to the pro file. Does it work without `-1.7`?
> 
It does not. Only fixed version is working for some reason

**Comment by tsujan** [comment]
> Only fixed version is working for some reason

That isn't good. If we don't find another way, it'll show that qmake has serious drawbacks. I might warn users in `INSTALL`.

Anyways, we have cmake, which most maintainers prefer and many developers use.

**Comment by shlyakpavel** [comment]
Lol. I was missing pkg-config on my system

**Comment by tsujan** [comment]
> P. S. With pkg-config it's still the same

Don't bother yourself with qmake; there's no hope for it ;)

**Comment by tsujan** [comment]
I mean outside Linux. Under Linux, it has been good enough, as far as I know.

**Comment by shlyakpavel** [comment]
> I mean outside Linux. Under Linux, it has been good enough, as far as I know.

By the way, I have used it on windows and it worked always just fine. Wanna try running FeatherPad on windows one day (with wine for debugging 🤣 )

**Comment by tsujan** [comment]
> Wanna try running FeatherPad on windows one day

It should be possible with some changes. An advanced user of [Kvantum](https://github.com/tsujan/Kvantum) had succeeded in running it under Windows; so, it should be possible with FP too. Qt is so flexible.

**Comment by shlyakpavel** [comment]
> > Wanna try running FeatherPad on windows one day
>
> It should be possible with some changes.

Just tried this with MSVC2017. No chance to do it natively. There is no way to run hunspell on windows other than virtual environment (such as sygwin).

**Comment by tsujan** [comment]
Closing because this is about Hunspell and Haiku/macOS, not FeatherPad.
