### ISSUE TITLE
configurable syntax highlighting

### ISSUE THREAD

**Issue by pvanek** [tsujan/FeatherPad#30]
it would be great to use standalone config files for various prg languages instead to hardcode it into c++ code...

**Comment by tsujan** [comment]
If you mean the highlighting colors, I intentionally made them hard-coded because FeatherPad's background color value can be changed by users. I had a hard time to choose highlight colors in such a way that the text would be clearly readable with all bg color values FeatherPad accepts.

**Comment by pvanek** [comment]
no, I mean content of highlighter*.cpp files. It's full of "if lang == c" like conditions. Now it's extremely hard to add a new lang support. If these "configs" would be stored in separate files (like eg. Juffed or kwrite does it), there can be only an easy loader and all these keywords and whatever can be loaded on demand.

Examples:
https://github.com/Mezomish/juffed/tree/master/apis

**Comment by tsujan** [comment]
This is a really good idea.

The highlighter code was the most hard-to-implement part of FeatherPad and can't be seem as finished. Seeing that even an editor like Kate and gEdit had problems with some texts, I realized that there was no universal way of syntax highlighting. There were some common structures in some languages but each one had its special syntax/rules. Adding a language requires dealing with a new structure. But *keywords* are different.

Maybe the syntax highlighting code can be simplified or maybe there are better approaches. I'll look into it Thanks for the suggestion!

**Comment by tsujan** [comment]
I took a look at `JuffEd` (your link above). It uses `qscintilla` for syntax highlighting. gEdit uses `gtksourceview` and Kate user KDE libraries. That's while FeatherPad is self-sufficient in that regard :) I guess the syntax highlighter code is something that most coders don't want to deal with ;)

**Comment by tsujan** [comment]
FeatherPad's syntax highlighting will never be configurable because it's hard-coded (no external library).

**Comment by Glory7000** [comment]
...Why?

GNU nano also doesn't use any libraries for highlighting, it uses its own regex-based and extensible format, and it's pretty good at it, albeit being a terminal editor. It's what keeps me from using Featherpad to be honest.

**Comment by tsujan** [comment]
> ...Why?

Because its syntax highlighting is "a little" different from that of nano:

![nano](https://user-images.githubusercontent.com/981076/49659029-93e31900-fa58-11e8-9cca-ed8812a51edd.png)

**Comment by SjoerdV** [comment]
if you open up a PowerShell script file (ps1) then there is no highlighting whatsoever. @tsujan are you saying this can be tweaked in settings? If so, is there some guidance on this?

**Comment by tsujan** [comment]
> if you open up a PowerShell script file (ps1) then there is no highlighting whatsoever.

It seems that what you mean is not related to this page.

If you mean Microsoft's PowerShell and if uses the syntax of SH, then you could change the language to `sh` with the language button (check Preferences → Text → Support syntax override).

If it doesn't use the syntax of SH, then it isn't (and won't be) supported by FeatherPad. Its extension (`ps1`) isn't even recognized as a mime type.

BTW, why should one use Microsoft's PowerShell  on Linux?!

**Comment by tsujan** [comment]
> actually the Ruby highlighter does an OK job

Are you sure that PowerShell's syntax is that of Ruby?

Featherpad supports more than 36 syntaxes without depending on an external library. If PowerShell is really compatible with one of them, I could make Featherpad open `ps1` files with that syntax.

**Comment by tsujan** [comment]
> is that little text also something that can be changed?

No. It shows the syntax; shouldn't be changed.


With the syntax of Ruby for PowerShell, problems will appear sooner or later. Each programming language needs its own syntax highligting. If PowerShell was among commonly used languages in Linux, I might add code for highlighting its syntax.

Therefore, I don't recommend FeatherPad for working with PowerShell scripts.

**Comment by aaronpeacock** [comment]
hard-coding language syntax !? 
  I was looking for a config file or something. this is quite possibly the only text editor in the world that has hardcoded programming language syntax.  OF COURSE programming language syntax are all different! 

so, I cannot get syntax highlighting with a programming language you didn't include, for example Ruby syntax highlighting would generally work FINE for Crystal language, however, featherpad does not see this, and won't allow me to set it manually. no config. I go searching for a solution and end up here, and now I will stop using featherpad, because this is unacceptable on any level.

**Comment by tsujan** [comment]
> this is quite possibly the only text editor in the world that has hardcoded programming language syntax

It may be the only text editor in the world that doesn't depend on any library for syntax highlighting. What you call "unacceptable" out of ignorance consists of a huge amount of difficult codes that keep the app lightweight and independent, while supporting *common programming languages* — as mentioned in README.
