### ISSUE TITLE
CMAKE: fails to install on Haiku

### ISSUE THREAD

**Issue by shlyakpavel** [tsujan/FeatherPad#300]
I'm running
```mkdir build
cd build
cmake ..
make
```
The project builds successfully. But if I try `make install` I get
```-- Installing: /boot/system/featherpad_ar_DZ.qm
CMake Error at featherpad/cmake_install.cmake:39 (file):
  file INSTALL cannot copy file
  "/boot/home/FeatherPad/build/featherpad/featherpad_ar_DZ.qm" to
  "/boot/system/featherpad_ar_DZ.qm".
Call Stack (most recent call first):
  cmake_install.cmake:32 (include)


Makefile:73: recipe for target 'install' failed
make: *** [install] Error 1
```

**Comment by shlyakpavel** [comment]
I guess we should call @khallebal as neither of us here is familiar with Haiku

**Comment by tsujan** [comment]
@khallebal, could you please take a look at the Hunspell problem under Haiku? It'll be enough if it works with cmake -- qmake doesn't seem friendly toward all platforms.

**Comment by tsujan** [comment]
in `featherpad.pro`, the translations installation path for Haiku is `$$PREFIX`, which is `/boot/home/config/non-packaged/apps/FeatherPad`.

in `CMakeLists.txt`, it is `${CMAKE_INSTALL_PREFIX}`, which is `/boot/home/config/non-packaged/apps/FeatherPad` again.

So, I have no clue where the problem may be.

**Comment by khallebal** [comment]
It looks like one o the Cmakefile.txt files needs to be patched so that it refers to the right path, from the error it's trying to install to the system hierarchy which is "readonly" instead of the home hierarchy, i'll take a look later today and see which Cmakefile.txt is not playing nice.

**Comment by khallebal** [comment]
@tsujan  are you planning on removing the qmake build system?

**Comment by tsujan** [comment]
> @tsujan are you planning on removing the qmake build system?

Actually, Qt will remove it in its version 6. Although I have no plan to remove the qmake support, I prefer to rely on cmake for a clean compilation.

**Comment by khallebal** [comment]
I just tried and it worked just fine! @shlyakpavel are you using a recent nightly build of haiku? 32 or 64, do you have qt5_tools installed? please clean up the build dir and retry again,  watch the output and see whether the translations are actually being built. thanks

**Comment by tsujan** [comment]
> I just tried and it worked just fine!

Hurrah! I knew cmake shouldn't be different from qmake in this regard. As for Hunspell, cmake seems better.

**Comment by shlyakpavel** [comment]
> I just tried and it worked just fine! @shlyakpavel are you using a recent nightly build of haiku?

Yes
> 32 or 64

64
> do you have qt5_tools installed?

yes
> please clean up the build dir and retry again, watch the output and see whether the translations are actually being built. 

They are being built. The app is still failing to install with the same error message

**Comment by khallebal** [comment]
I really don't know why it fails with your setup? could you please paste the complete outputs of the configure and make install phase?

**Comment by shlyakpavel** [comment]
Buggy piece of crap. I didn't succeed in installing it for thousands of times. But at the time I redirected output it succeeded.
```
cmake .. > cmake.log.txt
make > make.log.txt
make install > install.log.txt
```
https://gist.github.com/shlyakpavel/e759fb2a8d1256822614e20529719805
I strongly believe the problem is still present and still in there. That could be some kind of cmake bug or UFO stealing variables in order to build red sphere houses on Mars

**Comment by shlyakpavel** [comment]
It doesn't load Russian translation if I run it from `/boot/home/config/non-packaged/apps/FeatherPad/` 😢

**Comment by tsujan** [comment]
In Linux (and probably, Unix), to test a translation, we do:

```
LANGUAGE=ru featherpad
```

![ru](https://user-images.githubusercontent.com/981076/63263329-86478980-c29d-11e9-97ad-364b02b72ad6.png)

Please note that FeatherPad is a single-instance app, which means its restart needs closing of all of its windows: if a single window is running, the old session will continue.

**Comment by shlyakpavel** [comment]
> In Linux (and probably, Unix), to test a translation, we do:
> 
> ```
> LANGUAGE=ru featherpad
> ```

Yes, that works for me on linux & Mac
But not on Haiku
<img width="881" alt="image" src="https://user-images.githubusercontent.com/19782228/63264949-0a494380-c295-11e9-8f0f-2e172828f285.png">
@khallebal

**Comment by khallebal** [comment]
Ah.., so the .qm files get installed after all? but unlike with qmake they're being installed in 
`/boot/home/config/non-packaged/apps/Featherpad` 
instead of 
` /boot/home/config/non-packaged/apps/Featherpad/translations`
Qmake adds automatically the /translations subdir to
`/boot/home/config/non-packaged/apps/Featherpad` 
whereas cmake doesn't and that's why Featherpad can't find them
So i think the solution is to change `${CMAKE_INSTALL_PREFIX}` to `${CMAKE_INSTALL_PREFIX/translations}` in `CMakeLists.txt`

**Comment by tsujan** [comment]
> Qmake adds automatically the /translations subdir...

Thank you very much! You solved the problem.

It isn't automatic though. With qmake, the folder `translations` is put into the destination directory, while with cmake, its files are put into `destination/translations/`. That's the case for Linux/Unix and should be the same for Haiku but `translations` is missing for `CMakeLists.txt` for HAIKU.

Now, it's missing for APPLE too. So, translations shouldn't work with cmake compilation under macOS either. @shlyakpavel, is it possible that you have the folder `translations` from a previous installation?

**Comment by khallebal** [comment]
Well, it actually only fixes the installation routine, the translations for some unknown reason don't work, i can't change to any language, it could be a bug in the haiku Qt port , i'll file ticket to the maintainer and see if he has a fix.

**Comment by shlyakpavel** [comment]
@tsujan don't worry about the translations on Mac. I've already fixed that in my PR. I hope you will merge it once it gets ready
