### ISSUE TITLE
Feature request: open at line #

### ISSUE THREAD

**Issue by shlyakpavel** [tsujan/FeatherPad#306]
Many text editors support line number as an argument then opening a file
Like `featherpad qps.cpp:840`
Feathered does not support it with a message that "file does not exist"
Would be great to see it supported one day

**Comment by tsujan** [comment]
> Many text editors support line number as an argument then opening a file

And FeatherPad supports more ;) See `featherpad --help`.

**Comment by shlyakpavel** [comment]
1. `featherpad makefile+9` - "file not found"
2. Most apps use : as a separator. Why did you change this?

**Comment by tsujan** [comment]
> "file not found"

Because you're doing it wrong. Everything is explained in `fpad --help`. The syntax is taken from a very famous text editor (I don't remember its name because I only use FeatherPad).

**Comment by agaida** [comment]
i guess it was nano - and i guess i was suggesting the implementation nano-like - btw. works fine with debian change logs - thats why i asked for :smile:

**Comment by tsujan** [comment]
> i guess it was nano

Yes! It was you suggestion and it was a good one, as usual :)
