### ISSUE TITLE
font changing is not saved

### ISSUE THREAD

**Issue by psic** [tsujan/FeatherPad#308]
I change the font for some font, it's working for the current document and the new tabs. I quit. I open featherPad, it's working.
I change the font for Fira (which I install, I do not remember how, but it's shown in the font list). It's ok for the current document and the new tab. I quit. I open featherPad, and Fira is gone?

**Comment by tsujan** [comment]
FeatherPad doesn't (actually, can't) remove fonts ;) I installed Fira (ttf-fira-sans), chose it in font dialog, quit, opened FeatherPad, and Fira is still chosen and, of course, it's still installed.

BTW, Fira isn't a fixed-pitched font. The new font dialog tells you about that. It has a checkbox for "Programmin fonts". If it's checked, you'll see only fixed-pitched (monospace) fonts, which are most suitable for a text editor.

**Comment by tsujan** [comment]
Also make sure that preferences → Text → Remember font is checked.
