### ISSUE TITLE
main window position is not remembered on start

### ISSUE THREAD

**Issue by pvanek** [tsujan/FeatherPad#31]
when its config option is set

**Comment by tsujan** [comment]
It's meaningful for a text editor to remember its size but NOT its position (yes, for notes manager -- [FeatherNotes](https://github.com/tsujan/FeatherNotes) --  it has meaning).

**Comment by tsujan** [comment]
> when its config option is set

Oh, that option you saw was about size, not about position.

**Comment by pvanek** [comment]
yes, but I think the initial position should be remembered too (my 2c only)

**Comment by tsujan** [comment]
I agree that remembering position is useful with an app that is always running (in systray, for example) and whose window is shown/hidden (not minimized) constantly. Notes managers are an example: The user wan't to know where the window shows up when he clicks on the tray icon; that's good for reading/editing the contents quickly. But there's no practical usage for a fixed position in the case of a text editor, file manager, web browser,...
