### ISSUE TITLE
feature request: syntax highlighting support for dart lang

### ISSUE THREAD

**Issue by antej** [tsujan/FeatherPad#318]
more details: https://en.wikipedia.org/wiki/Dart_(programming_language)

https://dart.dev/guides/language/language-tour#keywords

Thank you!

**Comment by tsujan** [comment]
I should first get familiar with Dart -- never heard of it before -- and I should do that in my free time (which is taken by several projects). So, it might take a while.

Thanks for the suggestion!

**Comment by antej** [comment]
Dart is language used by Google for the new Flutter framework.
Here's a 2 minute video about it:
https://www.youtube.com/watch?v=fq4N0hgOWzU
Thank you for making FeatherPad!

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/19e971706c61dcb1451c5f6d2557cc8f58cdbe42

Please note that it isn't a complete Dart support. It handles keywords, types and dart:core classes. If there is an issue in these areas, please tell me.

Later, I might cover more classes.
