### ISSUE TITLE
"show line number" option is not persistent over sessions

### ISSUE THREAD

**Issue by pvanek** [tsujan/FeatherPad#32]

**Comment by tsujan** [comment]
Check `Preferences` → `Text` → `Always show line numbers`!

**Comment by pvanek** [comment]
ah, it works this way. A little bit confusing IMHO.

**Comment by tsujan** [comment]
Line numbers aren't what many users want to see always. I use FeatherPad for coding, so I use line numbers often but prefer not to see it next time once I enable it in a session. Anyhow, I really don't think that option -- in its appropriate tab -- could be confusing ;)
