### ISSUE TITLE
build errors: connection of signals/slots does not work for Qt 5.6.1

### ISSUE THREAD

**Issue by pvanek** [tsujan/FeatherPad#33]
I have to change many occurrences of connect in my local build:

```
-        connect (closeButton, &QAbstractButton::clicked, msgDlg, &QDialog::reject);
+        connect (closeButton, SIGNAL(clicked(bool)), msgDlg, SLOT(reject()));
```

maybe I'm using too old version of Qt. What is minimal required one? qmake should check it too...

**Comment by tsujan** [comment]
This is new signal-slot syntax in Qt 5. Please see [here](https://wiki.qt.io/New_Signal_Slot_Syntax) and [here](https://woboq.com/blog/new-signals-slots-syntax-in-qt5.html). Probably your gcc (g++ in Debian based systems) is too old

**Comment by pvanek** [comment]
```
pvanek@spongebob:~> g++ --version
g++ (SUSE Linux) 4.8.5
```

pro file should check it in this case too ;)

**Comment by tsujan** [comment]
Yes, it's too old. With Qt5, The version of g++ should be greater than 5 -- please read I`NSTALL`!

As for checking the vesion in the pro file, you're right. I didn't do so because (1) Qt5 needed g++ ≥ 5 for some of its features, and (2) even an old distro like Ubuntu LTS had g++ ≥ 5.

**Comment by tsujan** [comment]
Now, g++-4.8.5 is too old for this app. Closing this.
