### ISSUE TITLE
support to view *.ass or *.srt 

### ISSUE THREAD

**Issue by shirishag75** [tsujan/FeatherPad#334]
First of all below is the featherpad version and details so you know how things are. 

```
Package: featherpad
Version: 0.11.1-2+b1
Severity: normal

-- System Information:
Debian Release: bullseye/sid
  APT prefers testing
  APT policy: (900, 'testing'), (500, 'testing-debug'), (100, 'unstable-debug'), (100, 'experimental'), (100, 'unstable'), (50, 'experimental-debug')
Architecture: amd64 (x86_64)

Kernel: Linux 5.3.0-3-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages featherpad depends on:
ii  libc6                2.29-3
ii  libgcc1              1:9.2.1-21
ii  libhunspell-1.7-0    1.7.0-2+b1
ii  libqt5core5a         5.12.5+dfsg-2
ii  libqt5gui5           5.12.5+dfsg-2
ii  libqt5network5       5.12.5+dfsg-2
ii  libqt5printsupport5  5.12.5+dfsg-2
ii  libqt5svg5           5.12.5-2
ii  libqt5widgets5       5.12.5+dfsg-2
ii  libqt5x11extras5     5.12.5-1
ii  libstdc++6           9.2.1-21
ii  libx11-6             2:1.6.8-1

Versions of packages featherpad recommends:
ii  featherpad-l10n  0.11.1-2
ii  libglib2.0-bin   2.62.3-2

featherpad suggests no packages.

-- no debconf information
```

Now many a times I see either *.ass or *.srt not being viewable under featherpad, in fact featherpad refuses to acknowledge those files and says those files are not present whereas gedit shows them without an issue. 

```
$ file subs.srt
subs.srt: UTF-8 Unicode text, with CRLF, LF line terminators
```

**Comment by tsujan** [comment]
SRT syntax highlighting has been supported for a long time:

![SRT](https://user-images.githubusercontent.com/981076/71550425-1d0f1a00-29e5-11ea-8033-a3ac381f0fa7.png)

`.ass` is opened as a simple text. It isn't interesting enough for a text editor to highlight its syntax -- Kate doesn't do so either by default.

If you have a text SRT file, whose syntax isn't highlighted by FeatherPad, please attach it as a zipped archive.

**Comment by shirishag75** [comment]
actually at my end, .ass doesn't seem to be supported. I get the following - 

![featherpad-file-could-not-be-opened](https://user-images.githubusercontent.com/727626/71552497-38ceec00-29f6-11ea-8c8a-cb2345c769c4.png)
I am able to open the .srt (was not able to open it before but not .ass while in gedit I can. 

```
$ls -lh > ls-lh.txt
total 633k
-rw-r--r-- 1 shirish shirish    0 Dec 29 10:17 ls-lh.txt
-rw-r--r-- 1 shirish shirish 303K Dec 29 04:41 sub.srt
-rw-r--r-- 1 shirish shirish 233K Dec 29 04:22 sub.ass
```

**Comment by wxl** [comment]
You should provide the example file as aforementioned.

**Comment by shirishag75** [comment]
@wxl how, github doesn't support .ass , the only thing I could do is zip it, would that be ok ?

[sub.ass.zip](https://github.com/tsujan/FeatherPad/files/4007778/sub.ass.zip)

**Comment by tsujan** [comment]
Actually, your attached file shows how well FeatherPad works.

The file has a problem that FeatherPad sees but gedit (or Kate) doesn't. FeatherPad will open it in the uneditable mode once you uncheck `Preferences → Files → Do not permit opening of non-text files`. Fortunately, the problem is quite visible:

![uneditable](https://user-images.githubusercontent.com/981076/71555582-3e065800-2a43-11ea-80e5-60d2995fe5c0.png)

There is an extra null character near the beginning of the file (shown by a rectangle). Real text files don't contain random null characters in their middle; null has special meanings. In short, the file is bad formed and FeatherPad is aware of that, while gedit isn't.

Ignoring such problems -- in the way gedit does -- might cause data loss.

In this special case, the file can be corrected by pasting its contents to a new tab, removing the "rectangle character", and saving it:

![corrected](https://user-images.githubusercontent.com/981076/71555677-e9171180-2a43-11ea-91a7-c98ef6a6162a.png)

But that's only by chance; FeatherPad is NOT a file repair tool.

**Comment by tsujan** [comment]
More interestingly, `subtitleeditor` is also aware of the problem in the attached file:

![subtitleeditor](https://user-images.githubusercontent.com/981076/71555861-a22a1b80-2a45-11ea-9fa3-c4278c771022.png)

But not in the corrected one:

![good_file](https://user-images.githubusercontent.com/981076/71555872-c71e8e80-2a45-11ea-89d7-e8969b3dabad.png)

**Comment by shirishag75** [comment]
when you pointed out I also got the issue in the gedit, perhaps I had overlooked it before. 
it does bring another point, the error it gives is generic, if it had given me something more substantial I would have known what proper steps to take, for e.g. as in gedit. That gave me much info. to figure out what the issue is. 

![gedit-error](https://user-images.githubusercontent.com/727626/71556204-45bb0200-2a2d-11ea-9341-413e44feaa9c.png)

**Comment by tsujan** [comment]
> the error it gives is generic, if it had given me something more substantial I would have known what proper steps to take

I agree. I'll change the error message in V0.12.1 (0.12.0 is already released).

But opening in the uneditable mode will be kept. After unchecking `Preferences → Files → Do not permit opening of non-text files`, you could open all kinds of files in FeatherPad by DND. That's intentional because some files -- like PDF -- have hidden info that can be found in this way. However, the document shouldn't be editable because, otherwise, it could be easily corrupted.

**Comment by tsujan** [comment]
An example of a PDF file, opened by FeatherPad in the uneditable mode, with interesting info in it:

![pdf_file](https://user-images.githubusercontent.com/981076/71556806-18347f80-2a52-11ea-895e-558b1947da9f.png)

The uneditable mode has a special background.

**Comment by shirishag75** [comment]
> > the error it gives is generic, if it had given me something more substantial I would have known what proper steps to take
> 
> I agree. I'll change the error message in V0.12.1 (0.12.0 is already released).
> 
> But opening in the uneditable mode will be kept. After unchecking `Preferences → Files → Do not permit opening of non-text files`, you could open all kinds of files in FeatherPad by DND. That's intentional because some files -- like PDF -- have hidden info that can be found in this way. However, the document shouldn't be editable because, otherwise, it could be easily corrupted.



> > the error it gives is generic, if it had given me something more substantial I would have known what proper steps to take
> 
> I agree. I'll change the error message in V0.12.1 (0.12.0 is already released).
> 
> But opening in the uneditable mode will be kept. After unchecking `Preferences → Files → Do not permit opening of non-text files`, you could open all kinds of files in FeatherPad by DND. That's intentional because some files -- like PDF -- have hidden info that can be found in this way. However, the document shouldn't be editable because, otherwise, it could be easily corrupted.

agreed, no issue with that at all :)

**Comment by shirishag75** [comment]
> An example of a PDF file, opened by FeatherPad in the uneditable mode, with interesting info in it:
> 
> ![pdf_file](https://user-images.githubusercontent.com/981076/71556806-18347f80-2a52-11ea-895e-558b1947da9f.png)
> 
> The uneditable mode has a special background.

That I would say is a feature rather than something minus. At times I have been stymied and have had to find creative ways to find the info. displayed, although dunno how it would work with pdf files which are 100 MB's . I have seen most text-editors struggle with opening pdf's of large sizes,

**Comment by tsujan** [comment]
> dunno how it would work with pdf files which are 100 MB's 

Opening non-text files with sizes greater than 100 MiB can be very CPU-intensive. On my computer, there's no problem up to 500 MiB -- once, I also opened a 1-GiB file (after changing the code) -- but this is a powerful laptop. I hated it it when Kate hung in such cases and I didn't want that for FeatherPad.

IMO, a text/code editor should remain like a text/code editor -- probably, with a few non-text functionalities.

**Comment by shirishag75** [comment]
> > dunno how it would work with pdf files which are 100 MB's
> 
> Opening non-text files with sizes greater than 100 MiB can be very CPU-intensive. On my computer, there's no problem up to 500 MiB -- once, I also opened a 1-GiB file (after changing the code) -- but this is a powerful laptop. I hated it it when Kate hung in such cases and I didn't want that for FeatherPad.
> 
> IMO, a text/code editor should remain like a text/code editor -- probably, with a few non-text functionalities.

care to share the specs, RAM, CPU without diclosing the make. I am guessing these would be the most important bits.

**Comment by shirishag75** [comment]
@tsujan also when you do code, please reference this report and the bad null character so know . Preferably, also document what the error would be so we know what to look out for.

**Comment by tsujan** [comment]
> care to share the specs,

I prefer moderately priced gaming laptops because they're the best with coding, compiling and heavy jobs. This one is relatively old but has worked very well. CPU: Intel Core i7-6700HQ 52, GPU: NVIDIA GeForce (but I only use Intel; it's very good with 3D), Hard: 256GB PCIe SSD + 1TB HDD, RAM. 16GB DDR4. The double fan cools the system fast and efficiently.

> I have been also looking for subtitle checker 

Sorry, I'm not an expert in subtitles. I rarely use them -- with non-English films or, for example, when a Welsh accent is weird to my ears. Previously, I used `subtitlecomposer` but it was too heavy and sometimes didn't compile. Now, a simple tool like `subtitleeditor` is enough for me.

BTW, I'll change the message to this:

![non-text](https://user-images.githubusercontent.com/981076/71557251-e541ba00-2a58-11ea-89af-dadb2dc9865b.png)

"Non-text" means that it isn't a text file and and shouldn't be treated as such. Whether it was intended to be a text file or not is beyond FeatherPad (for now, at least). Non-text files usually have lots of null and non-readable characters.

**Comment by shirishag75** [comment]
> > care to share the specs,
> 
> I prefer moderately priced gaming laptops because they're the best with coding, compiling and heavy jobs. This one is relatively old but has worked very well. CPU: Intel Core i7-6700HQ 52, GPU: NVIDIA GeForce (but I only use Intel; it's very good with 3D), Hard: 256GB PCIe SSD + 1TB HDD, RAM. 16GB DDR4. The double fan cools the system fast and efficiently.
> 
> > I have been also looking for subtitle checker
> 
> Sorry, I'm not an expert in subtitles. I rarely use them -- with non-English films or, for example, when a Welsh accent is weird to my ears. Previously, I used `subtitlecomposer` but it was too heavy and sometimes didn't compile. Now, a simple tool like `subtitleeditor` is enough for me.
> 
> BTW, I'll change the message to this:
> 
> ![non-text](https://user-images.githubusercontent.com/981076/71557251-e541ba00-2a58-11ea-89af-dadb2dc9865b.png)
> 
> "Non-text" means that it isn't a text file and shouldn't be treated as such. Whether it was intended to be a text file or not is beyond FeatherPad (for now, at least). Non-text files usually have lots of null and non-readable characters.

That doesn't work if like me you uncheck non-text files but guess see your point. Maybe at some point in the future, there could be a way to find out about null characters . If you want I can make a separate ticket about null characters which would be something that could be checked for or as a parsed. If you know of any command which does this on shell that would also be good enough at least for now ?

**Comment by tsujan** [comment]
> That doesn't work if like me you uncheck non-text files

The message explicitly says which option is pertinent (in its second line). The user could choose to uncheck it or keep it checked.

> Maybe at some point in the future, there could be a way to find out about null characters

"Meaningless" null characters == non-text file.

In a valid text file, null characters should be in certain positions. If not, the file is not a text document. There is no other way of distinguishing between text and non-text. You could have very unusual characters in a valid text file -- like colored emojis, which are supported by FeatherPad when the DE's font settings support them:

![emojis](https://user-images.githubusercontent.com/981076/71557909-34401d00-2a62-11ea-9c25-661ec46c0daf.png)

gedit sees all files as text files and then mentions the existence of "invalid characters" (== meaningless null chars). FeatherPad considers a file as a text doc only when it is well-formed. Different ways of saying the same thing...
