### ISSUE TITLE
Norwegian Bokmål translation

### ISSUE THREAD

**Issue by hansfn** [tsujan/FeatherPad#339]
I have just completed the Norwegian Bokmål translation - see https://weblate.lxqt.org/projects/tsujan/featherpad/nb_NO/ Please include it in the next release.

And thanks for an excellent program.

PS! The information about translations in `README.md` and `INSTALL` are inconsistent.

**Comment by tsujan** [comment]
Thanks for your translation! I added your name and github address to the Translators tab of About dialog. I'll wait for the PR and, after merging it, will release 0.12.1.

> PS! The information about translations in README.md and INSTALL are inconsistent.

The info in `INSTALL` was added before the Weblate support. Fortunately, all translators use Weblate but that info is for those who may want to use Qt Linguist directly.

**Comment by hansfn** [comment]
OK, I see now that Weblate automatically creates PRs. It seems a bit noisy ... Closing this issue now. 

PS! I didn't get your "Thanks" comment on the first (?) PR. If I had, I wouldn't have created this issue.

**Comment by tsujan** [comment]
> I didn't get your "Thanks" comment on the first

My bad. I should have added "@hansfn". I guess Github doesn't send email notifications with Weblate PRs.

**Comment by tsujan** [comment]
I downloaded and applied your translation manually because I needed to add a commit.

BTW, Weblate doesn't make PRs automatically; [Helix](https://github.com/HelixBot) does.
