### ISSUE TITLE
Actions that I do not understand

### ISSUE THREAD

**Issue by shlyakpavel** [tsujan/FeatherPad#342]
https://github.com/tsujan/FeatherPad/blob/c98872d49e823ac277a7f567cbcf26e98221abe5/featherpad/config.cpp#L130-L134
That can be changed to
```
if (noToolbar_ && noMenubar_)
{
noToolbar_ = false;
}
```
Right?

**Comment by tsujan** [comment]
Right. Sometimes, super explicitness is good for me when I'm searching for needles (bugs) in haystacks.

BTW, it's good to hear from you again.

**Comment by tsujan** [comment]
And VERY unrelated to FeatherPad:

Could you please review https://github.com/lxqt/qps/pull/214 ?

**Comment by shlyakpavel** [comment]
> Right. Sometimes, super explicitness is good for me when I'm searching for needles (bugs) in haystacks.

On the other side, such a code is suspicious and sometimes looks like a bug itself. I'd recommend to be careful with it.

**Comment by tsujan** [comment]
Must respectfully disagree. But it isn't important.

**Comment by tsujan** [comment]
Thanks for the QPS review, BTW -- I wasn't sure about the change.

As a member, you could also add yourself to reviewers and approve, request changes,..., at LXQt.
