### ISSUE TITLE
Unicode validation

### ISSUE THREAD

**Issue by shlyakpavel** [tsujan/FeatherPad#343]
https://github.com/tsujan/FeatherPad/blob/c98872d49e823ac277a7f567cbcf26e98221abe5/featherpad/encoding.cpp#L506-L507
Validating a pointer seems to be weird. 
Didn't you mean `if (!*string) return true;` to validate empty strings?

**Comment by tsujan** [comment]
It's just a nullity check; nothing more.

**Comment by shlyakpavel** [comment]
Can `byteArray.constData()` be a null pointer? Why does it return true in such a strange case?

**Comment by tsujan** [comment]
> Can byteArray.constData() be a null pointer?

Better safe than sorry. Always!

> Why does it return true in such a strange case?

To praise UTF8.
