### ISSUE TITLE
Not translate Japanese

### ISSUE THREAD

**Issue by ito32bit** [tsujan/FeatherPad#347]
I use FeatherPad in Japanese.

```bash
$ echo $LANG
ja_JP.UTF-8
$ featherpad
```
When I run FeatherPad, menus and dialogs are in English but not Japanese.

FeatherPad Ver: Latest git
Linux: Ubuntu 18.04.4 LTS
Qt: 5.9.5

**Comment by tsujan** [comment]
Here, if I run it with `LANG=ja_JP && featherpad`:

![jp](https://user-images.githubusercontent.com/981076/73636486-2e4de500-467b-11ea-979e-4af73905eb40.png)

Could you please be more specific about what you mean by "menus and dialogs"? A screenshot?

**Comment by ito32bit** [comment]
All are in English:  

![screen-2020-02-04-11-26-13](https://user-images.githubusercontent.com/52656419/73709424-64a36700-4744-11ea-9374-c769f6f91737.jpg)

Also Lubuntu 18.04:  

![2020-02-04-103334_1024x768_scrot_A](https://user-images.githubusercontent.com/52656419/73709449-771da080-4744-11ea-87d0-547d13ab3409.jpg)

**Comment by tsujan** [comment]
Strange! Your locale shows `ja_JP`, not `ja`. Have you installed `qttranslations5-l10n`?

**Comment by ito32bit** [comment]
Of course I have it installed.
```bash
$ LANG=C apt list qttranslations5*
Listing... Done
qttranslations5-l10n/bionic,now 5.9.5-0ubuntu1 all [installed]
```

I found:

```bash
$ echo $LANG
ja_JP.UTF-8
$ echo $LANGUAGE
ja:en
$ LANGUAGE=ja_JP:en featherpad
```

![screen-2020-02-04-18-35-41](https://user-images.githubusercontent.com/52656419/73733722-d1882280-477f-11ea-8da9-8976d2acd95f.jpg)

**Comment by tsujan** [comment]
@ito32bit 
There was a typo in the code: `_` should have been used instead of `-`. I fixed it and also changed the name as in LXQt (..._ja.ts).

Now, I can get the Japanese translation and help wit both `ja_JP` and `ja`.

Would you please test the latest git version and check if the problem is solved?

**Comment by ito32bit** [comment]
I tested it.

![screen-2020-02-05-11-13-28](https://user-images.githubusercontent.com/52656419/73805201-5f5c2000-4809-11ea-87be-995ac233f150.jpg)

Good. Thank you.

**Comment by tsujan** [comment]
Thanks!

**Comment by tsujan** [comment]
BTW, I'll do the same thing in other apps, especially in FeatherNotes. If it weren't for your report, I wouldn't find the problem; I really appreciate it.

**Comment by ito32bit** [comment]
You are welcome.
