### ISSUE TITLE
Feature request: add tab indent

### ISSUE THREAD

**Issue by fulalas** [tsujan/FeatherPad#35]
If you select one or more lines and then press TAB, the selection is deleted instead of being indented. Same with SHIFT + TAB.

**Comment by tsujan** [comment]
It'll be a good feature. I'll work on it. Thanks!

**Comment by tsujan** [comment]
Done. Please test!

Please also note that back-tab (Shift+Tab) should work with a single line too and should remove not only a single tab indentation but also 4 ordinary spaces (at most) each time.

**Comment by fulalas** [comment]
Great! It's almost there, I think. If I just TAB a single line, it's deleted. It only works with 2 or more lines, or 1 or more lines when back-tabing. QtCreator, for example, always tab, regarding if it's 1 or more lines or forward or back tab. :)

**Comment by tsujan** [comment]
> QtCreator, for example, always tab, regarding if it's 1 or more lines

Kate doesn't. If the user wants to add a tab indent to a single line, he could do so easily by inserting the tab at its start. Moreover, the user may need to insert tab somewhere inside a line (with or without selection).

**Comment by tsujan** [comment]
Actually, QtCreator is only for coding; a text editor goes beyond coding; hence tabs inside lines.

**Comment by fulalas** [comment]
Maybe I wasn't clear enough. Try this code inside TextEdit (remember to comment shift+tab event since I used just one method in order to avoid code duplication):
```
    else if (event->key() == Qt::Key_Tab || event->key() == Qt::Key_Backtab)
    {
        QTextCursor cursor = textCursor();
        int newLines = cursor.selectedText().count (QChar::ParagraphSeparator);
        bool isTextSelected = cursor.selectedText().size() > 0;

        cursor.beginEditBlock();
        if( newLines > 0 || isTextSelected )
        {
            if (cursor.anchor() <= cursor.position())
                cursor.setPosition(cursor.anchor());

            cursor.movePosition (QTextCursor::StartOfBlock);
        }

        for (int i = 0; i <= newLines; ++i)
        {
            if( event->key() == Qt::Key_Backtab )
            {
                if(cursor.block().text().size() == 0)
                    break;

                int currentBlockPosition = cursor.positionInBlock();
                if(!isTextSelected)
                {
                    if(cursor.position() == 0 || currentBlockPosition == 0)
                        break;

                    currentBlockPosition--;
                    cursor.setPosition(cursor.position() -1);
                }
                if( cursor.block().text().at(currentBlockPosition) == ' ' )
                {
                    for (int j = 0; j < 4; ++j)
                    {
                        if(cursor.block().text().at(currentBlockPosition) == ' ')
                        {
                            cursor.deleteChar();

                            if(currentBlockPosition == 0 || cursor.position() == 0)
                                break;

                            currentBlockPosition--;
                            cursor.setPosition(cursor.position()-1);
                        }
                    }
                }
                else if( cursor.block().text().at(currentBlockPosition) == '\t' )
                    cursor.deleteChar();
            }
            else
                cursor.insertText ("\t");
            if (!cursor.movePosition (QTextCursor::NextBlock))
                break; // not needed
        }
        cursor.endEditBlock();
        event->accept();
        return;
    }
```
As you can see, you can still insert/remove TABs in the middle of the text, even if it's not selected. I believe this behavior is more intuitive and useful. :)

BTW, I also added some key/mouse events in FPwin in order to extend the shortcuts to something more common (i.e. ctrl + w or ctrl + F4 -> closes current tab / Esc -> closes search bar). Of course, I had to disable the original ctrl + w shortcut.

```
void FPwin::keyPressEvent( QKeyEvent* e )
{
    if( (e->key() == Qt::Key_F4 || e->key() == Qt::Key_W ) && (QApplication::keyboardModifiers() & Qt::ControlModifier))
    {
        closeTab();
    }
    if( e->key() == Qt::Key_Escape )
    {
        int index = ui->tabWidget->currentIndex();
        if (index == -1) return;
        TabPage *tabPage = qobject_cast< TabPage *>(ui->tabWidget->widget (index));

        if(tabPage->isSearchBarVisible())
            showHideSearch();
    }
}
```

About mouse wheel click to close tab, I can't figure out a way of calling FPwin::closeTab() from TabBar class. Do you have any idea?

**Comment by tsujan** [comment]
> Maybe I wasn't clear enough.

You were clear enough. As I mentioned earlier, this behavior isn't natural for a text editor; tab should work as tab, not as a tab indentation, *for a single line, with or without selection*. When a part of a  single-line text is selected, tab should replace it with a tab space. Kate has the same behavior and even if hadn't, I'd prefer the current behavior in FeatherPad. The cases of multiple lines and back-tab are quite different.

As for shortcuts and mouse click, https://github.com/tsujan/FeatherPad/issues/29 is in my TODO list. I'll implement those features as soon as I have some free time for them. Let's discuss those matters on that page and when I start to work on them. Thanks in advance for your patience!

**Comment by tsujan** [comment]
BTW, I used separate blocks for tab and back-tab in `textedit.cpp` intentionally -- the tab part might be changed to include modifiers in future.

**Comment by fulalas** [comment]
I see. I can't remember if your current back-tab is moving by multiples of 4, since removing 4 spaces doesn't seem the right solution in all situations. The idea is to move each text block to a position that is always aligned with tab space-distance (indeed it's the current default behavior for forward tab). Let me know if I'm explaining this clear enough (as you can see, English isn't my native language :P).

Thanks for your hard work!

**Comment by tsujan** [comment]
> The idea is to move each text block to a position that is always aligned with tab space-distance 

It removes a tab or, at most, 4 spaces, whichever is present. This is exactly what Kate does. Aligning is always done by the user, in any way he/she sees appropriate.

> BTW, I don't know if this makes you happier, but I'm including FeatherPad as the only notepad inside LXQt package for Porteus distro.

By "notepad" you mean "text editor"; don't you. And yes, I'm glad :)

> Thanks for your hard work!

Thank you for your bug reports/feature requests!

**Comment by fulalas** [comment]
4 spaces at most means it sometimes removes less in order to keep tab spacing coherence (like it happens with forward tab)?

Yes, text editor! :) I like this minimalist approach that FeatherPad and LXQt have. And Porteus too, of course! Why having an OS with more than 300 mb, consuming more than 700 mb of RAM after boot, right? :+1:

**Comment by tsujan** [comment]
> 4 spaces at most means it sometimes removes less in order to keep tab spacing coherence (like it happens with forward tab)?

Neither multi-line `Shift+Tab` nor multi-line `Tab` is for aligning but for adding/removing tabs. If the lines are aligned, `Shift+Tab`/`Tab` will preserve their alignment, otherwise it won't make a magic ;) A well-known text editor like Kate has the same behavior, as I mentioned above.
