### ISSUE TITLE
how to syntax-highlighting inline?

### ISSUE THREAD

**Issue by 3xploiton3** [tsujan/FeatherPad#371]
![image](https://user-images.githubusercontent.com/19517680/76143720-5bdbe300-60ac-11ea-97fa-cb759b0c1ff6.png)

**Comment by tsujan** [comment]
Apparently, I was too cautious.

Fixed in https://github.com/tsujan/FeatherPad/commit/d2bea674d401b0749cc06178c06e501d23d93242. Now, these characters are allowed in URLs (but not in email addresses): `-._~:/?#[]@!$&'()*+,;=%`.

![special_chars](https://user-images.githubusercontent.com/981076/76144491-4065dd80-6096-11ea-9e15-9c0048dbfce1.png)

Thanks for your report!

**Comment by 3xploiton3** [comment]
thx for fast response,

how to update application
i tried `sudo apt update` didn't work

i'm using lubuntu 19.10

**Comment by tsujan** [comment]
> how to update application

Only if you had Arch/Manjaro, you could use AUR and have the latest git FeatherPad.

> i'm using lubuntu 19.10

Ubuntu/Lubuntu 19.10 has old versions of everything. I'll release FeatherPad 0.13.0 soon. Hopefully, it'll be in Ubuntu 20.04 but that's up to Ubuntu maintainers.

**Comment by 3xploiton3** [comment]
> > how to update application
> 
> Only if you had Arch/Manjaro, you could use AUR and have the latest git FeatherPad.
> 
> > i'm using lubuntu 19.10
> 
> Ubuntu/Lubuntu 19.10 has old versions of everything. I'll release FeatherPad 0.13.0 soon. Hopefully, it'll be in Ubuntu 20.04 but that's up to Ubuntu maintainers.

![image](https://user-images.githubusercontent.com/19517680/76227607-24a73680-6252-11ea-9b48-f0be914f55ef.png)

i change to manjaro now, still old version  :(

**Comment by tsujan** [comment]
> i change to manjaro now, still old version :(

You need to use featherpad-git from AUR. It's here: https://aur.archlinux.org/packages/featherpad-git/

Go to that page, click "Download snapshot", extract the archive, open a terminal inside it and enter `makepkg`. After the package is made, install it with `sudo pacman -U *.pkg.tar.xz`.

With Manjaro/Arch+AUR, you could always have the latest git version. Just do the above once in a while.

Later, you could also use an AUR helper like `yay` (recommended) to make everything automatic but the above method is enough for now.

**Comment by 3xploiton3** [comment]
> > i change to manjaro now, still old version :(
> 
> You need to use featherpad-git from AUR. It's here: https://aur.archlinux.org/packages/featherpad-git/
> 
> Go to that page, click "Download snapshot", extract the archive, open a terminal inside it and enter `makepkg`. After the package is made, install it with `sudo pacman -U *.pkg.tar.xz`.
> 
> With Manjaro/Arch+AUR, you could always have the latest git version. Just do the above once in a while.
> 
> Later, you could also use an AUR helper like `yay` (recommended) to make everything automatic but the above method is enough for now.

thx man, it work, how about if any update in future? what should i do?

**Comment by tsujan** [comment]
> how about if any update in future? what should i do?

You could do the same every month if you want to have the latest fixes/features.
