### ISSUE TITLE
Unexpected file type when saving with multiple tabs

### ISSUE THREAD

**Issue by chriswyatt** [tsujan/FeatherPad#372]
### Version / Distribution
0.11.1 (Arch Linux)

### How to reproduce:

 - Open XML file
 - Open a new, empty file, in a new tab
 - Write something (e.g. Lorem ipsum)
 - Save file
 - The **Save as...** dialogue box appears and the file type is **.xml**.

### Expected behaviour

I would expect this to default to no extension, or to try and guess the correct extension from the content of the file.

### Other ways to reproduce

You can also reproduce, by opening the **.xml** file in Featherpad (when it is first loaded, and before loading any other files).

The same behaviour can also be observed with **.txt** files. I haven't tried other file extensions, but I assume the behaviour would be the same.

Also, if you close all tabs, and then create a new file, it still remembers the extension of the last remaining file that was closed. E.g., if you opened a **.xml** file, then a **.txt** file, then closed the **.xml** file, then closed the **.txt** file, then created a new empty file and tried to save it, it would try and save the file with a **.txt** extension.

Apologies if that's confusing. It's a little hard to explain! If that's making your head spin, it may be easier to do your own explorative testing!

### Not tested

I haven't tried multiple windows or file extensions other than **.txt** or **.xml**

**Comment by tsujan** [comment]
> I would expect this to default to no extension

On the contrary, I expect a file with an extension `.xyz` to be saved as a `.xyz` file. Therefore, that's the default. However, the user could select `All Files (*)` and choose another extension or no extension.

This isn't a bug but a feature (red below).

> Apologies if that's confusing. It's a little hard to explain

No need to an apology. It just seems you and I have different expectations ;)

Long story made short, several years ago, I mistakenly overwrote a video file (hundreds of megabytes) when I was saving its subtitle. So, I learned my lesson: *use the same extension when saving!* Hence the feature.

Thanks for caring and reporting though.

**Comment by chriswyatt** [comment]
I still think it's strange that it defaulted to .xml, when the file I was writing contained no XML. I've not experienced this in any other text editor.

Nevertheless, it's a minor annoyance (for me, personally), and it's nice to know it's a feature, rather than a bug.

**Comment by tsujan** [comment]
Sorry, I misunderstood your point! I misread what you said about "new empty tab". This *is* a bug. Reopening...

It seems that I should add a point release after fixing it.

**Comment by tsujan** [comment]
Fixed in https://github.com/tsujan/FeatherPad/commit/f8e9fc2562808147383c320e3fca043e17e0fe2d

My mistake was that I'd gone too far to prevent unintentional overwritings. "Save As" should preserve the extension of an edited file but, when a new tab is created and is saved, there's no real need to remember the last extension — and you were completely right about that.

Thanks for making me see the problem!
