### ISSUE TITLE
Build on NetBSD-9.0_STABLE with pkgsrc-current

### ISSUE THREAD

**Issue by voidpin** [tsujan/FeatherPad#373]
Just want to say thanks. The new release builds on NetBSD without patches, thanks for merging those :)

I'll have a look at packaging the new release of Arqiver as well but, that will require a bit more thinking after 868bd4b
Any tips regarding Arqiver are welcome.
Once again thank you for your interest in allowing your projects to run on NetBSD.

**Comment by tsujan** [comment]
You're welcome.

> Any tips regarding Arqiver...

I think it should be like other projects -- at least, after the changes that I made or None-Linux users. I rely on your info in that regard.

Please discuss Arqiver at its own issue tracker. Thanks!

**Comment by voidpin** [comment]
FYI: I've just launched `featherpad` on Wayland on NetBSD using `swc`/`velox` and there are no issues. It runs smoothly :)

**Comment by tsujan** [comment]
> I've just launched featherpad on Wayland...

Under Wayland, tab drag-and-drop is disabled (because of a Qt+Wayland problem). Also, virtual desktop detection isn't possible for now. But all other things work.

**Comment by voidpin** [comment]
`featherpad-0.13.1`, `arqiver-0.4.0` and `feathernotes-0.6.0` are now available as packages on NetBSD.

**Comment by tsujan** [comment]
Very good!
