### ISSUE TITLE
Preferences not being saved correctly

### ISSUE THREAD

**Issue by heldernovais** [tsujan/FeatherPad#374]
Options like "Remember window size on closing" and "remember window position" are not reflected when the program is restarted. After inspecting ~/.config/featherpad/fp.conf, these settings appear to have no entries in the configuration file, so I presume they were simply forgotten.

**Comment by heldernovais** [comment]
If I change the entry "size" from "@Size(700 500)" to "none", the window size is set to its start size and not remembered, as I previously intended. However, the problem remains.

The problem may lie in the file config.cpp.

**Comment by heldernovais** [comment]
If I add "position=@(0 0)" to the file, the setting "remember window position" appears to be turned on, but the position is actually never remembered.

**Comment by heldernovais** [comment]
Changing the value of position has not effect either.

**Comment by heldernovais** [comment]
"position=@Point(100 100)" has an effect. My bad

**Comment by tsujan** [comment]
Size is correctly remembered. Position is remembered of the window manager is well-behaved (like KWin is).

You don't need to worry about config files -- they'll be updated only when needed (when all FeatherPad windows are closed or Preferences changes). Particularly, if you change them with FeatherPad, they'll be overwritten by FeatherPad.

Also, note that config files are there for the app, not for the user. There are exceptions (like in Kvantum) but, in most cases, it's the app that handles them.

**Comment by heldernovais** [comment]
Well, I use Lubuntu, so, ideally, it would work perfectly.
This is not invalid, the problem is easily visible.

**Comment by heldernovais** [comment]
All windows are being closed and the preferences are being changed and the config file is not being changed.

**Comment by heldernovais** [comment]
Anyways, what kind of a reply is that?

**Comment by tsujan** [comment]
> Anyways, what kind of a reply is that?

A logical one.

When you report a bug, please suppose that the developer doesn't have any telepathic power and, instead, *describe a step-by-step way of reproducing it*. Saying, "If I add "position=@(0 0)" to the file..." (who said you could do that?)  or "Options like... are not reflected..." (reflected in what?!) is not a bug report but a source of confusion.

**Comment by heldernovais** [comment]
"Options like "Remember window size on closing" and "remember window position" are not reflected when the program is restarted."

This is the problem right here.
Literally the first line of the first post. 

Step by step:
Open the window, change the property, close the window, reopen and see how the properties haven't changed. Is this enough or what? No need for telepathic powers, only reading skills.

**Comment by tsujan** [comment]
> Is this enough or what?

That's enough but not reproducible.

I run FeatherPad, check Options like "Remember window size on closing" and "Remember window position", resize FeatherPad (to be sure), close it, run it again, and it'll appear in the same place with its last size before closing.

> No need for telepathic powers, only reading skills.

Read again what you've written on this page, instead of a clear description.

**Comment by heldernovais** [comment]
I'm running the latest version from apt. Any chance this may an older version?
>Package: featherpad
>Version: 0.9.3-1

**Comment by tsujan** [comment]
> I see now that it is older.

It makes no difference. Those options worked OK in 0.9.3 too, although FeatherPad's version is 0.13.1 now.

> Can you update the repository package?

I'm not an Ubuntu/Lubuntu maintainer.

However, most Qt apps need a re-build when the Qt version changes a lot. There will be a possibility of crash if not.

**Comment by heldernovais** [comment]
Well this is weird.
The problem is present when one single window is open in one virtual desktop/workspace (settings aren't saved). However, if I open a second window in another workspace, the problem is no longer present and the settings are appear to be saved correctly.

**Comment by tsujan** [comment]
You could also check if you haven't changed the permissions of the conf files by running FeatherPad as root in an old version of LXQt. FeatherPad can be run as root by `lxsudo featherpad` but ancient versions of LXQt had a bug (and no GUI app should be run with `sudo APP`).

**Comment by heldernovais** [comment]
I haven't changed permissions, but I could only edit the configuration file with a sudo nano.

**Comment by heldernovais** [comment]
OS: Ubuntu 19.04 x86_64 (Lubuntu flavour)

**Comment by tsujan** [comment]
> I move it, close it, reopen and notice how the window position was reset to default/not remembered.

The option about window position has a tooltip that says, "... and may not work with some window managers" (I also mentioned it above, with the word "well-behaved"). The size option, however, should work everywhere.

Needless to say, I repeated what you described above under KWin, and the position was remembered.

**Comment by tsujan** [comment]
Oh, VERY unrelated to this, but now, that we talked for 2 hours:

> Linux: 5.0.0-36-generic

If you have Intel, don't use kernels 5.0 to 5.4! They could cause file system corruption. I wonder how Ubuntu maintainers may have missed that.

**Comment by shlyakpavel** [comment]
> They could cause file system corruption. I wonder how Ubuntu maintainers may have missed that.
Could you please provide a link to bug report/any other information regarding that?

**Comment by tsujan** [comment]
This page has some links: https://linuxreviews.org/Linux_Kernel_5.5_Will_Not_Fix_The_Frequent_Intel_GPU_Hangs_In_Recent_Kernels

It seems that I was wrong about 5.0; bad things started to happen since 5.3. But I only use LTS and experienced nasty freezes with 5.4. Also, SMART's "Number of Reported Uncorrectable Errors" became 1 in the 2 weeks I was using 5.4. So, I switched to the good 4.19.

**Comment by shlyakpavel** [comment]
FYI: I have done all the steps above with the latest daily Lubuntu 20.04. It does save the window location as well as its size.

**Comment by tsujan** [comment]
@shlyakpavel, thanks for your test under Ubuntu!

Window position is tricky -- some X11 WMs set the position too forcefully and, under Wayland, you can't set it with Qt (or GTK or any toolkit).

**Comment by heldernovais** [comment]
> Oh, VERY unrelated to this, but now, that we talked for 2 hours:
> 
> > Linux: 5.0.0-36-generic
> 
> If you have Intel, don't use kernels 5.0 to 5.4! They could cause file system corruption. I wonder how Ubuntu maintainers may have missed that.

Thank you for that, I didn't know. I can't find much information about it, though. Do you have any idea of how it may occur and how to avoid it? I swear, every other day I read news about problems with Intel products.

**Comment by heldernovais** [comment]
Is it the GPU hangs?

**Comment by tsujan** [comment]
@heldernovais 
Apparently, the kernel bug wasn't present in 5.0 -- my mistake. It showed up in 5.3 and I'm not convinced it's fixed in 5.5. Yes, it caused GPU hangs and probably more. I use Linux for 15 years but had never seen such a hang before.

**Comment by shlyakpavel** [comment]
> Apparently, the kernel bug wasn't present in 5.0 -- my mistake. It showed up in 5.3 and I'm not convinced it's fixed in 5.5.

Doing just fine on my i5 with intel GPU :)
<img width="635" alt="image" src="https://user-images.githubusercontent.com/19782228/77778162-a9bb8980-7061-11ea-9e7f-2336a975c5ac.png">

**Comment by tsujan** [comment]
> Doing just fine on my i5 with intel GPU :)

You may be lucky. The freeze happened to me 3-4 times, as if out of nowhere. I could only press the laptop's shutdown button, which, fortunately, caused a clean shutdown -- keyboard, mouse and touchpad were useless.

I'll wait for the next LTS (5.9?). 4.19 has worked seamlessly here, for several months.
