### ISSUE TITLE
(request) feature multi window or split view 

### ISSUE THREAD

**Issue by 3xploiton3** [tsujan/FeatherPad#376]
![image](https://user-images.githubusercontent.com/19517680/78315567-963f7f80-7587-11ea-885e-31d1e5a5b54d.png)

**Comment by tsujan** [comment]
I should see if it can be done in a way that doesn't damage FeatherPad's lightness. I'll consider it later but no promise.

Anyway, thanks for the suggestion!

**Comment by tsujan** [comment]
A few days ago, I started to work on this feature but realized that it would make the code overcomplicated and damage FeatherPad's lightness. The idea itself is good but I'm afraid FeatherPad should remain light.
