### ISSUE TITLE
The File Does Not Exist error

### ISSUE THREAD

**Issue by bjlockie** [tsujan/FeatherPad#378]
v0.11.1

1. cd somewhere (eg. cd /tmp)
2. from the CLI, featherpad somefile.txt &
3. cd somewhere else (eg. cd /home)
4. featherpad someotherfile.txt

The file is not loaded and is not found.

**Comment by tsujan** [comment]
Already reported and fixed. The fix will be included in 0.13.2.

Please either upgrade to the latest git or, until you have the fix, use `featherpad ./somefile.txt`.

**Comment by tsujan** [comment]
BTW, 0.11.1 is really outdated. The latest release is 0.13.1 and will be 0.13.2 soon.
