### ISSUE TITLE
feature request: add LaTex syntax

### ISSUE THREAD

**Issue by hmollercl** [tsujan/FeatherPad#380]
It would be really nice if featherpad has support for LaTex sintax

**Comment by tsujan** [comment]
Maybe later; I can't promise anything but will look into it.

For now, my focus is on optimization and finding and fixing bugs, not on more features.

**Comment by dgtlmoon** [comment]
"syntax" would be the correct word in English

**Comment by tsujan** [comment]
Found time to add it in https://github.com/tsujan/FeatherPad/commit/24381e665c8b46b1b1a185bfa34552944a202207 and https://github.com/tsujan/FeatherPad/commit/23d4dc6b07032d37dbbf5e72a879ca044b55680f. Will enhance it if needed.
