### ISSUE TITLE
[enhancement] one instance option

### ISSUE THREAD

**Issue by pirate486743186** [tsujan/FeatherPad#382]
like the title says. An option to enforce one instance.

**Comment by tsujan** [comment]
FeatherPad has been a single-instance app from day one.

If you mean single window, as far as files are opened from one and the same virtual desktop, no other window will be opened. See Help.

**Comment by pirate486743186** [comment]
if the window is too far offscreen, then a new window is opened. This includes when the window is minimized. The user has no control over this.

**Comment by tsujan** [comment]
That's the expected behavior.

**Comment by pirate486743186** [comment]
I'm saying, to have an option to enforce one window, no matter what.

**Comment by tsujan** [comment]
Opening files in a too off-screen window? To me, that would be a bug, not an option. I've added codes to *fix* it.

**Comment by pirate486743186** [comment]
let me guess, you have a giant programmers screen. I have a small screen. Been crowded is normal on my screen. Half the window, is a significant fraction of the screen. Your feature is a bug down here. On a small screen, it's incredibly annoying.

**Comment by tsujan** [comment]
No, I don't have a giant screen (I would if I had the money).

Having a small screen is one thing (I've used FeatherPad in small virtual screens of VirtualBox), having a habit of making windows off-screen is another.
