### ISSUE TITLE
Why Qt?

### ISSUE THREAD

**Issue by digitalethics** [tsujan/FeatherPad#383]
I'm curious why you ultimately decided to opt for Qt instead of GTK. Could you provide some background to your decision-making?

**Comment by tsujan** [comment]
I've told the story here and there. This is my experience; please don't turn it into a battle between Qt and GTK.

I started FeatherPad in GTK2. In that time, I thought that was the best way I could have started it. Then, GTK3 came out and I saw that my work could be ruined by arbitrary and backward-incompatible changes Gnome devs made to GTK3 or, at least, a lot of time was wasted just to keep it working. Then, I discovered Qt on the coding level (I was quite familiar with it in apps) and saw an enormous difference: GTK -- even GTK2 -- was an obstacle in comparison. So, I rewrote the whole program in C++ and Qt; of course, I mean its preliminary version.

**Comment by digitalethics** [comment]
Thanks a lot for your feedback. I was just curious regarding the engineering decisions behind it. Much appreciated!

**Comment by tsujan** [comment]
You're very welcome.
