### ISSUE TITLE
Convert line endings / breaks

### ISSUE THREAD

**Issue by hansfn** [tsujan/FeatherPad#387]
Since FeatherPad enables you to change the encoding of a file, I also expected to be able to change the line endings. However, I couldn't find any option to do that.

If no such option exist, this is a feature request.

**Comment by tsujan** [comment]
Only Windows end-of-line is supported, although it isn't needed with new versions of Windows anymore. Use "Save with Encoding" (while keeping the encoding if you want to) and this dialog will appear on saving:

![ending](https://user-images.githubusercontent.com/981076/81694375-7ea4c200-9476-11ea-8c27-2029a747ba15.png)

**Comment by hansfn** [comment]
Thx for the quick reply. Some testing shows that FeatherPad auto-converts Windows line endings to Unix when saving - I didn't know. And as you say, if using "Save with Encoding" I can preserve or change to Windows line endings.

This covers my needs so I'm fine with the issue being closed, but I think it would be more user-friendly with an explicit change line ending option/command.

**Comment by tsujan** [comment]
> Some testing shows that FeatherPad auto-converts Windows line endings to Unix when saving

Oh, yes. Unix line-end is the most "natural" one.

> but I think it would be more user-friendly with an explicit change line ending option/command.

Maybe later. Even encoding is a thing of the past, when UTF-8 wasn't universal.
