### ISSUE TITLE
100MB per file size limit as option

### ISSUE THREAD

**Issue by mashiro-tan** [tsujan/FeatherPad#388]
https://github.com/tsujan/FeatherPad/blob/master/featherpad/loading.cpp#L53
Why hardcoded filesize check was added there? Some users (like me) have a huge text files and i think that isn't good to urge them to install another editor without this limitation. If you're aware of the low performance on the old hardware then, probably, will be good to make this limit as enabled by default option. Or let user decide this value by himself (with zero as unlimited size).

**Comment by shlyakpavel** [comment]
Is there a sane reason to open text files over 100mb?

**Comment by tsujan** [comment]
As @shlyakpavel implied, no one is interested in files > 100 MiB for text editing/reading. Files with sizes > 100 MiB may be audio/video/binary... files but not text files anyone wants to read/edit.

I don't need to explain why nothing is unlimited in computing...

**Comment by mashiro-tan** [comment]
@shlyakpavel
>Is there a sane reason to open text files over 100mb?

Yes. I want to look into logs with user-friendly gui, same for the search, for example. And i don't want to install another editor in my mostly pure lxqt system, not that based on GTK and not that kio-dependable ones. Sometimes i have a deal with a large json or csv files, for what i want just do a open_and_look thing, but with this restriction i have to use nano instead. 
Here is the today generated 240MiB sha1sum output opened in the patched Featherpad. 
![screen-2020-05-13-14-34-44](https://user-images.githubusercontent.com/6959472/81808055-d0595500-9527-11ea-92ef-31790e31b618.png)

@tsujan 
>no one is interested in files > 100 MiB for text editing/reading

Why do you think so?

>Files with sizes > 100 MiB may be audio/video/binary...

It will have a different extension and different MIME type from a generic text files. And no one sane person will open these files with a text editor. Moreover, Featherpad by default restricts to open these binary files, but this behaviour may be disabled in preferences. Your judgment just doesn't make sense.

**Comment by shlyakpavel** [comment]
@mashiro-tan
Wow. I have never seen such a huge log-files.
Could you please show the RAM consumption with such files opened? Does the program remain stable? If yes, the reason can be that the syntax highlighting is disabled. 
@tsujan why did you add this limit? Was there any improper behaviour of the app that you/other users faced?

**Comment by tsujan** [comment]
> @tsujan why did you add this limit?

Because, after reading them, the job of showing them is just started ;) Reading of files is usually very fast -- at least, in the way FeatherPad does it -- but showing them with Qt widgets isn't.. Not all files are as simple as @mashiro-tan's example, which is , BTW, very uninteresting. Programs that make huge log files should have their own way of showing them. systemd's journalctl is one example.

Anyway, I won't cover such impractical use cases.

**Comment by mashiro-tan** [comment]
@shlyakpavel 
>Could you please show the RAM consumption with such files opened?

Sure. htop: 1725M virtual, 1263M resident, 55M shared for the sha1 log.

>Does the program remain stable?

Search is working, not blazing, but fast. Scrolling is perfect. Editing causes small hangs (but is somewhat generic for any editor). No crashes.

>If yes, the reason can be that the syntax highlighting is disabled.

It was automatically disabled when file size was around 50mb.

>My 2,5gb RAM VM is used to hang on much smaller file sizes

Well, i have a bunch of RAM + zswap and don't mind about consumption. 

I don't ask remove this limit entirely, if there some fundamental issue with the large files - jusk asking to let user decide, open it at his own risk or not.

**Comment by tsujan** [comment]
> And no one sane person will open these files with a text editor.

I ignore your impoliteness and reply: sometimes, non-text files have interesting readable but hidden info in them. PDF is one example.

**Comment by mashiro-tan** [comment]
@tsujan 
>I ignore your impoliteness

Sorry if I could hurt, did not mean anything like that. 

>non-text files have interesting readable but hidden info in them. PDF is one example.

Bios roms may have any interesting text information too. Or libraries with debug information. But really this is not a valid case for a _text_ editor, and this is what i mean.

Well, no so no.
