### ISSUE TITLE
Match color scheme

### ISSUE THREAD

**Issue by danger89** [tsujan/FeatherPad#389]
I have a dark theme. FeatherPad doesn't adjust to my desktop settings like Firefox and other applications do. I know its Qt, but maybe you have an idea how to improve this?

Regards,
Melroy

**Comment by tsujan** [comment]
Firefox is based on GTK; FeatherPad on Qt. GTK doesn't control Qt and Qt doesn't control GTK.

You need a Qt config app and a dark Qt style. If you're in KDE or LXQt, you already have one and can install and use Kvantum. If you're in a GTK DE, I recommend you ask the question in the forums of your distro or read its documentation.
