### ISSUE TITLE
Combined search&replace like…

### ISSUE THREAD

**Issue by AcarBurak** [tsujan/FeatherPad#39]
Hope you don't get angry, just asking, pointing out: Does combining search/find & replace bloat the code or undesirable? Compare fp and qtcreator implementation:
![fp-search](https://user-images.githubusercontent.com/1426842/27009478-5ab5a066-4e98-11e7-8533-c8e6e5c9ce3d.png)
![qtc-search](https://user-images.githubusercontent.com/1426842/27009479-5abaaf52-4e98-11e7-8dc7-1ea4c29e5a33.png)

With qtcreator Control+F brings everything to bottom, with feather one needs another hotkey Control+R. Besides, toggling Control+R, removes Replace pane but keeps Search pane despite it hasn't been opened initially.

**Comment by tsujan** [comment]
> Hope you don't get angry, just asking...

Quite conversely, I'm glad to know about your ideas.

These are the reasons why I made search and replace *almost* separate from each other:

(1) Search is much more needed/used/important than replacement is.
(2) There's no harm in searching something while wrong replacement can be dangerous. So, search and replacement should be separate from each other graphically.
(3) Mixed GUIs have always been confusing to me; I never wanted to implement them in FeatherPad.
(4) For usability reasons, each tab has its own search bar (although they all seem like a single bar) but there's only one replacement bar for all tabs. So, they're structurally different too.

Anyhow, they aren't completely separate either: replacement follows the search settings and you couldn't show the replacement bar without showing the search bar.

**Comment by AcarBurak** [comment]
Thank you. All fair points.
