### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by beepollen** [tsujan/FeatherPad#392]
Well, first of all,  thank you for making this editor for the linux community.
I don't have any problems using FeatherPad.
I just would like to make a suggestion:
To add, if possible, a button to play ambient noise (restaurant, beach waves, etc...)
And a distraction free mode, like we see in other foss editors (the F11 shows the menu bar...).
Once again, thank you, I love this editor.

**Comment by tsujan** [comment]
> To add, if possible, a button to play ambient noise

A text editor that plays sound is as funny as a media player that edits text. Such a fun has costs that a lightweight app can't afford — to say nothing of the Unix philosophy ("Write programs that do one thing and do it well").

> And a distraction free mode

Preferences → Do not show toolbar/manubar, etc.
