### ISSUE TITLE
toolbar icons cannot display

### ISSUE THREAD

**Issue by yochenhsieh** [tsujan/FeatherPad#4]
build & install successfully. But the toolbar icons cannot display:
http://imgur.com/a/aheuq

**Comment by tsujan** [comment]
The icons are SVG. Do you have libqt5svg5 installed?

**Comment by tsujan** [comment]
More important than that: do you use a DE with a Qt5 plugin or config tool?

**Comment by yochenhsieh** [comment]
Mm, I should add libqt5svg5 as requirement. I'm packaging a rpm for Mageia, will import it to repository.

I use lxde to test if it's really DE-independent. Thanks.:-)

**Comment by tsujan** [comment]
That's my fault. I should have explained it in `INSTALL`, although `libqt5svg5` isn't a build dependency.

So, are all icons shown when `libqt5svg5` is installed?

I'll add an option for choosing between own and syste icons soon.

**Comment by yochenhsieh** [comment]
Yes, all icons show after libqt5svg5 installed. Mention it in `INSTALL` is a good idea.

**Comment by tsujan** [comment]
Added explanation about `libqt5svg5` in `INSTALL`. Also `g++` was another dependency I'd taken for granted. All done as a part of https://github.com/tsujan/FeatherPad/commit/3a8679461d2bd41a91cc36f5046c36f3ebbb5ff9

**Comment by tsujan** [comment]
This SVG problem reminded me of a memory leak that I'd fixed offline a long time ago but forgotten to fix online. It's fixed now. Please update to the latest GitHub version!
