### ISSUE TITLE
fpwin.cpp:2350: possible wrong operator ?

### ISSUE THREAD

**Issue by dcb314** [tsujan/FeatherPad#40]
../../featherpad/fpwin.cpp:2350]: (style) Boolean result is used in bitwise operation. Clarify expression with parentheses.

Source code is

    ui->actionCut->setEnabled (!readOnly & textIsSelected);
    ui->actionDelete->setEnabled (!readOnly & textIsSelected);

Maybe you meant &&, not &.

**Comment by tsujan** [comment]
Thank you! `&` is my mistake. I wonder how you could find it ;)

I'll fix it with the next commit (for bash syntax highlighting -- which is a real mess in its current state).

**Comment by dcb314** [comment]
I used a static analyser for C and C++ called cppcheck.

I find it very useful. It is available from sourceforge.

**Comment by tsujan** [comment]
OK. Please tell me if you find another mistake! Thanks in advance!

**Comment by dcb314** [comment]
Since you asked:

[../../featherpad/config.cpp:23]: (warning) Member variable 'Config::curRecentFilesNumber_' is not initialized in the constructor.
[../../featherpad/tabbar.cpp:29]: (warning) Member variable 'TabBar::dragStarted_' is not initialized in the constructor.

**Comment by tsujan** [comment]
They cause no problem but yes, it's better to initialize them in the c-tor. Added to fixes.

**Comment by tsujan** [comment]
All fixed.
