### ISSUE TITLE
feature request: compare selected text

### ISSUE THREAD

**Issue by prrvchr** [tsujan/FeatherPad#400]
First of all, congratulations FeatherPad it's really great ...

I would dream of having the possibility of easily comparing two different sections of text ...

For example a section that I previously copied to the clipboard with the current selection, may be in a new document opened for this purpose... or any other way, as long as we can compare two different sections of text like linediff for vim...
Thank you anyway

**Comment by tsujan** [comment]
You mean a visual diff app.

I'm afraid that's both beyond my time and beyond what FeatherPad is designed to be, namely, a lightweight text editor.

I prefer to focus on making the current functionalities better (for example, better syntax highlighting for some languages) and adding some others that are related to them (like selection highlighting, [proposed by](https://github.com/tsujan/FeatherPad/pull/398) @urnenfeld).
