### ISSUE TITLE
Feature Request: Completely hide toolbar/menubar

### ISSUE THREAD

**Issue by BreakfastSerial** [tsujan/FeatherPad#401]
I'd love to be able to hide the toolbar and the menubar.

I use featherpad as my daily scratchpad and this would make it more minimalistic and visually pleasing.
There should be a right-click context menu option to enable the menubar again.

**Comment by tsujan** [comment]
I'm afraid, hiding both toolbar and menubar isn't practical. As for minimalism, it may be good as far as it doesn't render the app useless -- as it does in Gnome.
