### ISSUE TITLE
Feature Request: Hide file path in window title

### ISSUE THREAD

**Issue by BreakfastSerial** [tsujan/FeatherPad#402]
FeatherPad shows the complete file path and the file name in the window title.
I'd love to see an option to reduce this to only the file name.

**Comment by tsujan** [comment]
> I'd love to see an option to reduce this to only the file name.

It was only the file name in very old versions but the full path was requested.

I don't add options for such minor things because, as much as I hate Gnome's exaggerated minimalism, I don't like KDE's bloated config dialogs either.
