### ISSUE TITLE
I'm just wondering if this naming is confusing

### ISSUE THREAD

**Issue by shlyakpavel** [tsujan/FeatherPad#406]
https://github.com/tsujan/FeatherPad/blob/60c9e7477b7b715c25e93da02dc9ef9248479500/featherpad/highlighter-css.cpp#L100
https://github.com/tsujan/FeatherPad/blob/60c9e7477b7b715c25e93da02dc9ef9248479500/featherpad/highlighter.h#L159
Could you please check if the argument order is correct? In case it is, a comment would be a real 'nice-to-have'
Have a nice day!

**Comment by tsujan** [comment]
Yes, it's correct. For a start comment sign to be *invalid*, it should not be inside a value (although that value may have a structure similar to that of an attributor selector) but inside an attributor selector. Example:

FeatherPad:

![fpad](https://user-images.githubusercontent.com/981076/87208029-bd45e400-c322-11ea-9690-1c097b130ff8.png)

Kate:

![kate](https://user-images.githubusercontent.com/981076/87208041-c3d45b80-c322-11ea-802a-c057df09dc88.png)

**Comment by tsujan** [comment]
Dev to dev:

All FeatherPad codes about syntax highlighting are results of my curiosity to know whether Qt's syntax highlighter is enough for an acceptable syntax highlighting. I think most devs may say, "No!" But, IMO, I've proved -- sometimes with headache -- that it is good enough. At some point, I might make and use a different class and get rid of the headache but I'm still not convinced that it won't give me a bigger headache.

**Comment by shlyakpavel** [comment]
It would be still nice to have a small comment in the code explaining this
