### ISSUE TITLE
Accelerator displayed as Rep&lacement is unusable

### ISSUE THREAD

**Issue by stefonarch** [tsujan/FeatherPad#411]
![schermata-26-13-41-54](https://user-images.githubusercontent.com/10681413/91388982-b9b9de00-e838-11ea-9349-a378f709a99c.png)
Also in translations, see picture.
There are 4 files concerned, see links [here](http://135.181.85.100/translate/tsujan/featherpad/it/?checksum=61eb44b439abdf3&q=sostituzione&sort_by=-priority%2Cposition) on the right.

**Comment by tsujan** [comment]
You mean the accelerator. Yes, I know :) Its story is that, years ago, I added `&` by mistake and, after a while, it was translated into several languages and I didn't have time to correct it everywhere. Later, I just forgot it. Fortunately, it's harmless.

Please don't remove it in your translation(s). I'll remove it everywhere later — this page will serve as a reminder. Thanks!

**Comment by tsujan** [comment]
The interesting thing is that Kvantum and Breeze don't show `&`; Fusion does. That's another reason why I forgot it.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/600a268d59fdaad41bff41597bb0000af504a0be

All translations are also corrected.
