### ISSUE TITLE
Configure word characters

### ISSUE THREAD

**Issue by oonet** [tsujan/FeatherPad#420]
Configure characters to be included in double-click select word.

**Comment by tsujan** [comment]
They are always whole words. "Whole word" is a standard concept in text editing as well as in regex..

However, a setting for including some extra characters may be good. I'll think about it.

**Comment by tsujan** [comment]
Last night, I not only thought about it but also wrote its code to test it. I'm afraid it was too weird.

As I mentioned above, "word" is a standard concept. As a regular expression, it's defined as `[a-zA-Z0-9_]+`.

By "standard", I don't mean "usual" — the word "standard" may be abused to mean "what I'm accustomed to". Here, we're dealing with a *real* standard that shouldn't be violated by a text editor.
