### ISSUE TITLE
Feature request: Obviously FeatherPad should not spellcheck URLs

### ISSUE THREAD

**Issue by Yekutiel** [tsujan/FeatherPad#422]
Obviously FeatherPad should not spellcheck URLs

I don't remember ever using a spellchecker that checked the spelling of URLs. That is inane.

Hey. 1995 just called and wants it's non-internet aware spell checkers back!

**Comment by tsujan** [comment]
"Obviously" you could skip URLs and other things in the Spell Checking dialog. There are many things besides URLs that don't need spell checking. That's called logic (→ ~ 300 BC).

**Comment by Yekutiel** [comment]
I guess maybe English is not your native language. Therefore, pou probably misunderstood me.

None of the spellcheckers in English that I have used for the last twenty years, spellcheck URLs.

In other words, spellcheckers normally ignore any string that contains "http" or "www". 

Here's an example. Try spellchecking it in, for example, Gmail or Google Docs. Then try spellchecking it in feather.

https://www.google.com/search?q=logic&safe=active&sxsrf=ALeKk01vDKXt1LoJPpnkuhnWdPoFHHN3sw:1600907073266&source=lnms&tbm=isch&sa=X&ved=2ahUKEwj5ja7Lw4DsAhXSs54KHY7WCr4Q_AUoAnoECB0QBA&biw=1280&bih=624&dpr=1.5

Your purported "logic" is illogical.

**Comment by tsujan** [comment]
There is a difference between an inline spell checker and spell checking with a dialog that can start spell checking from the cursor position.

From [your other report](https://github.com/tsujan/FeatherPad/issues/423), it seems that you don't want to check any option in Preferences.
