### ISSUE TITLE
Feature request: Use Ctrl+W to close a window

### ISSUE THREAD

**Issue by Yekutiel** [tsujan/FeatherPad#423]
I would like to use Ctrl+W to close a window instead of Ctrl+Shift+Q.

For regular users like me, Ctrl+W is the standard way we use a keyboard to close a window. Sure, VIM uses Ctrl+Shift+W but that's not what regular users like me use.

**Comment by tsujan** [comment]
Preferences → Shortcuts

**Comment by Yekutiel** [comment]
Thanks Tsujan! 

When FeatherPad opens the first three times it should display a message such as, 

"You can change the keyboard shortcuts by going to Preferences → Shortcuts. For example, by going to Preferences → Shortcuts you could change 'Close' to 'Ctrl+W' . This message will display the first three times you open FeatherPad; after that it won't appear."

**Comment by tsujan** [comment]
> When FeatherPad opens the first three times it should display a message such as,

What?! Everyone knows what a Preferences dialog is for and everyone can see the "Shortcuts" tab there.

**Comment by Yekutiel** [comment]
>> What?! Everyone knows what a Preferences dialog is for and everyone can see the "Shortcuts" tab there.

Ummm. Yeah. Look. Mr Super Genius Dictator. When you start introducing non-standard approaches into ordinary software such as a text editor the onus is on you to explain yourself. 

Most software does not allow users to edit keyboard shortcuts.

Ctrl+W is standard. If you choose to change it then you need to explain yourself.

**Comment by tsujan** [comment]
It was a while that I hadn't encountered narcissistically written comments.

**Comment by Yekutiel** [comment]
Let me see, tsujan knows more than the folks at Google who designed Gmail and Google Docs about spellchecking in English. Look Mr. Arrogant Non-Native Speaker of English. Put simply: their approach (the standard approach) is better than yours for ordinary users spellchecking ordinary documents in English.

You seem like a typical self-centered open source developer who thinks "I am always right" and has contempt for ordinary users and their reasonable suggestions.

**Comment by tsujan** [comment]
@Yekutiel, this is *my* app and I don't owe anything to anyone. I've shared it with others; they're free to use or ignore it. There's no need to a high IQ to understand that.

**Comment by Yekutiel** [comment]
Did you notice the following on Wikipedia?

> https://en.wikipedia.org/wiki/FeatherPad#Reception
> 
> It also praised its extensive, **if non-standard keyboard shortcuts**, noting, "the keyboard shortcuts are all nicely explained in the menus, however, and, once learned, FeatherPad becomes very fast to use.

The phrase **if non-standard keyboard shortcuts** is a polite way of saying, "The default keyboard shortcuts should be changed to conform with standards."

**Comment by Yekutiel** [comment]
> is _my_ app and I don't owe anything to anyone. I've shared it with others; they're free to use or ignore it. There's no need to a high IQ to understand that.

First of all, FeatherPad is not your app. FeatherPad is open source.

You are clearly a typical self-centered open source developer who thinks "I am always right." In other words, you don't bother to allow pesky things like facts get in the way of your foolish opinions.

**Comment by tsujan** [comment]
> Did you notice the following on Wikipedia?

LOL! I know the writer of the Wikipedia article and have a deep respect for him.

> First of all, FeatherPad is not your app. FeatherPad is open source.

?!

> You are clearly a typical self-centered open source developer...

OK, please stop mistaking a bug tracker for a place for group therapy! I don't have time for psychology.

**Comment by Yekutiel** [comment]
> LOL! I know the writer of the Wikipedia article and have a deep respect for him.

You claim you deeply respect for the Wikipedia article yet you are ignoring his implicit suggestion that, "The default keyboard shortcuts should be changed to conform with standards."

I suppose in your mind up is down; left is right; good is bad. Right?

**Comment by shlyakpavel** [comment]
> I suppose in your mind up is down; left is right; good is bad. Right?

Just shut the fuck up and get outta here

**Comment by Yekutiel** [comment]
Kindness, humility, and open-mindedness are three qualities that most people like to find in others. 

If it ever seems to you that "the world is against you" then remember this: no one likes dealing with a nasty, arrogant, and ignorant person. I suppose that many people go out of their way to make life difficult for you because they dislike you. 

As for me, I've gone back to using LibreWriter. It's not as light and nimble as FeatherPad, but it follows many standard conventions that FeatherPad does not.

**Comment by tsujan** [comment]
> Kindness, humility, and open-mindedness are three qualities that most people like to find in others.

What you need is just a little common sense. Your delirium is phenomenal.
