### ISSUE TITLE
Search bar shown when doing replace

### ISSUE THREAD

**Issue by karabaja4** [tsujan/FeatherPad#424]
Hello, I'm wondering is this is a bug or not, seems like it is.

When I use the replace functionality, a search bar is opened together with the replace bar.

When I execute the replace, and close the replace bar, the search bar stays open and I have to press Ctrl+F twice to close it. Seems a bit strange.

Regards,

Igor

**Comment by tsujan** [comment]
Hello,

No, it isn't  a bug. The replacement is done by using the state of "Match Case", "Whole Word", and "Search in all nodes", whose buttons are on the search bar (I may also make replacement follow the state of the other two radio buttons). Therefore, the search bar should be shown when a replacement is done.
