### ISSUE TITLE
Hit Esc to exit Ctrl+F search

### ISSUE THREAD

**Issue by KloudKoder** [tsujan/FeatherPad#431]
The only thing I find annoying about FeatherPad is that when I Ctrl+F to search for something, I can't hit Esc. Ideally, the first Esc would clear the search input field, so that some other search term can be entered. Then the second Esc would return to the editing context. The way things are now, you need to reach over to your mouse constantly, just to click in the editing window so that you can exit the search context.

There is also the issue of where the editing context should be after a search. Should it be at the beginning of a found word, at the end of a found word, or in the same place as before the search occurred. I kind of thing the last case makes the most sense, but it's not a big deal.

**Comment by tsujan** [comment]
> Ideally, the first Esc would clear the search input field

`Ctr+K` is shown as the tooltip of the clear button. It's also mentioned in Help.

> The way things are now, you need to reach over to your mouse constantly

Not true. Press Tab when the search-bar has focus. Tab and Backtap are well known for changing the focus of widgets that don't consume them.

> where the editing context should be after a search

If by "editing context" you mean the cursor, it selects the found word. That's the most practical behavior.

**Comment by KloudKoder** [comment]
@tsujan Unfortunately, I can't get your fix until it shows up in the Ubuntu store. I don't know how often they push new revisions. But thanks for addressing this.

So if I understand you correctly, once your fix gets out in the wild, then you can clear the search bar with Ctrl+K, and then return to the editor with Esc?

**Comment by tsujan** [comment]
> So if I understand you correctly, once your fix gets out in the wild, then you can clear the search bar with Ctrl+K, and then return to the editor with Esc?

Yes, but more than that: With `Esc`, you could return to the editor *from anywhere and without changing anything*.

>  I can't get your fix until it shows up in the Ubuntu store

I don't know when it'll be packaged for Ubuntu users but I'll release 0.16.0 within a few weeks.

**Comment by tsujan** [comment]
BTW, I added the info to Help doc.
