### ISSUE TITLE
We need an option to not record history

### ISSUE THREAD

**Issue by KloudKoder** [tsujan/FeatherPad#432]
@tsujan Regarding the history modified files: recording this history to disk expands the security surface (although with the right config file permissions, it's at least theoretically safe). But in general, one of the great advantages of "dumb" text editors is that they forget all about what was edited once they're closed. It would be very helpful if we could opt out of this history.

The options could be: (1) all recently opened, (2) all recently modified, or (3) none.

I don't mind if the status quo is the default. I just want to be able to change it. I can't seem to find a setting that does this.

(Edited to correct some wrong assertions.)

**Comment by tsujan** [comment]
Oh, that can be easily implemented by allowing 0 for "Number of recent files" — without cluttering the GUI. I thought that a minimum of 1 would be enough but, OK, I'll change it to 0.

**Comment by tsujan** [comment]
Done cleanly in https://github.com/tsujan/FeatherPad/commit/87c6e924a53c51fe7932f00f1ed3b4ed478d2551

It was a good idea; I wonder why it hadn't occurred to me. Thanks for your report!

**Comment by KloudKoder** [comment]
@tsujan Thanks for the fixes! I look forward to getting the updated package when it's available.
