### ISSUE TITLE
enhancement "detection of text encoding"

### ISSUE THREAD

**Issue by Golddouble** [tsujan/FeatherPad#436]
I have read in the feature overview:

> Automatic detection of text encoding as far as possible and optional saving with encoding;

This works not with this file:
[wrong default coding.txt](https://github.com/tsujan/FeatherPad/files/5437453/wrong.default.coding.txt)

Have a look at line 23:
how it looks:
` - Autorun-Menь das auf die Ressourcen dieser CD verweist`

How it should look:
` - Autorun-Menü das auf die Ressourcen dieser CD verweist`

The reason is, that featherpad does open it by default with CP1251 instead of ISO-8859.

Maybe you can enhance dedecting the right coding?

**Comment by tsujan** [comment]
It says, "... as far as possible."

Encoding detection doesn't have an exact method and isn't possible for all cases. You make it work better in some cases and it might work worse in others. I have text samples that are opened correctly in FeatherPad but are shown as scrambled texts in Kate. Apparently, Kate's emphasis has been on European languages, while I've tried to detect Arabic too, etc.

I'll take a look at the code again, considering your sample — but no promise. It's simply not worth the effort; UTF-8 is the standard everywhere....

**Comment by Golddouble** [comment]
Thank you.

**Comment by tsujan** [comment]
I added the commit https://github.com/tsujan/FeatherPad/commit/be8925ce476186e8dbe2b83949a4c76a7602f49e, which covers your example, while still shows my samples correctly.

Please note that you might encounter wrong detections again. As is mentioned in https://wiki.qt.io/Basics_of_String_Encoding:

"It is not possible to accurately determine the encoding for an array of bytes. The encoding of bytes needs to be known from some external source to correctly interpret them."

However, you could attach them here. Who knows? The heuristic method might be improved a little by considering them.

Thanks for the report!

**Comment by Golddouble** [comment]
Thank you. I appreciate it.
