### ISSUE TITLE
It is recommended that you add syntax highlighting for the Nim language.

### ISSUE THREAD

**Issue by lihf8515** [tsujan/FeatherPad#447]
It is recommended that you add syntax highlighting for the Nim language, which has a similar syntax to Python, but with some differences. Without this syntax highlighting, it's inconvenient to write code. I found the highlight of 'Featherpad' to be fixed. This would be perfect if you could use configuration files. It is also easy for users to extend themselves.

**Comment by tsujan** [comment]
> It is recommended that you add syntax highlighting for the Nim language

I'll do it if it's worth the effort -- don't want to add all languages of the coding world to FeatherPad ("... a lightweight Qt plain-text editor..."). Will add a comment here when I reach a decision.

> This would be perfect if you could use configuration files

Already suggested and rejected (I've explained why but don't have time to find the reports -- sorry).

Thanks for your comment!

**Comment by tsujan** [comment]
Closing because Nim isn't among the common programming languages that I want to support in FeatherPad. I think the 30 syntaxes that are supported are more than enough.
