### ISSUE TITLE
ITP opend

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#45]
Fyi, i created an ITP for FeatherPad - https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=869730

**Comment by tsujan** [comment]
Great! More responsibility for me ;)

**Comment by stevenpusser** [comment]
Hey!  I made some packages for it on the OBS about the same time, too:  https://build.opensuse.org/package/show/home:stevenpusser:kvantum/featherpad

Despite the notes saying it requires g++ >= 5, it builds and runs fine with Jessie's 4.9 and Qt 5.3.

https://build.opensuse.org/package/show/home:stevenpusser:kvantum/featherpad

Feathernotes seem to need a newer Qt 5 than that, though. The Jessie builds failed, so I disabled them:

https://build.opensuse.org/package/show/home:stevenpusser:kvantum/feathernotes

**Comment by tsujan** [comment]
> Feathernotes seem to need a newer Qt 5 than that, though. The Jessie builds failed, so I disabled them

Strange! I thought if one of them needed newer gcc/Qt, it would be FeatherPad because there are C++11 "lambdas" in it.

**Comment by tsujan** [comment]
I had a question about Debian Stable: When will it be equipped with c++11? With the next Ubuntu LTS?

**Comment by agaida** [comment]
debian has nothing to do with Ubuntu in that regard - and the answer is: never, it might landing in backports

**Comment by tsujan** [comment]
> and the answer is: never, it might landing in backports

That doesn't seem possible to me! At some point, c++11 *should* go into Debian Stable. I just wanted to have a rough timing to equip Kvantum with c++11 because it has Debian Stable users but I can't wait for Debian Stable forever ;) -- backward compatibility is hard to maintain. Ubuntu LTS will have it in 2018.

**Comment by tsujan** [comment]
> current stable should have no problems with c++11

A Stable user told me he couldn't compile Kvantum and I found out that was because of some c++11 lines.

**Comment by agaida** [comment]
we build with Sid and c++11 last year - didn't we? - so thats the same what is released as stable - i mentioned current aka Stretch?

**Comment by tsujan** [comment]
Oh, you're right! That user should have had old stable and who wants to support old stable?! Thank you!

**Comment by agaida** [comment]
The problem is that there are nearly three years in development between the releases - if we add freeze to the time between the releases.

**Comment by stevenpusser** [comment]
As far as I can tell, Jessie's gcc-4.9 has no problems with the c++11 standard.  Maybe you are thinking of c++14, which indeed needs gcc >= 5?

**Comment by tsujan** [comment]
> As far as I can tell, Jessie's gcc-4.9 has no problems with the c++11 standard

Mostly yes but that old gcc fails when some features of c++11 are used. For example, it doesn't understand something like this:
```cpp
template <typename T> using KvPointer = QPointer<T>;
```
