### ISSUE TITLE
Bug: printing: "reverse" function

### ISSUE THREAD

**Issue by Golddouble** [tsujan/FeatherPad#455]
The "reverse function" does not work.

When I try to print pages 4 to 8 together with the checked "reverse" function it does not reverse the pages. I get the same result  as when I would not check the "reverse" option:
![Featherpad, print, reverse](https://user-images.githubusercontent.com/13977359/99881853-7b0ba800-2c1c-11eb-8719-7cf85a36a76c.png)

Featherpad version 0.16.0
MX Linux 19.3 (Debian 10 based)
Xfce 4.14.2

Thank you for testing.

**Comment by tsujan** [comment]
FeatherPad has no control over the print process. It only calls Qt's print dialog; the rest is done by Qt and CUPS.

Moreover, I can't see a difference between FeatherPad and Kate when the Reverse box is checked with PDF. Neither I can see any difference when odd/even pages are supposed to be printed to PDF. Maybe printing to PDF doesn't support these properties or there's a bug in Qt/CUPS.

**Comment by Golddouble** [comment]
> Maybe printing to PDF doesn't support these properties or there's a bug in Qt/CUPS.

It's the same, when I try this with my HP ink printer.

**Comment by tsujan** [comment]
> It's the same, when I try this with my HP ink printer instead of the PDF printer.

I found this report but it isn't what you see: https://bugreports.qt.io/browse/QTBUG-84016

I checked Kate again and the result was the same: no reverse order. Then, I checked Qt Creator and was surprised: the reverse order worked! How Qt Creator does the trick, I don't know yet but there is something different in its printed PDF.

Because of that, I re-open this report to investigate it thoroughly. Will tell you about the result.

**Comment by tsujan** [comment]
OK, I investigated it. This is 100% a Qt issue:

I read some Qt source files and found out that the reverse order in disabled in `QTextDocument::print`. Why? I don't know.

However, I succeeded in importing `QTextDocument::print` to FeatherPad and enabling the reverse order in it. After that, the Reverse button really worked :) I think Qt Creator uses a similar workaround.

I should test the code for a while, before adding a commit.

**Comment by Golddouble** [comment]
Thank you for this interesting report.

So it's not a CUPS-issue, but a QT-issue? Or is this the same?

**Comment by tsujan** [comment]
> So it's not a CUPS-issue, but a QT-issue? Or is this the same?

It's definitely a Qt issue -- I'm looking at the problem in Qt source, right in front of me.

I also downloaded the source of Qt Creator minutes ago and saw that its workaround is exactly like what I did :)

I really don't understand why Qt developers should disable the reverse order in Qt — it's so weird — but, now, we have a safe workaround.

Thank you for making me look into the problem! While most Qt apps don't support the reverse order printing, FeatherPad will soon, thanks to your report.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/2fae0dcbc612a3b7ebbab398afcab4c2fcb039b3

Now, not only Qt's reverse printing bug is avoided but also documents can be printed correctly with the dark color scheme (previously, another Qt bug didn't allow that).

**Comment by Golddouble** [comment]
Yes. I use Featherpath's dark mode and I already run into this "printing in dark mode" issue. But I have never reported this until now. Thank you.

**Comment by tsujan** [comment]
> I already run into this "printing in dark mode" issue. But I have never reported this until now.

It was reported and I'd replied that it's impossible with what's available in `QPlaineTextEdit`. But now, that the printing code is imported, several things became possible..

Yet another problem that's fixed is the color of line-end symbols in the printed PDF (when showing of line/document ends is enabled in Preferences). They're fine now.

> Is this also a disabled QT-feature that is disabled in QT?

Yes, for a reason unknown to me, it's intentionally disabled in Qt's code. Programs like FeatherPad and Qt Creator, that want it back, should include the printing code completely. The irony is that Qt Creator is made by the Qt team!
