### ISSUE TITLE
Add option to highlight current line

### ISSUE THREAD

**Issue by adjamhub** [tsujan/FeatherPad#459]
Title says it all. Would be nice to have.

**Comment by tsujan** [comment]
Current line highlight has existed from day one and is customizable in the latest release. It shows up when line numbers are shown (as is mentioned in a tooltip).

**Comment by adjamhub** [comment]
Sorry, I couldn't find that option because I don't like having line numbers shown. Now I see it. Do you think I can provide a patch to decouple it from the line numbers feature?

**Comment by tsujan** [comment]
> I don't like having line numbers shown.

Then you won't see any line highlight, as mentioned above.

> Do you think I can provide a patch to decouple it from the line numbers feature?

No, it's so by design.If the user doesn't like line numbers, he/she isn't interested in lines.
