### ISSUE TITLE
translation in Bulgarian

### ISSUE THREAD

**Issue by mkkDr2010** [tsujan/FeatherPad#461]
I have finished the translation of featherpad in Bulgarian. If that issue is an interest for you, point me how to upload the .ts file. I read in Install instructions about a Pull request in git, but I couldn't initiate one.

**Comment by tsujan** [comment]
> I have finished the translation of featherpad in Bulgarian.

Thank you very much! Your work is very appreciated.

> how to upload the .ts file

You could make a PR (Pull Request) but if you don't have time to experiment with PRs, you could also use Weblate. @stefonarch has included FeatherPad in Weblate.

**Comment by tsujan** [comment]
As the last resort, you could also attach the zipped .ts file to a comment of yours here. I could merge it manually, although that's unusual.

**Comment by mkkDr2010** [comment]
I prefer to use Webplate, but when I tried to upload the file, there is massage that I have not the right privileges. The Upload is not possible

**Comment by tsujan** [comment]
The untranslated `bg` file is now added to Weblate.

**Comment by stefonarch** [comment]
Is "tsujan" among your projects? The permissions should be the same for all 4 projects.
At which exact moment do you get the messages? With my test user I can choose the file and select

>  Add as translation
> Add as suggestion
> Add as translation needing edit 

but didn't test further.

**Comment by stefonarch** [comment]
BTW looking into the options (settings → file tab) I see different settings for adding a new language, one of them is
* contact Maintainer

**Comment by mkkDr2010** [comment]
I uploaded the file and made last check. All functions are working fluently.


Am Dienstag, Dezember 8, 2020, 5:26 PM schrieb Standreas <notifications@github.com>:




BTW looking into the options (settings → file tab) I see different settings for adding a new language, one of them is
   
   - contact Maintainer
