### ISSUE TITLE
Unwanted mouse events

### ISSUE THREAD

**Issue by Peter2121** [tsujan/FeatherPad#468]
Hi!

I use FeatherPad 0.14.2 (built with Qt 5.15) installed from FreeBSD ports under WM Enlightenment 0.24.2 and EFL 1.25.1 on FreeBSD 12.1. I have a mouse with additional buttons (wheel-left and wheel-right). I bound these buttons in Enlightenment to some WM actions.

The mappings work correctly in Enlightenment. The problem is that these events are ALSO processed by FeatherPad. For example, if I click 'wheel-right' - I have an Enlightenment action AND the FeatherPad scrolls right. I don't want it. I don't want that the mouse events processed by Enlightenment would be propagated to FeatherPad windows.

I tested the events propagation with xev - it does NOT see the events, so Enlightenment does not propagate them to the underlying windows, so it is NOT the problem of the WM. I don't understand how does FeatherPad get the events, but it should NOT get them like this - it it the responsibility of WM - to propagate or _not_ input events to applications. I suppose that there is a parameter that can change the behavior at the level of Qt, but my experience in this library is really limited, so I cannot find the correct option.

Please, fix this problem.

**Comment by tsujan** [comment]
> so Enlightenment does not propagate them to the underlying windows,

On the contrary, if the wheel events weren't propagated, they wouldn't be received by the app. FeatherPad doesn't do magic.

> Please, fix this problem.

I'm afraid I can't fix a problem in Enlightenment.

> I use FeatherPad 0.14.2

Very old and not supported but that isn't related to your problem.

**Comment by Peter2121** [comment]
>
> I'm afraid I can't fix a problem in Enlightenment.
>

The answer of Enlightenment developers after I sent them xev logs:

_It's not a problem with e. it's the **app/toolkit that is bypassing the regular input pipeline** and going directly to the xinput device and listening to it directly no matter what. the xinput extensions allows this.
you would find almost all wm's would be affected by this (or anything that grabs buttons passively for bindings as has been the case in x for 30 years). they are bypassing this flow and NOT respecting having lost focus due to a grab._

**Comment by tsujan** [comment]
> it's the app/toolkit that is bypassing the regular input pipeline

The app is FeatherPad and it doesn't bypass anything.

The toolkit is Qt and E has proven to have several problems with it. I can't "fix" E's problems with Qt.

I'm not here to defend Qt. You could also say that Qt has problem with E. That's an issue that Qt and E developers might need to discuss between themselves. Obviously, it isn't *my* problem.

**Comment by Peter2121** [comment]
> The toolkit is Qt and E has proven to have several problems with it. I can't "fix" E's problems with Qt.

Just BTW, I use E on everyday basis, 12+ hours per day, and I've never seen any problem with Qt (I reported you the first one I've seen). 

If you can share any information about problems of Qt in E _that should be fixed in E_ - you are welcome, I'll route the information to E developers.

**Comment by tsujan** [comment]
> Just BTW, I use E on everyday basis, 12+ hours per day, and I've never seen any problem with Qt

Please don't get me wrong! First, I like E; second, I know that Qt has many bugs, especially regarding X11. I've tried E many times for more than 8 years but it has always showed intolerable peculiarities (with or without Qt apps) that I can't find in other DEs. Sorry, I don't have time to explain them.

Actually, even if I had time, I wouldn't be motivated to tell E's devs about them. Reactions like what you quoted above aren't new to me.

All in all, what you reported was about E and Qt, not about FeatherPad.
