### ISSUE TITLE
make Error: ‘class QFontMetrics’ has no member named ‘horizontalAdvance’

### ISSUE THREAD

**Issue by CodexForster** [tsujan/FeatherPad#469]
I followed the cmake installation instructions in your install file in your repo after installing the required dependencies. After running cmake .. and then make, I get the following error:
`error: ‘class QFontMetrics’ has no member named ‘horizontalAdvance’
         painter->drawText(qRound (pageNumberPos.x() - painter->fontMetrics().horizontalAdvance (pageString)),
                                                                              ^~~~~~~~~~~~~~~~~
featherpad/CMakeFiles/featherpad.dir/build.make:421: recipe for target 'featherpad/CMakeFiles/featherpad.dir/printing.cpp.o' failed
make[2]: *** [featherpad/CMakeFiles/featherpad.dir/printing.cpp.o] Error 1
CMakeFiles/Makefile2:130: recipe for target 'featherpad/CMakeFiles/featherpad.dir/all' failed
make[1]: *** [featherpad/CMakeFiles/featherpad.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by tsujan** [comment]
You have a very old version of Qt (< 5.11); don't you? I'm afraid supporting very old Qt versions isn't practical and can cause complex problems.

The latest git code isn't for Qt < 5.12. I should bump `QT_MINIMUM_VERSION` in `CMakeLists.txt`. Will close this page when it's done.

Thanks for the report!

**Comment by CodexForster** [comment]
Yes, my Qt version is less than 5.11. You should include a minimum version in the INSTALL file because I just did a get-apt install line and then continued with the CMake installation.
Thanks!

**Comment by CodexForster** [comment]
On a side note, my synaptic package AND apt-get shows that the latest version is 5.9.5. How do I get some version above that?

**Comment by CodexForster** [comment]
Ok, I am not sure of what I found. But on the synaptic package, I found featherpad already present. All I had to do was mark for installation and then install. Isn't this easier than the cmake/qmake install? It's fast and simple.

**Comment by tsujan** [comment]
> You should include a minimum version in the INSTALL

It is in `CMakeLists.txt` and I should change it for git as well as the next release. `CMakeLists.txt` is the correct place; Qt itself will use cmake in its version 6.

> On a side note, my synaptic package AND apt-get shows that the latest version is 5.9.5

If you mean FeatherPad, the latest release is [0.16.0](https://github.com/tsujan/FeatherPad/releases/tag/V0.16.0) but 0.17.0 will come soon. 5.X.Y is a relic of very old times.

If you mean Qt, the latest release is 5.15.2, which is LTS. The previous LTS was 5.12, which will be supported by FeatherPad 0.17.0.

I think you might be able to compile 0.16.0 with your installed Qt version; it's worth a try. I don't support previous versions but 0.16.0 is *much better* than what you may found with apt.

**Comment by CodexForster** [comment]
Ok thanks, I will try the 0.16.0 version.
But if you do not mind could you tell me how do I download Qt (>5.11)?

**Comment by tsujan** [comment]
> Isn't this easier than the cmake/qmake install? It's fast and simple.

Yes, of course, installing with the package manager is the best method. But, unfortunately, FeatherPad's Debian maintainer stopped his work (for an unknown reason) and there's no new maintainer yet. As a result, Debian's FeatherPad version is outdated.

> could you tell me how do I download Qt (>5.11)?

I recommend you use the version your distro (Debian?) provides. Using another version of Qt could break all of your Qt apps, to say nothing of the fact that Qt should never be directly installed from its source.

Sooner or later you'll get a Qt upgrade, depending  on your distro.

**Comment by CodexForster** [comment]
Yes. My distro has 5.9 as the latest version of Qt, which means I can't install the latest version of FeatherPad, but anyways, I think I can work with v0.15.0 until my distro gets a better version of Qt.
Thanks a lot for the help! You can close the issue now.

**Comment by tsujan** [comment]
> but anyways, I think I can work with v0.15.0 until my distro gets a better version of Qt.

Yes, that's a good decision. Installing apps by using the package manager is always the cleanest way, in all distros.

> You can close the issue now.

I will, after bumping `QT_MINIMUM_VERSION`. Your report reminded me of that.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/626d84ce92e70038f9ab1cb6edff79aa5fe0674f
