### ISSUE TITLE
Feature request: F3 to continue search

### ISSUE THREAD

**Issue by KloudKoder** [tsujan/FeatherPad#470]
Code development is a whole lot of this:

Search
Edit
Search
Edit
Search

etc. It's really awkward to have to press Ctrl+F, enter search text, toggle the dialog with Ctrl+F again, do some editing, press Ctrl+F again, etc. Most editors make this easy: Ctrl+F to search, then allow immediate editing (no need to back out of search), then F3 to repeat the search. No cumbersome mouse movements, no context toggling.

I realize that to properly fix this, you'd need to rearchitect Featherpad in a way you don't like, but even just the F3 functionality would be wonderful. Or maybe it's already there in some nonobvious way? In your help text, it says that F3 clears the search dialog, which is kind of the opposite of what most editors do. I don't care if it's F4 to continue search; anything in that regard would be a welcome improvement.

**Comment by tsujan** [comment]
F3 continues the search since FeatherPad was made.

> toggle the dialog with Ctrl+F again

That's an awkward habit of yours. Press `Esc` and the editor will be focused (`Backtab` if you have an outdated version).

> Most editors make this easy: Ctrl+F to search, then allow immediate editing

If I was satisfied with "most editors", I wouldn't make FeatherPad.

> Or maybe it's already there in some nonobvious way?

You seem unfamiliar with the basic concept of tooltip.

**Comment by KloudKoder** [comment]
Fair enough, looks like I've been stuck with an outdated version
