### ISSUE TITLE
Syntax highlighting: Pascal

### ISSUE THREAD

**Issue by ojz0r** [tsujan/FeatherPad#479]
Is there any plans to implement syntax highlighting for Pascal?
I tried to look through your code and i cant seem to find any mentions about it.

I like featherpad alot and it would be great to be able to use it for Pascal editing as well.

**Comment by tsujan** [comment]
I'm afraid I can't cover all syntaxes in FeatherPad; have included more than 30 common programming languages and syntaxes, which I think are more than enough for a lightweight (code) editor.

However, I'll take a look at Pascal's syntax (I don't code in Pascal). If it's simple enough, I'll add it. If not, I'll leave a comment here. Thanks for the suggestion!

**Comment by ojz0r** [comment]
Ofcourse i fully respect that.
Thank you for taking the time!

**Comment by tsujan** [comment]
I found this: https://www.freepascal.org/docs-html/ref/ref.html. The syntax seems simple.

**Comment by tsujan** [comment]
So far, so good:

![pascal](https://user-images.githubusercontent.com/981076/104117849-c0ee0e00-5339-11eb-871f-b8686b6255af.png)

I should continue reading the Pascal doc to see if something is missing...

**Comment by ojz0r** [comment]
Wow looks really good, you are a very fast and dedicated developer!

**Comment by tsujan** [comment]
Thanks!

After it's finished, if you encounter any problem in Pascal syntax highlighting, please tell me by opening an issue.

I tried to include everything that I found in various — and, sometimes, contradictory — documentations but, not being a Pascal programmer, I may have missed or misunderstood some things.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/3bc827c715a2b11f6efaa197d69ab487e7a6ff4d
