### ISSUE TITLE
Syntax highlighting: Java

### ISSUE THREAD

**Issue by stakek26** [tsujan/FeatherPad#482]
Are there any plans to add syntax highlighting for Java? A very common programming language.

**Comment by tsujan** [comment]
It shouldn't be difficult. I'll consider it when I find the time.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/33d5c05033bcf4d571592f368b0c5f2d01fd31b1

If you encounter a problem, please tell me by opening a separate issue!

**Comment by stakek26** [comment]
Excellent work. Thank you.

**Comment by tsujan** [comment]
You're welcome.

And thanks for your report — I'd totally forgotten Java.
