### ISSUE TITLE
Increase side pane file limit?

### ISSUE THREAD

**Issue by Amandaville** [tsujan/FeatherPad#486]
Is there a way to allow more than 50 files in the side pane?  This week I noticed that some of my regularly used files were missing from the side pane.  It took a few days, but I finally figured out that Featherpad drops files from the list when the total exceeds 50.

**Comment by tsujan** [comment]
You can have 1000 files in the side-pane. What you see is that, if `Preferences → File → Start with files of last window` is checked. FeatherPad will remember a maximum of 50 opened files of its last window plus their cursor positions on exiting.

Starting FeatherPad with more than 50 files would be not only CPU-intensive but also impractical (actually, 50 is also too big).

Instead, you could use the Session Manager and save a session consisting of more than 50, 100, 500,… files and open that session whenever you need it (last cursor positions are also saved). You could also have several saved sessions.

**Comment by Amandaville** [comment]
Okay, I will try the Session Manager to see how that works for me.  I was hoping there was a config file that I could edit to increase the side-pane limit.  FYI, I don't see any ill effects of having that many files open.  My 6th generation I5 is showing 0.6% CPU and 0.2% MEM with 50 files in the side-pane.

**Comment by tsujan** [comment]
> FYI, I don't see any ill effects of having that many files open

Not having them open but opening them at the start.

You want a saved session, not a temporary collection of last files that can be changed inadvertently.
