### ISSUE TITLE
Missed features - Whitespaces and line endings

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#49]
it would be nice to have options to show whitespaces and nice line endings

**Comment by tsujan** [comment]
Will think about it; shouldn't be hard to implement.

**Comment by agaida** [comment]
And if you are on it - a ruler with default position after 79 (pep8) or 80 cols would be nice to have too :)
Hmm, i should run and hide very fast now :) (While running; Intendation lines would be nice and useful too ...) 

![](https://pb.5id.eu/547w.jpg)

**Comment by tsujan** [comment]
Wow! I was so busy that totally forgot about this.

With which text editor did you take the screenshot?

**Comment by agaida** [comment]
this is a stock atom

**Comment by tsujan** [comment]
Oh, here on Manjaro, it wants to install hundreds of megabytes, especially because of `electron`, which I don't want on my system.

Does FeatherPad have any problem with Python?

**Comment by agaida** [comment]
no, but it is handy to have visible whitespaces, a line at 79 char and so on

**Comment by tsujan** [comment]
OK. I asked because I use Python only rarely -- although Python is the heaven of every programmer. If you see any problem in Python syntax highlighting, please open an issue!

I'll experiment with those features one by one.

**Comment by xircon** [comment]
Actually python is my personal hell, I persist with out of pure masochism :D

**Comment by tsujan** [comment]
@xircon I'm not good at Python at all but, whenever I have to deal with it, it feels so "cozy". Hence that exaggeration ;)

**Comment by xircon** [comment]
I produce some good stuff, but it just winds me up.  It does not make things easy:
Forced indentation - WTF!
Lack of indirect addressing/macro expansion - Apparently I am not "pythonic"
I struggle (probably my fault) with lambda (anything!).

**Comment by tsujan** [comment]
@agaida I added an option for showing whitespaces (spaces, tabs, line-ends and the doc end) when syntax highlighting is enabled. It's under Preferences → Text . Please test it whenever you have time and tell me if there's a problem!

@xircon I've never pursued Python seriously, so my opinion about it can't be reliable. As I once told a friend of mine, Python may not be so good for end-users -- due to backward incompatibility and a higher memory usage compared to C/C++ -- but I like it from a distance ;)

**Comment by tsujan** [comment]
Added indentation vertical lines (rulers) too. They're automatically enabled when whitespaces are shown with syntax highlighting (Preferences → Text):

![rulers](https://user-images.githubusercontent.com/981076/31051774-5b492a8c-a67e-11e7-9262-0e1961aaae29.png)

**Comment by tsujan** [comment]
Thanks to this new feature, a bug is also fixed and text tabs are now exactly equal to 4 spaces :)

![tabs](https://user-images.githubusercontent.com/981076/31052311-05df0de0-a68e-11e7-87ed-e7bf4c73112d.png)

**Comment by agaida** [comment]
so far so good, but i dont think that couple the display of whitespaces to syntax highlighting is the best idea, second whish - if possible - make the line endings not so prominent - maybe gray would be fine

![](https://pb.5id.eu/2WI8.jpg)

Maybe a good idea too - give the user the option to set a default lexer in options and maybe a switch in the status line to switch the highlighting

**Comment by agaida** [comment]
Hmm - if a simpel lexer, maybe text (option) is choosen for not detected content, coupling the display of whitespaces  and lines to syntax hightlighting is indeed a good idea.

**Comment by tsujan** [comment]
Actually, I put whitespaces under syntax highlighting *by force* because when an ordinary file is opened, there's no need to clutter the text-view with extra marks. IMO, showing whitespaces may be useful only with programming languages and syntax highlighting.

> and maybe a switch in the status line to switch the highlighting

Syntax highlighting can always be toggled by a menu-item and its shortcut `Ctrl+Shift+H`.

>  if possible - make the line endings not so prominent - maybe gray would be fine

Yes, I noticed that too. It's a challenge because Qt text rendering works based on the concept of "block" and those marks are outside all blocks.

There's also a second problem: when the line numbers are shown, the vertical rulers of the current paragraph become hidden behind the paragraph highlight.

I'll try to fix these 2 problems.

**Comment by tsujan** [comment]
BTW, I should add Debian control files to syntax highlighting -- as I did with Arch PKGBUILD files.

**Comment by agaida** [comment]
that would be great

**Comment by agaida** [comment]
![](https://pb.5id.eu/N_cA.jpg)

so this is a text file captured from build  output - the interesting part for me is the diff - and i want to be able to set the type by hand - mousepad is really fine in that.

**Comment by tsujan** [comment]
You mean forcing the programming language for syntax highlighting?

**Comment by tsujan** [comment]
Rulers aren't hidden by line highlight anymore:

![visible_rulers](https://user-images.githubusercontent.com/981076/31057362-62d4c002-a6ee-11e7-88bb-43ba998d4a15.png)

I didn't find a way for graying out line-break marks.

As for diff files, I didn't understand what the problem might be. FeatherPad does highlight the diff syntax but the file should be recognized as diff by the system first:

![diff](https://user-images.githubusercontent.com/981076/31057395-e3b5ea7a-a6ee-11e7-82d2-e4630eddec59.png)

Kate has the same behavior.

**Comment by tsujan** [comment]
Added debian/control syntax highlighting:

![deb](https://user-images.githubusercontent.com/981076/31061629-20c52020-a730-11e7-8699-409199dbfe22.png)

I think this can be closed now. Refinements will be made later.

**Comment by agaida** [comment]
cool - and yes, i'm thinking of a way to override the detected type - think of mixed contents like in build logs and so.

**Comment by agaida** [comment]
btw - it would be nice to have a releases soon

**Comment by tsujan** [comment]
@agaida I'm really doubtful of the benefits of a language override, although its implementation would be very easy. If, for example, a c++ file isn't shown as c++, that may indicate a problem in its name or somewhere else. Such problems are global and should be solved accordingly, IMO.

That being said, I'll think about language override.

Yes, a new release is needed. I'll do it in ~10 days -- should test some things thoroughly and might make small modifications.

**Comment by tsujan** [comment]
V0.6.1 released.
