### ISSUE TITLE
Missed features - auto brackets

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#50]

**Comment by tsujan** [comment]
You mean highlighting paired brackets `[....]` when one of them is chosen, like perpetrates and braces? Or do you mean `<...>`? The latter might be a less-than or greater-than sign.

**Comment by tsujan** [comment]
Auto-spelling changes "parentheses" to "perpetrates" ;) Corrected it.

**Comment by agaida** [comment]
http://pb.5id.eu/N800.mkv - autobrackets

**Comment by tsujan** [comment]
Got it and will add it. Thanks!

**Comment by agaida** [comment]
Cool, Thanks.

**Comment by tsujan** [comment]
Auto-bracket is added :) It can be enabled in Preferences → Text → Auto-bracket.

I didn't add the behavior of Kate or Qt Creator when `Enter` is pressed inside brackets because, IMO, it takes away control from the user and isn't so helpful.

**Comment by tsujan** [comment]
Added a Kate-like behavior on pressing `Enter` but only immediately after auto-bracketing and only for parenthesis and braces. I found it useful when coding.

**Comment by agaida** [comment]
really nice

**Comment by tsujan** [comment]
Thanks! Now I'm using this feature while fixing 2 bugs in pcmanfm-qt; will make one PR for both.

**Comment by adamjp** [comment]
I really like your editor.  Auto-bracket does not seem to work for single quotes.  Is that on purpose or am I missing something?  I am using version 0.12.1 that comes with MX Linux 19.

**Comment by tsujan** [comment]
> Auto-bracket does not seem to work for single quotes. Is that on purpose...

Yes, it's intentional. As in `it's`, single-quote auto-bracket could be very annoying, while including double-quote is practically useful.

For a similar reason, I've excluded `<` too.

**Comment by adamjp** [comment]
Makes sense.  I will not bug you any more on this except to say that atom and sublime include auto bracketing with single quotes too.  I like your editor because it is lighter yet has lots of functionality.  I want to use it for coding, mainly node.js, javascript etc.  Single quotes are used constantly in js.  Thank you for your reply.

**Comment by tsujan** [comment]
Thanks for the kind words!

> I want to use it for coding, 

I use FeatherPad + QTerminal -- and nothing else -- for coding.

> mainly node.js, javascript etc

Good! If you find any problem in JS syntax highlighting, please don't hesitate to report it! Highlighting of JS and, especially, Perl regex was a nightmare ;)

FeatherPad supports many programming languages but I don't code in all of them -- I mostly code in C, C++, bash and, just a little, Python and Lua but have got familiar with other syntaxes through others' codes.
