### ISSUE TITLE
a symbol at the end of each wrapped line

### ISSUE THREAD

**Issue by ralf3u** [tsujan/FeatherPad#520]
some people like me don't like the break-symbol at the end of a line, is it in Geany, LibreOffice Writer or FeatherPad; with a symbol at the end of each wrapped line, I could see if a line is a wrapped line or if in a line I pressed return; one more advantage of a symbol at the end of each wrapped line: one get a visible hint if the wrapped-line-modus is active

possible solution
in the editor Geany there is a symbol at the end of each wrapped line, like you can see on the right side in the picture; in Geany it is default and can't be disabled
but maybe some will not like the symbol at the end of each wrapped line; so maybe it would be good to put a checkbox in the "Preferences" in "Text" just below "Wrap lines by default" with this kind of text: "symbol at the end of each wrapped line"

my FeatherPad 0.17.1 in Lubuntu 21.04 is old, but I still don’t know how to install the latest version
if in FeatherPad 0.18.0 there is already a symbol at the end of each wrapped line, then I’m sorry for this report
<br><br>

![geany_screenshot](https://user-images.githubusercontent.com/68117017/116112699-16b3af80-a6b8-11eb-8ee0-e9793bf4ca50.jpg)

**Comment by tsujan** [comment]
If you check `Preferences → Text → Also show line and document end`, the end of the real line (= block) will be marked by a symbol and the lack of that symbol will show that the visible line is wrapped. No need to a redundant symbol for wrapped lines.

**Comment by tsujan** [comment]
People may like opposite things and there are various tastes. The important thing is functionality. The goal is knowing which visible line continues and which doesn't; both methods do that. Using a single symbol at the end of a whole line is cleaner than using several symbols at the end of its wrapped parts.

**Comment by ralf3u** [comment]
> Using a single symbol at the end of a whole line is cleaner than using several symbols at the ends of its wrapped parts.

Cleaner? Really? Ok, so here is a side by side comparison:

![side-by-side](https://user-images.githubusercontent.com/68117017/116264197-65298280-a77a-11eb-9770-f5b05afbed06.jpg)

I think it is more then obvious, that Geany with its symbols at the end of each wrapped lines is much cleaner than FeatherPad.

**Comment by tsujan** [comment]
> Cleaner? Really?...

Programmatically, FeatherPad is cleaner because it shows a *real* character inside the text, namely, "new-line" — while those arbitrary symbols in Geany don't correspond to any character.

Aesthetically, taste are different, as I've mentioned tens of times.
