### ISSUE TITLE
Ability to autosave non-existent files

### ISSUE THREAD

**Issue by UnsolvedCypher** [tsujan/FeatherPad#523]
I like to use Featherpad as a scratchpad for short-term notes, but sometimes my computer will crash or run out of battery and I lose them. It would be nice if I could specify a directory to autosave these in-progress files so that I can recover them. Thank you by the way for this excellent software :)

**Comment by tsujan** [comment]
I'm afraid that's the job of a notes manager with auto-saving. (Unix philosophy: Make each program do one thing well.)

**Comment by UnsolvedCypher** [comment]
I do appreciate the Unix philosophy :) I was more asking for a modification to the current "save changes to open files" feature that FeatherPad has. Currently it ignores any files that haven't been saved somewhere, I think it would be nice if you could give it a default location and it would do the auto-saving for all files, perhaps giving the new files the current time as a name. I do understand if this is out of scope, just wanted to clarify what I was suggesting.

**Comment by tsujan** [comment]
I understood your suggestion and appreciate your interest in FeatherPad.

However, a text editor should ask where to save if no file is opened. The only reason for adding such an unusual feature would be using FeatherPad as a notes manager, which it isn't.

Actually, a notes manager also starts with a file; the user could add various kinds of notes to that file by using the app.
