### ISSUE TITLE
Feature request: unified search/replace/jump interface

### ISSUE THREAD

**Issue by KloudKoder** [tsujan/FeatherPad#526]
It would be nice if I could toggle a switch somewhere and magically get all the find dialogs, search-and-replace dialogs, and line-jump dialogs to:

1. Be shared identically among tabs. So if I jump to line 22 in the first tab, then instantly that's the default for the second tab. Really helps if I'm trying to search-and-replace the same thing in multiple files.
2. Have shared hide/show toggles among tabs. So if I hide the find dialog in the first tab, it's instantly hidden in the second tab.

It's really awkward to try to remember whether I need to hide/unhide each particular type of dialog as I switch back and forth between tabs. I mean, it only takes a second to look, but I'd prefer to just speed along with editing and not have to remember what state the dialogs are in in which tab. 

I thought "Use a shared search history" might do this, but it seems to do something else.

**Comment by tsujan** [comment]
First, there's no search *dialog* in FeatherPad (are you sure you're using FeatherPad?!).

Second, having the same search entry for all tabs would mean a serious drawback, not a feature.

If you want to search the same string in all tabs, check "Use a shared search history". Read `Help → Searching and Replacing` for knowing how to use the search history. I've written `Help` for users to get familiar with the app's features as easily as possible.

**Comment by KloudKoder** [comment]
@tsujan By "search dialog", I mean the field that appears when I hit Ctrl+F.  Anyways thanks I get it now.
