### ISSUE TITLE
Allow custom alt+key bindings to overwrite menu accelerators

### ISSUE THREAD

**Issue by adabru** [tsujan/FeatherPad#527]
I'd like to use the alt+s and alt+f shortcuts to switch to the previous/next tab. I can set these shortcuts in the preferences and when the menubar is hidden, the shortcuts work fine. But when the menubar is visible, these shortcuts trigger the menu accelerators (i.e. alt+f : "File", alt+s : "Search") instead of the assigned custom functions.

[There doesn't seem to be a way to disable Qt menu-accelerators globally](https://forum.qt.io/topic/126482/disable-alt-menu-shortcuts-systemwide), so would it be possible to have an option to disable them? The linked forum thread mentions one could set `qt_set_sequence_auto_mnemonic` to `false`. Maybe this could be made configurable in preferences?

As workaround I could hide the menubar but then I'd have to show the toolbar which is too large for my taste.

**Comment by tsujan** [comment]
> so would it be possible to have an option to disable them?

Yes, it's possible and is a good idea. I'll add it. Thanks for the suggestion!

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/fbc40e908e6c9a655f1d34b469afe7fa790f243a

I didn't use `qt_set_sequence_auto_mnemonic` because (1) it would disable all accelerators, not just those of the menubar, and (2) accelerators would still be visible with it.
