### ISSUE TITLE
Feature Request - read-only (view only) toggle for files

### ISSUE THREAD

**Issue by guiverc** [tsujan/FeatherPad#528]
This issue maybe considered stupid - but it's how I use the program.

I have featherpad open on my LXQt desktop always; with a list of files (restored session) that I only very rarely change (mostly using them for cutting/pasting; answers for support, QA-test entries etc).

Currently I know if I've changed a file in error because of the "*" appearing in front of the filename, but I often miss it.. and so on occasion wonder if I've made a change I failed to save, or I mis-hit keys on my keyboard & thus corrupted something..

I request a "READ ONLY toggle" option be available, so I can use it like `vi` has a 'view' mode, being able to toggle featherpad into EDITOR mode when I need to change my mostly static files...  

It'd be great if this was on a file-by-file (file-by-tab?) basis (I have 5 tabs opened when I restore session), but having the whole of featherpad toggle to READONLY or EDITOR mode would work for my use case just as well I believe.

Thanks in advance for the great program :)

**Comment by tsujan** [comment]
I'm afraid your use case is too personal.

However, you could open a file twice and close its first instance. The second instance will have a special background that shows it's read-only.
