### ISSUE TITLE
changing the shortcut from ctrl+w to ctrl+shift+j is not possible

### ISSUE THREAD

**Issue by ralf3u** [tsujan/FeatherPad#543]
in the Preferences in Shortcuts I wanted to change the shortcut from ctrl+w to ctrl+shift+j
but it is not possible; it says that it is reserved although I can't find the shortcut ctrl+shift+j nor in the list of Shortcuts nor in the menu

my FeatherPad 0.17.1 is old even if I use the new Lubuntu 21.04, but I still don’t know how to install the latest version
if the issue does not appear in FeatherPad 0.18.0 any more, then I’m sorry for this report

**Comment by tsujan** [comment]
Unlike most apps that let their users set ambiguous shortcuts and break them, FeatherPad clearly says that they're reserved.

Not all shortcuts are on the list or menus.

**Comment by ralf3u** [comment]
Ctrl+w is the common use for closing tabs. In comment https://github.com/tsujan/FeatherPad/issues/423#issuecomment-698037012, it is mentioned that it can be changed to Ctrl+w. But it is not possible.

Also Ctrl+Page up and Ctrl+Page down is the common use for tab-browsing. But also those shortcuts are not possible. 

All those shortcuts are reserved, although they are not in use in the list of shortcuts. Would it be possible to make them not reserved?

**Comment by ralf3u** [comment]
>Ctrl+w is the common use for closing tabs. In comment https://github.com/tsujan/FeatherPad/issues/423#issuecomment-698037012, it is mentioned that it can be changed to Ctrl+w. But it is not possible.

I don't know what happened but now it works in 1.3.5.
Thank you so much for this shortcut!

Unfortunately tab-browsing with the Ctrl+Page up and Ctrl+Page down like in Firefox is still not possible. Is it really so complicated to realize it?

Hey, what about to add the possibility to customize the shortcuts of the features of Ctrl+Page up and Ctrl+Page down? Then I could change the four shortcuts to use tab-browsing with the Ctrl+Page up and Ctrl+Page down like in Firefox!
Pleeeease!

**Comment by tsujan** [comment]
> I don't know what happened but now it works in 1.3.5.

I did nothing, as nothing was needed to be done. You changed the shortcut for line wrapping to something other than `Ctrl+W` — perhaps unknowingly — so that `Ctrl+W` can be used elsewhere.

> what about to add the possibility to customize the shortcuts of the features of Ctrl+Page up...

Such shortcuts belong to the text editor widget and are hard-coded by Qt. Therefore, they are excluded from the shortcut editor.

>... like in Firefox....

One shouldn't compare a text/code editor with a web browser. They have no relation to each other.

**Comment by ralf3u** [comment]
>Such shortcuts belong to the text editor widget and are hard-coded by Qt.

So, it could be that Qt will one day add the possibility to customize the shortcuts of the features of Ctrl+Page up and Ctrl+Page down?

**Comment by tsujan** [comment]
Not necessarily. It's possible to add hundreds — or perhaps thousands — lines of code to make editor's shortcuts customizable. Of course, it absolutely isn't worth the effort.

**Comment by ralf3u** [comment]
>One shouldn't compare a text/code editor with a web browser. They have no relation to each other.

The editor Geany, the editor Kate, the editor Visual Studio Code, the terminal QTerminal, the file-manager PCManFM-Qt, OpenOffice Calc, the browser Firefox, the browser falkon, and even Gimp are all using Ctrl+Page up and Ctrl+Page down for tab-browsing.

**Comment by tsujan** [comment]
> The editor Geany, the editor Kate, the editor Visual Studio Code....

The apps that aren't text editors don't count at all.

As for the others, the developers of an app like Kate may not care when they don't have two sets of shortcuts for scrolling by one page without selecting the text: one with moving the cursor (PgDn/PgUp in FeatherPad), the other without moving the cursor (Ctrl+PgDn/PgUp in FeatherPad).

I do care and have included codes in FeatherPad to protect such important shortcuts from being assigned to other jobs. That will never change.

**Comment by ralf3u** [comment]
>... one with moving the cursor (PgDn/PgUp in FeatherPad), the other without moving the cursor (Ctrl+PgDn/PgUp in FeatherPad)

Sorry to ask, but why you don't offer the possibility to customize the shortcuts scrolling without moving the cursor (Ctrl+PgDn/PgUp)?
If you would add this option (well, in real there are two options because there are two shortcuts) then one could change Ctrl+PgDn/PgUp for tab-browsing. Ctrl+PgDn/PgUp for tab-browsing is a very important feature for me. Why preventing users to change important shortcuts?
