### ISSUE TITLE
visible spelling mistakes in the text

### ISSUE THREAD

**Issue by ralf3u** [tsujan/FeatherPad#548]
it's cool to have a spelling in FeatherPad, but instead of a spellcheck one by one by pressing F2, it would be better to see ALL mistakes AT THE SAME TIME in the text with a red underline in waveform like in Geany or in LibreOffice; a "spellcheck on/off"-button in the toolbar like in the editor Geany and a shortcut for this feature would be perfect; it should work exactly like "Automatic Spell Checking" in LibreOffice 7.1.3.2, what works in LibreOffice with the shortcut shift+F7

this is how the spellcheck looks like in the editor Geany 1.37.1:
![spelling](https://user-images.githubusercontent.com/68117017/125250294-5ae94000-e2f6-11eb-800d-55b08f1aad37.jpg)

my FeatherPad 0.17.1 is old even if I use the new Lubuntu 21.04, but I still don’t know how to install the latest version
if the issue does not appear in FeatherPad 0.18.0 any more, then I’m sorry for this report

**Comment by tsujan** [comment]
There are several differences between an inline spell checker and spell checking with a dialog that can start spell checking from the cursor position (and that's one difference). Suffice it to say that an inline spell checker can be CPU-intensive with heavy texts.

**Comment by tsujan** [comment]
BTW, closing a report doesn't mean that it was a bad idea. I appreciate all your reports.
