### ISSUE TITLE
Preferences window checkboxes

### ISSUE THREAD

**Issue by zoomosis** [tsujan/FeatherPad#560]
In Options -> Preferences, may I suggest changing "Do not show toolbar" to "Show toolbar" and reversing the meaning of the checkbox.

Likewise "Do not show menubar" and "Do not permit opening of non-text files".

Just a trivial change, but helps usability.

**Comment by tsujan** [comment]
Thanks for your suggestions but toolbar and menubar are shown by default everywhere; those options are for *hiding* them, in certain ways.

Also, I don't think negative descriptions can damage usability. In addition to cases like the above, they can be used to place emphasis on something (as in "Do no permit..."). The rest is just a matter of taste.

BTW, you could use [Discussions](https://github.com/tsujan/FeatherPad/discussions) for ideas or Q&A.

**Comment by zoomosis** [comment]
I am not suggesting turning off the toolbar and menubar by default. I just have a problem with the current descriptions resulting in their checkboxes become double-negatives in the Preferences window when they are unchecked. I found that quite confusing.

Noted about the Discussions, thanks.
