### ISSUE TITLE
Release as flatpak?

### ISSUE THREAD

**Issue by K0-RR** [tsujan/FeatherPad#563]

**Comment by Hasshu** [comment]
> Packaging is done by downstream.

Flatpak might finally solve this long-standing issue by making official packages that work on every distro a reality.

**Comment by tsujan** [comment]
There has never been a "long-standing issue" but Flatpak is free to see something as an issue and solve it.

Please note that any problem in Flatpak's packages should be reported to Flatpak.

**Comment by Hasshu** [comment]
@tsujan Do you think that official distro-agnostic packages aren't a good idea? But why, if you don't mind my asking? Even Linus Torvalds [believes there's a problem](https://www.youtube.com/watch?v=Pzl1B7nB9Kc).

**Comment by tsujan** [comment]
A proper packaging is done only by the package manager of your distro. You could wait until your distro does it for you, or you could learn how to do it yourself — not only it's not rocket science but also it can be fun with small apps.

Red Hat is known for troubling open-source with its bad ideas. After all, open-source devs may solve Red Hat's problems for free, ordinary users are susceptible to its advertisements, and it can hide after creating a mess.

> Even Linus Torvalds believes there's a problem.

I don't agree with him. He also dislikes C++ ;)

**Comment by Hasshu** [comment]
@tsujan I disagree, but I see your point. Thank you for actually explaining it.

> I don't agree with him. He also dislikes C++ ;)

Heh.
