### ISSUE TITLE
ReStructuredText highlighting?

### ISSUE THREAD

**Issue by ghost** [tsujan/FeatherPad#57]
Don't you think such a fine editor deserves rest syntax highlighting as well?! Not that I use rest (at the moment), but gather it's superior to markdown (except for its idiotic headings) and very popular among the developers as you would know much better than me.

**Comment by tsujan** [comment]
Thanks for the suggestion! More syntax highlighting is always good. Do you have a good link explaining its syntax?

**Comment by tsujan** [comment]
Never mind! Found this with a simple search: http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html. There are several other sources too.

Now, I'm working on inertial wheel scrolling. Will work on ReStructuredText after that.

**Comment by AcarBurak** [comment]
Obviously Kate/QtCreator has a syntax file which I find rather very plain so I'll attach my modified one. As for the explanation you may find these helpful:
http://docutils.sourceforge.net/docs/user/rst/quickref.html
http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html

**Comment by tsujan** [comment]
This might take a while. Please see https://github.com/tsujan/FeatherPad/issues/26#issuecomment-341891799.

**Comment by ianorlin** [comment]
Any updates on this I still really want this and have found this issue rather than opening a new issue. I use restructured text everyday to write the lubuntu manual and having highlighting for featherpad will make things easier on me.

**Comment by tsujan** [comment]
OK, I'll make this my next job related to FeatherPad.

**Comment by tsujan** [comment]
At last, done in https://github.com/tsujan/FeatherPad/commit/c28c5c0b33cb6be58fc0fb1e49433764c9a09d20

Sometimes, simple "languages" have more complex highlighting; reStructuredText was so too.

I tested it with various `rst` files, including the kernel doc, and it worked correctly:

![kernel-doc](https://user-images.githubusercontent.com/981076/50691052-c9255b80-1044-11e9-9d0c-0a7039d977f9.png)

Please open an issue if you find a highlight that shows a wrong syntax!
