### ISSUE TITLE
Add Linux binary files to Release page

### ISSUE THREAD

**Issue by YALdysse** [tsujan/FeatherPad#570]
Please, add binaries to each new version.

**Comment by tsujan** [comment]
Here is upstream. Packaging is done downstream, by distro maintainers..

**Comment by YALdysse** [comment]
> Here is upstream. Packaging is done downstream, by distro maintainers..

Look at this: https://nightly.link/GTAmodding/re3/workflows/build-cmake-conan/master/ubuntu-18.04-gl3.zip
It is works on Manjaro, Mint, Ubuntu and others.

**Comment by tsujan** [comment]
Some developers may add installable packages to their releases. It isn't good practice for various reasons.

Also, see https://github.com/tsujan/FeatherPad/issues/563#issuecomment-906703936
