### ISSUE TITLE
Can't open some UTF-16 texts

### ISSUE THREAD

**Issue by IC-Tech** [tsujan/FeatherPad#575]
I am using featherpad 1.0.0
I can't open UTF-16 and UTF-32BE. my test is
```bash
echo 私 | iconv -f UTF8 -t UTF16 -o test.txt
```

**Comment by tsujan** [comment]
You could change the encoding to UTF-16 manually and see it but, no, UTF-16BE isn't supported completely. Maybe later...

**Comment by tsujan** [comment]
Such cases of UTF-16 are handled in the latest commit: https://github.com/tsujan/FeatherPad/commit/37a010410881762de7746061e3968782ae43642e

If you encounter other well-formed cases that aren't detected by the latest git, please tell me.

Thank you very much for the report!
