### ISSUE TITLE
Fountain highlighting?

### ISSUE THREAD

**Issue by ghost** [tsujan/FeatherPad#58]
https://fountain.io/syntax

https://github.com/rnkn/fountain-mode
https://github.com/vim-scripts/fountain.vim/blob/master/syntax/fountain.vim
https://github.com/IBPX/fountain_nano/blob/master/fountain.nanorc
https://github.com/superlou/fountain-atom
https://github.com/derickc/Fountainhead

My simplified attempt adopted from kate's markdown:
[fountain.tar.gz](https://github.com/tsujan/FeatherPad/files/1679964/fountain.tar.gz)

**Comment by tsujan** [comment]
Thanks a lot! it might take some time but I'll add it too.

**Comment by AcarBurak** [comment]
Thank you.

**Comment by tsujan** [comment]
This might take a while. Please see https://github.com/tsujan/FeatherPad/issues/26#issuecomment-341891799.

**Comment by tsujan** [comment]
Started to work on this (after a long time). Strange that there's no mimetype for fountain but `fountain` as the extension will be enough.

It isn't as easy as it may seem at the first glance (because what comes after/before a line is important)...
