### ISSUE TITLE
Feature request: open new file in new window

### ISSUE THREAD

**Issue by adamgit** [tsujan/FeatherPad#584]
For people who prefer one window = one file (or the more advanced version: one window = one main file, with tabs per-window for related files), it seems there's currently no way to 'create a new file, in a new window'? I tried a bunch of things, and searching the closed issues.

Currently:
1. Setting 'open files in new window' has no effect on creating new files
2. New file always creates a new tab in current window
3. Drag/drop only works window-to-window, it fails if you try to create a new window

In particular, compare to:

Firefox/Chrome/etc: drag/drop a tab to somewhere that's NOT an existing window automatically creates a new window and moves the tab there
NB: most IDE's work similarly: drag/drop a sub-panel into empty space and it becomes a popup window

However, even something as simple as a keyboard shortcut / file-menu option to 'create IN NEW WINDOW' would work fine I believe.

**Comment by tsujan** [comment]
> Drag/drop only works window-to-window, it fails if you try to create a new window

Not true. Dragging a tab outside all FeatherPad windows creates a new window with that tab in it. There's also the item "Detach Tab" under the File menu, that can have a shortcut.

Do you work under Wayland? If so, use "Detach Tab" (also, read Help → Drag-and-Drop).

**Comment by adamgit** [comment]
What do you mean 'not true'? You cannot reproduce?

1. Open Featherpad
2. ctrl-n (or use file menu) to make a new tab
3. drag that tab off window
4. (cursor changes to the no-entry sign)
5. (dropping destroys the tab)

version: 0.12.1-1build1
ubuntu: 20.04 (current)

**Comment by adamgit** [comment]
'Detach tab' in theory would work great, but it has the same
behaviour: it simply deletes the tab.

**Comment by tsujan** [comment]
> Have you heard of ubuntu?

You may want to learn the difference between upstream and downstream and then report Ubuntu problems to Ubuntu.

> I don't want to touch this software

Totally irrelevant.
