### ISSUE TITLE
QKeySequence for system-wide shortcuts

### ISSUE THREAD

**Issue by probonopd** [tsujan/FeatherPad#585]
Please consider following QKeySequence for system-wide shortcuts.

FeatherPad should make use of [`enum QKeySequence::StandardKey`](https://doc.qt.io/qt-5/qkeysequence.html#StandardKey-enum).

For example, if it would use in

https://github.com/tsujan/FeatherPad/blob/03800e4e967331a049cb7cd48eeaec848d9583c3/featherpad/searchbar.cpp#L118

```
toolButton_nxt_->setShortcut(QKeySequence::FindNext);
```

then the system-wide key (F3 by default, but Command-G on my system) for "Next" (a.k.a. "Find again") would be used like in other Qt applications that follow the system-wide QKeySequences.

**Comment by tsujan** [comment]
Thanks for the suggestion but I'm afraid my answer is exactly like https://github.com/lxqt/qterminal/issues/862#issuecomment-944898765, except for the first paragraph.
