### ISSUE TITLE
Could you add .bash_functions to sh syntax?

### ISSUE THREAD

**Issue by AcarBurak** [tsujan/FeatherPad#59]
Could you add .bash_functions to sh syntax?

**Comment by tsujan** [comment]
Yes, of course!

BTW, could you please try inertial scrolling (Preferences → Text → the last but one option) that I added today? Does it feel inertial to you?

**Comment by AcarBurak** [comment]
Thank you.

Inertial scrolling? Slightly I guess, not sure, as I don't think I've got much experience of inertial scrolling.

**Comment by tsujan** [comment]
> I don't think  I've got much experience of inertial scrolling.

I haven't either. I just wanted smooth scrolling, in spite of what people said about its impossibility with QPlainTextEdit, and after 4 hours of failure, I believed what they said ;) However, I found something interesting among my experiments and called it "inertial scrolling" -- because it persisted for ≥ 300 ms after the wheel stopped and felt like inertia. After polishing it, I googled for the term and found that the same words were used in Mac OS.

**Comment by AcarBurak** [comment]
Yes, it feels slightly smoother, and smoother than qtcreator. Scrolling is fine. Only if we could retain the cursor position and the last opened file after relaunching! Would that make fp heavy?

**Comment by tsujan** [comment]
> Only if we could retain the cursor position and the last opened file after relaunching! Would that make fp heavy?

In that case, after a while -- when many files have been opened -- not only a long list should be checked on opening a file but also nonexistent files should be removed from the list. That could have a negative impact on the stat-up/opening time, especially for heavy files and even if the removal is done on quitting.

**Comment by tsujan** [comment]
If remembering the cursor position is done only for recently opened/edited files, there won't be any negative impact. However, I don't think that it could be practical because recent files are replaced in the list after their max number is reached.

**Comment by tsujan** [comment]
The only good possibility that comes to my mind is adding a menu-item for saving the cursor position. That would need other things too (like cleaning the saved cursor positions for nonexistent files, optional cleaning,...). t seems to be worth considering.

**Comment by AcarBurak** [comment]
I don't have heavy files, but qtcreator launches instantly, in a second, with 31 files showing me the last opened one and retaining cursor positions in every one of them, but again this is my experience with my simple files on a SSD. Thanks for considering.

**Comment by tsujan** [comment]
Restoring the cursor position is a piece of cake. What worries me is that those 31 files could become 310 or 3000 after a while. That usually doesn't happen with qtcreator.

There should be a limit. The upper limit of recently opened/edited files is 20 in FeatherPad. I could increase it to 50 but still the saved cursor position of the 50th file will be lost if a new file is opened/edited.

**Comment by AcarBurak** [comment]
> those 31 files could become 310 or 3000 after a while.
Wait wait wait, there must be some misunderstanding, as I may not put it clearly. I was not talking about the opened and closed files, but the session files or this

`Options->Preferences->Files->Number of recent files:X + Show recently opened files + Start with recent files:X`

Those can't be even 50. Who would want a session with 50 files? Not sure if I'm clear now though.

**Comment by tsujan** [comment]
> Who would want a session with 50 files?

You're right; no one ;)

So, apparently, there should be another list of opened files -- bigger than the list of recently opened files but including it and, preferably, saved in a separate setting file. This seems good to me. However, that list should have an upper limit.

**Comment by AcarBurak** [comment]
Why `another list of opened files`? Because of `recently opened files + session files`?

**Comment by AcarBurak** [comment]
I guess it's better to implement this only for session files, no?

**Comment by tsujan** [comment]
> I guess it's better to implement this only for session files, no?

Wow! That's the best idea! Thanks for this discussion! I add this feature to my TODO list for the next release :)

**Comment by AcarBurak** [comment]
:)
Actually, unaware of it, we've been talking about another open issue: https://github.com/tsujan/FeatherPad/issues/38

The session issue. I'll make a little more noise there if you don't mind.

**Comment by tsujan** [comment]
You're always welcome to tell me about your ideas. Without your suggestions, FeatherPad would lack some of its good features. I'll read your comments tomorrow.

**Comment by AcarBurak** [comment]
Thank you, very kind of you.

**Comment by tsujan** [comment]
Good news:

Today, after several experiments with saving cursor positions of session files, I chose an unusual method -- based on `QHash` -- which I think is much faster than common methods but whose config file isn't human-readable (not important, IMO). With it, I saw no extra delay in opening 30 session files whose cursor positions were at their ends, as if the process of reading/writing was instantaneous.

I'll test with more and heavier files before making a commit. It may need some polishing too. Will tell you when it's ready.

I have a feeling that If it weren't for your persistence, I might never start to think about it ;) So, thanks again for this great idea! It's really useful when one works on session files.

**Comment by AcarBurak** [comment]
Very fine indeed. I always know that I point out what you already know much better than me, but I can't help myself. Thanks for your kind words anyway.

**Comment by tsujan** [comment]
> I always know that I point out what you already know much better

Not this time, at least ;)

**Comment by tsujan** [comment]
The changes are pushed now. I tested them under extreme conditions (with more than 500 files).

With this feature, cursor positions will be remembered automatically for files that are managed by the session dialog -- there's no need to do anything for that.

If you encounter a bug, please open a separate issue!

**Comment by tsujan** [comment]
`.bash_functions` is also added to syntax highlighting, of course.

**Comment by AcarBurak** [comment]
Cursor positions retained, fine. Though not the last active file/tab which is intentional? I mean I quit FP while Session1>FileC is active, but relaunching FP the active file/tab is Session1>FileA.

**Comment by tsujan** [comment]
> Though not the last active file/tab which is intentional?

If so, it would be a bug. However, i can't reproduce it. Could you please tell me how to reproduce the issue in a step-by-step way? Thanks in advance!

**Comment by tsujan** [comment]
Oh, you mean restoring the activeness of a tab in addition to the cursor positions? If so, it isn't implemented (yet).

**Comment by tsujan** [comment]
In addition, the *order* of tabs cannot be retained with the current code because texts are read in a separate thread (for faster loading of multiple files). I should see if I could change the code to keep the order/activeness but it might be very tricky.

**Comment by AcarBurak** [comment]
> the order of tabs cannot be retained

I know!

**Comment by AcarBurak** [comment]
> Oh, you mean restoring the activeness of a tab in addition to the cursor positions?

Yes.

**Comment by tsujan** [comment]
Since tabs are "free" in FeatherPad (they can be detached and reattached freely), there's no way to tell which tab is active (more than one tab can be active in different windows).

Moreover, the asynchronous loading of files doesn't let the order be restored because there's no order in the first place. FeatherPad loaded files one by one a long time ago but that method was inefficient when there was a great number of files. Two methods of loading? Maybe but it doesn't seem elegant.

I might try to add a side-pane mode at some point. With that mode, tabs could be removed, so that the docs couldn't be detached or reordered. If the side-pane mode is proven to be practical (and especially, lightweight), I'll think about all this again.

**Comment by AcarBurak** [comment]
Side pane… the endless possibilities… How good it sounds!

**Comment by tsujan** [comment]
Bad news: read https://github.com/tsujan/FeatherPad/issues/38#issuecomment-340522731

**Comment by AcarBurak** [comment]
All right. How about this:

I open a SessionA file FileC via file browser and FP opens it in the SessionA automatically rather than its default non-session view?

**Comment by tsujan** [comment]
As I said elsewhere, I haven't jumped into conclusion yet ;) On the one hand, I have high hopes for QHash; on the other hand, I can't resist my curiosity about a side-pane. A lot of code should be written and should be checked for breaking the existing functionalities -- which would mean a lot of time. In short, it's a matter of time.

**Comment by tsujan** [comment]
Just a skeleton:

![start](https://user-images.githubusercontent.com/981076/32195019-4f0d3820-bdd1-11e7-9122-d2ac949d132b.png)

One of the advantages of a side-pane is that doc names can be filtered. A big disadvantage is the lack of tab DND.

**Comment by AcarBurak** [comment]
If you decide to implement it, would it be much trouble to add sessions there as well –that is, if it's not against your coding principles?

**Comment by tsujan** [comment]
How? Sessions are inside the session dialog, which doesn't obstruct the main window.

**Comment by AcarBurak** [comment]
A combobox Docs/Sessions. Chosing Sessions shows sessions.

Or by splitting the side pane one of which showing Sessions. Not good?

**Comment by tsujan** [comment]
When tomorrow comes, we'll think of tomorrow -- a proverb from my native language ;)

**Comment by AcarBurak** [comment]
Better proverb than the one I know in mine which is opposite to that.

**Comment by tsujan** [comment]
I like to know it, please!

**Comment by AcarBurak** [comment]
Don't leave/postpone today's work to tomorrow.

**Comment by tsujan** [comment]
LOL! I'd say they're complementary, rather than opposite.

**Comment by AcarBurak** [comment]
I'd say I've always followed yours!

**Comment by tsujan** [comment]
Very good news:

Today, I laid the foundation for the side-pane mode and, as I said before, used QHash to make a fast one-to-one relation between side-pane items and pages. Then, I tested with more than 200 files. The result was excellent: there was no lagging and no extra CPU usage. Tabs were switched instantly. A video that shows that: https://www.dropbox.com/s/w712yvhk21lzcp3/side_pane.mkv

The strangest thing was that the memory usage was a little less than when tabs were shown; I don't know why.

**Comment by AcarBurak** [comment]
Very fine. Then side pane or combobox , if any?

**Comment by tsujan** [comment]
Combo-box shouldn't make any difference in this but it isn't comfortable: every time, its popup menu should be shown before selecting an item.

**Comment by AcarBurak** [comment]
True, and not as versatile as a side pane either. Its only advantage is that it doesn't require additional window/screen area, obviously.

**Comment by tsujan** [comment]
An editable combo-box, with the auto-complete functionality, will be added for the sessions list (below the filter line-edit) after the side-pane is finished and pushed. Adding/removing/renaming sessions will still be done in the session dialog. However, there's a long way to go -- step by step.

**Comment by AcarBurak** [comment]
Sounds fine.
