### ISSUE TITLE
macOS: File dialog error

### ISSUE THREAD

**Issue by shlyakpavel** [tsujan/FeatherPad#592]
I manually disabled "system file dialog" and now it opens Qt file dialog.
![](https://user-images.githubusercontent.com/19782228/139527682-0686d684-f435-41a7-9ff4-415b7c83e999.png)
However, with system file dialog I get this:
![](https://user-images.githubusercontent.com/19782228/139527379-f4ee4b2a-80d5-4d0c-87b8-c5bc9542aec5.png)

**Comment by shlyakpavel** [comment]
It's possible that this is a Qt bug. I will investigate that later

**Comment by tsujan** [comment]
> It's possible that this is a Qt bug.

I'd say it definitely is. Qt 6.2 may have problems on macOS (it does on Linux but they're tolerable).

**Comment by shlyakpavel** [comment]
> Qt 6.2 may have problems on macOS

The other problem is that I'm testing it on new macOS 12.0.1 Monterey that was released 5 days ago

**Comment by shlyakpavel** [comment]
```
2021-10-30 12:26:58.505 featherpad[18748:147795] *** Assertion failure in -[NSSavePanel beginServicePanel:asyncExHandler:], NSVBOpenAndSavePanels.m:1907
2021-10-30 12:26:58.506 featherpad[18748:147795] -[NSSavePanel beginSheetModalForWindow:completionHandler:]_block_invoke caught non-fatal NSInternalInconsistencyException '<NSSavePanel: 0x12479b390> is attempting to advance this Open/Save panel to run phase while another self.advanceToRunPhaseCompletionHandler is in waiting for a previous attempt. An Open/Save panel cannot start to advance more than once.' with user dictionary {
    NSAssertFile = "NSVBOpenAndSavePanels.m";
    NSAssertLine = 1907;
} and backtrace (
	0   CoreFoundation                      0x00000001aee2412c __exceptionPreprocess + 240
	1   libobjc.A.dylib                     0x00000001aeb75808 objc_exception_throw + 60
	2   Foundation                          0x00000001afd50324 -[NSCalendarDate initWithCoder:] + 0
	3   AppKit                              0x00000001b2322c90 -[NSSavePanel beginServicePanel:asyncExHandler:] + 512
	4   AppKit                              0x00000001b2324140 -[NSSavePanel runModal] + 332
	5   libqcocoa.dylib                     0x0000000104980a98 qt_plugin_instance + 60096
	6   QtWidgets                           0x0000000105a14784 _ZN7QDialog4execEv + 264
	7   featherpad                          0x00000001043751ac _ZN10FeatherPad5FPwin8saveFileEbiibP15QListWidgetItemPNS_7TabPageE + 3136
	8   QtCore                              0x00000001053cf43c _ZN11QMetaObject8activateEP7QObjectPKS_iPPv + 3108
	9   QtGui                               0x0000000104f809a4 _ZN7QAction8activateENS_11ActionEventE + 368
	10  QtCore                              0x00000001053c7150 _ZN7QObject5eventEP6QEvent + 588
	11  QtWidgets                           0x000000010580b41c _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent + 272
	12  QtWidgets                           0x000000010580c65c _ZN12QApplication6notifyEP7QObjectP6QEvent + 544
	13  QtCore                              0x0000000105388a9c _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent + 208
	14  QtCore                              0x0000000105389d74 _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData + 820
	15  libqcocoa.dylib                     0x000000010497e248 qt_plugin_instance + 49776
	16  libqcocoa.dylib                     0x000000010497e8f8 qt_plugin_instance + 51488
	17  CoreFoundation                      0x00000001aeda4bbc __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
	18  CoreFoundation                      0x00000001aeda4b08 __CFRunLoopDoSource0 + 208
	19  CoreFoundation                      0x00000001aeda4860 __CFRunLoopDoSources0 + 376
	20  CoreFoundation                      0x00000001aeda3168 __CFRunLoopRun + 820
	21  CoreFoundation                      0x00000001aeda2694 CFRunLoopRunSpecific + 600
	22  HIToolbox                           0x00000001b7918990 RunCurrentEventLoopInMode + 292
	23  HIToolbox                           0x00000001b791861c ReceiveNextEventCommon + 320
	24  HIToolbox                           0x00000001b79184c4 _BlockUntilNextEventMatchingListInModeWithFilter + 72
	25  AppKit                              0x00000001b18f7aec _DPSNextEvent + 844
	26  AppKit                              0x00000001b18f6390 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1332
	27  AppKit                              0x00000001b18e83b0 -[NSApplication run] + 596
	28  libqcocoa.dylib                     0x000000010497d66c qt_plugin_instance + 46740
	29  QtCore                              0x0000000105391e14 _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE + 500
	30  QtCore                              0x000000010538917c _ZN16QCoreApplication4execEv + 128
	31  featherpad                          0x000000010434622c main + 2780
	32  dyld                                0x00000001045490f4 start + 520
)
```

**Comment by shlyakpavel** [comment]
<img width="840" alt="image" src="https://user-images.githubusercontent.com/19782228/139533574-755e47d3-badc-4cd2-990a-2e50a2000add.png">

>An Open/Save panel cannot start to advance more than once

Despite the error, file dialog is opened in the background window. It looks like the code tries to open it for the second time

**Comment by shlyakpavel** [comment]
The question is if it's Qt or FeatherPad loading two instances of file dialog

**Comment by shlyakpavel** [comment]
I have just tried Qt Application example. I got exact the same error when trying to save file. Possible solution can be to use Qt dialogs instead of native dialogs on MacOS by default until the problem is resolved on Qt side
<img width="503" alt="image" src="https://user-images.githubusercontent.com/19782228/139533862-faed06df-b935-470b-9161-ddf7e09737e4.png">
However, open file dialog works well with the app example
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/19782228/139533887-d0b36858-2af8-436e-b5de-90745a87dd4f.png">
Weird

**Comment by tsujan** [comment]
The native file dialog is a platform plugin. What you see is related to it.

It'll take a while until Qt6 becomes the default Qt in Linux. I guess, until then, probable problems will have been fixed. Qt5 had the same story...

**Comment by shlyakpavel** [comment]
@tsujan do you think it's a good idea to disable native file dialogs on Mac by default until the problem is resolved? I'm not sure if I should do it or not

**Comment by tsujan** [comment]
I don't think a fix will take a long time but, if it's a hassle, why not?

Qt6 still isn't usable on Linux because most Qt apps depend on the LTS Qt 5.15. I can try to port `libfm-qt` and `lxqt-qtplugin` to Qt6 to have a nice native Qt6 file dialog under LXQt but I think it's too soon for that, especially because keeping backward compatibility with Qt5 will need lots of work. Maybe, a few months later...

**Comment by tsujan** [comment]
My Qt6 platform plugins  are only these:

![Qt6](https://user-images.githubusercontent.com/981076/139535302-5dadd850-fbb6-4717-88cd-e75d7281c18c.png)

**Comment by tsujan** [comment]
Wrong screenshot. They're these:

![platform](https://user-images.githubusercontent.com/981076/139535534-ece0d526-8804-488e-80d5-85e823b0e6a2.png)

**Comment by tsujan** [comment]
> I have just tried Qt Application example. I got exact the same error...

A Qt6 plugin for mac is missing or has a problem.
