### ISSUE TITLE
Disable Menu Bar and Toolbar

### ISSUE THREAD

**Issue by NCC-Gnisha** [tsujan/FeatherPad#616]
Currently you can only disable one or other other at a given point. Would be awesome if you could disable both at the same time.

I'm guessing the reasoning behind this is so that you still have a way to access the menu if needed. Could possibly add it to the right click menu? Or even to the right side of the tab bar?

I came across this application to replace XFCE4-Notes on KDE.

**Comment by tsujan** [comment]
Thanks for your suggestion but I'm afraid I'm not a fan of extreme minimalism, as is practiced by GNOME and some GTK apps.

Right-click menu already has its separate functionality.

**Comment by tsujan** [comment]
> ... to replace XFCE4-Notes...

XFCE4-Notes is a notes app, while FeatherPad is a text/code editor. They can't replace each other.
