### ISSUE TITLE
Is it possible to disable drag-and-drop text editing?

### ISSUE THREAD

**Issue by frankspace** [tsujan/FeatherPad#617]
Problem:  if you have some text selected, and you try to select a different portion of text within that selected text without first deselecting, the selected text is dragged and moved instead of being automatically deselected in favor of the new selection.  I find this irritating, counterintuitive, distracting, and likely to cause problems without necessarily noticing.  I appreciate that some people probably like this, but I hate it.  Is there any way to turn this "feature" off?  (I would note that certain Microsoft products do allow disabling of this, but I have not been able to find any such setting in FeatherPad.)  Thank you!

**Comment by tsujan** [comment]
> Is there any way to turn this "feature" off?

No, there isn't and won't be because it's a part of basic text editing everywhere; it isn't specific to FeatherPad.

**Comment by artembunichev** [comment]
@tsujan do you know is it even possible to disable this feature from source code? I've tried to find text drag-and-drop related code in FeatherPad sources but I didn't find it. As far as I can see, this behaviour is default to QPlainTextEdit, but anyway, do you know the way how one can disable it? Maybe you've got some ideas?
Thank you in advance!

**Comment by tsujan** [comment]
> I've tried to find text drag-and-drop related code in FeatherPad sources but I didn't find it. 

As I said in my previous comment, it's deep in Qt.

> do you know the way how one can disable it?

It depends on how far a coder wants to go. You could make your text editing library and use it instead of Qt's methods. But, of course, that would require a huge amount of work. In FeatherPad, I've used Qt's classes and, on many occasions, overridden their mthods to work around their bugs, but not more.

**Comment by artembunichev** [comment]
OK, I got it. Thank you for FeatherPad!
