### ISSUE TITLE
[FR] Add option to choose background color

### ISSUE THREAD

**Issue by libalis** [tsujan/FeatherPad#624]
![FeatherPad](https://user-images.githubusercontent.com/45124869/154599358-ebba2316-7447-4e88-a84e-08b36e4b8413.png)
Either that, but then you should also be able to set the font and its color, or you automatically apply the lxqt colors.
Thank you for this great project.

**Comment by tsujan** [comment]
See Preferences → Text → Dark color scheme

Because of syntax highlighting, the colors of the view and text of a text/code editor should be limited. FeatherPad supports light and dark schemes, which are enough for all practical reasons.

**Comment by libalis** [comment]
Have completely overlooked this option, please apologize and thank you.

**Comment by tsujan** [comment]
There are many colors. See Preferences → Syntax Colors.

Each color scheme (dark vs. light) has its own set of syntax colors, which are remembered separately.

**Comment by libalis** [comment]
I meant the selection of the actual background color under "text".

**Comment by tsujan** [comment]
The background color should remain neutral because of syntax colors. The user can only set its value, inside predetermined ranges. That was my decision and I had good reasons for it (several lines of code were added for it). Other developers may have different opinions.

**Comment by libalis** [comment]
Very sad, but yes, it's your project, your decision.

**Comment by tsujan** [comment]
I assure you it isn't sad; there are practical reasons behind it.
