### ISSUE TITLE
Also make windows/mac build/installers and make available through github-release/scoop/chocolatey

### ISSUE THREAD

**Issue by hgkamath** [tsujan/FeatherPad#625]
As it uses qt build tool-chain. It should be straightforward to create a windows package.

Even though windows has notepad, a native windows build of featherpad will allow a user to have the identical look and feel-app in both linux and windows system. Featherpad and notepad do have noticeable differences in look and feel. 
A habit/custom of user is to press windows button and then type the application filename and then press keyboard shortcut-keys like ctrl-O etc. 
Presently, one has to remember to start notepad/featherpad in respective OS. One workaround is to create a shortcut (or make copy of the exe) in one of the OS to have the same application filename as the other. This does not solve the feel problem, but allows the user to rely on habit. 
```
[root@sirius ~]# cd /usr/share/applications
[root@sirius applications]# cp featherpad.desktop notepad.desktop
```
The presence of wine-notepad in Linux is a bit of an annoyance, one may remove that if one wishes.

So
a) Ensure that window build is possible
b) create a msi installer in github releases
c) create a portable zip in github releases
d) create a mac dmg installer in github releases
e) Ensure win install of package can be pulled by chocolatey or scoop bucket

**Comment by tsujan** [comment]
Thanks for your interest in FeatherPad!

As I've mentioned here and there, I have no plan to add any kind of binary or installer. I neither have time to review or check the available binaries. I prefer to use the limited time I have for making the app better and up-to-date.

My OS is Linux, which is the main target of FeatherPad. Supports for some other OS's have kindly been added by contributors, who are responsible for updating their works if needed. No binary will be provided here.
