### ISSUE TITLE
Feature: Detect Links

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#63]
and allow Actions like copy link address, open link etc - just like in terminal, nano or vi

**Comment by tsujan** [comment]
Opening a link means opening its targets. Do you mean that the target name/path should be shown instead of the link name/path? I think Kate does so.

**Comment by agaida** [comment]
no clue :) - just the fuctionality like in the terminal and terminal apps

**Comment by tsujan** [comment]
> no clue :) - just the fuctionality like in the terminal and terminal apps

I'll think about a way of adding info when a link is opened. Its coding is easy but finding a good place for it isn't ;)

**Comment by tsujan** [comment]
Done.

Now, symlinks are distinguished by a small icon in their tabs/items (on the side-pane) and their target paths can be copied by using tab/item right-click menus. Thanks for the idea!

**Comment by tsujan** [comment]
Reopen this if you don't like the current implementation or have ideas about a better one.
