### ISSUE TITLE
Featherpad does not have a man page

### ISSUE THREAD

**Issue by ArrayBolt3** [tsujan/FeatherPad#660]
I'm packaging Featherpad 1.3.0 for Lubuntu 22.10 Kinetic Kudu Alpha. During the process, it was noticed that Featherpad has no man page. It does, however, have some features that are controlled by the command line interface (visible by running `featherpad --help`), so for our packaging, it would be helpful if those features were documented with a man page.

I have experience writing man pages and am more than happy to write the man page, however I know little about how Featherpad's source code and internal build and install process works, so while I can write the page, I have no clue where on earth it would actually fit in the repository.

**Comment by tsujan** [comment]
Thank you very much for caring! Please see Help → Help; no extra man page is needed.

**Comment by tsujan** [comment]
> because of Debian policy, [which considers the lack of a man page to be a bug](https://www.debian.org/doc/debian-policy/ch-docs.html).

If Debian has such a policy, it has two choices: either it doesn't package apps without man pages (bad for Debian), or it makes fake man pages for them (bad for apps). Either way, it doesn't seem rational.

In Arch:
```
$ man dolphin
No manual entry for dolphin

$ man konsole
No manual entry for konsole

$ man qterminal
No manual entry for qterminal

......
```

In my apps, I avoid redundant files, as I avoid redundant code lines.

**Comment by tsujan** [comment]
"Bug" has a clear meaning in programming. Debian seems to have its arbitrary definition of the word "bug", and it definitely has no relation to a real bug.

Please also understand my reluctance to follow distro policies. My apps are (and will be) independent of all distros.

**Comment by ArrayBolt3** [comment]
Not only do I understand, but the execution of the policy seems so ridiculous in this particular instance that even one of the Ubuntu flavour lead developers is telling me to just override the warning and move on. Not to mention the fact that there's literally thousands of packages in Debain that ignore this particular nitpick of the policy as well. Besides, the thing's been in there for years without a man page and I'm the first one to complain about it because one utility spit out a warning.

Thank you for not being upset with me for this silliness. I'm pretty sure we're just going to override the man page warning and move on. There's way more important things for all of us to be doing than writing a fake man page.

**Comment by tsujan** [comment]
How could I be upset?! I really appreciate the job of distro maintainers like you, who care about correct packaging. I'll be happy if Debian/Ubuntu users can have latest releases from their distro repository.

Thanks again for caring, and also for your understanding!
