### ISSUE TITLE
0.7 Release

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#67]
Short question - what about a 0.7 release? Any blockers?

**Comment by tsujan** [comment]
No blocker. I just fixed some highlighting issues recently; there are more issues but if I want to fix all of them before the next release, there will be no next release ;)

So, it's a good idea. Will do it next week.

**Comment by agaida** [comment]
nice, thanks

**Comment by tsujan** [comment]
V0.7 released :)

**Comment by agaida** [comment]
@tsujan  https://ftp-master.debian.org/new/featherpad_0.7-1.html

**Comment by tsujan** [comment]
Thank you! I hope Debian users will get more familiar with this app and I'll get more bug report/feature request -- especially the first ;)
