### ISSUE TITLE
Keyboard shortcut for closing tab does not exist/cannot be added by user

### ISSUE THREAD

**Issue by severusseptimius** [tsujan/FeatherPad#678]
Basically the title. I could not find any shortcut for closing a tab.

This issue is especially frustrating when using a tiling WM because a mouse is needed just for the purpose of closing a tab.

**Comment by tsujan** [comment]
Preferences  → Shortcuts → Close

**Comment by severusseptimius** [comment]
Damn! I thought it meant closing the entire window and didn't even bother to try. 

Thank you and sorry for the useless bug report.

**Comment by tsujan** [comment]
It's OK. Marking as `invalid` is only for future reference; it doesn't mean that the user shouldn't have reported it.

The window is closed by the `Quit` action — and the app exits only when all its windows are closed (because it's a single-instance app).
