### ISSUE TITLE
Please use SPDX 2(.1) compat license short names

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#68]
Ok, SPDX 3 is out, but i would not use these notification right now. But SPDX 2 would be fine and ease the work of downstreams. Will send a PR.

**Comment by tsujan** [comment]
> Will send a PR.

Please do so! I don't know about these things; will learn them from your PR.

**Comment by agaida** [comment]
I'm learning right now - i was upset about licenses for the last years. With SPDX 2 and finally 3.0 it seems possible to at least have a system that even a noob understands - right now it was a major pain in the ass, because the expicit license was not in any form in the license headers of files. Just found that:
https://stackoverflow.com/questions/11670368/gpl-copyright-notice-when-contributing-new-files

**Comment by agaida** [comment]
you might have noticed that i'm leave out one file intentionally - encoding.cpp - imho you should apply the GPL2+ (as in the original) to that file. Just in case that anyone like the changes and would like them in the original - porting back your changes would be otherwise a GPL-Violation if the original author forget or can't relicense the modified file to GPL3+.

**Comment by tsujan** [comment]
Yes, it should be GPL2+. The first variant might even go back to an old version of Kate. Years ago, I found that simple structure, worked on some of its elements and improved it in some respects.
