### ISSUE TITLE
do not open the same document on an other tab

### ISSUE THREAD

**Issue by ralf3u** [tsujan/FeatherPad#686]
Steps to reproduce
open the file-manager
mark a txt-document
press enter (result FeatherPad will appear)
switch to the file-manager
press again enter

Result
the same txt-document will appear in a second tab

Expectation
the same document should not appear twice (in the editor Geany it does not appear twice, even if the document was changed, but not saved)

System
Lubuntu 22.10
FeatherPad 1.3.0

my FeatherPad 1.3.0 is old, so if it does not appear in FeatherPad 1.3.3, then I'm sorry for this report

**Comment by tsujan** [comment]
> the same txt-document will appear in a second tab

That's intentional. Many years ago, not being able to open a document more than once in Kate/Geany/,,, was one of their many annoyances that I didn't want in FeatherPad.

**Comment by ralf3u** [comment]
>That's intentional. Many years ago, not being able to open a document more than once in Kate/Geany/,,, was one of their many annoyances that I didn't want in FeatherPad.

OK, but maybe it could be interesting to add a checkbox as option in the `Preferences` in `Files`, something like:
`don't show the same document in an other tab`

**Comment by tsujan** [comment]
I have a document, I edit it and save the changes, but I also want to have the original document temporarily (it's very useful in coding, among other things). So, I open the original document twice. Preventing a second instance would be a useless limitation. Like in LXQt, in my own programs too, I avoid redundant options.

The second (third,...) instance is uneditable by default and has a distinguished background, so that the user immediately knows about it.

**Comment by ralf3u** [comment]
>The second (third,...) instance is uneditable by default and has a distinguished background, so that the user immediately knows about it.

I recognized that already, but an option would be good to disable this feature in the preferences.

**Comment by probonopd** [comment]
I agree. I always end up having the same file open multiple times unintentionally.

**Comment by probonopd** [comment]
This does the trick for me:

```
diff --git a/featherpad/fpwin.cpp b/featherpad/fpwin.cpp
index 24c51ab..8dba682 100644
--- a/featherpad/fpwin.cpp
+++ b/featherpad/fpwin.cpp
@@ -2746,7 +2746,7 @@ void FPwin::closeWarningBar (bool keepOnStartup)
 /*************************/
 void FPwin::newTabFromName (const QString& fileName, int restoreCursor, int posInLine, bool multiple)
 {
-    if (!fileName.isEmpty())
+    if (!fileName.isEmpty() && !alreadyOpen(fileName))
         loadText (fileName, false, false,
                   restoreCursor, posInLine,
                   false, multiple);
@@ -2834,6 +2834,41 @@ void FPwin::fileOpen()
 }
 /*************************/
 // Check if the file is already opened for editing somewhere else.
+bool FPwin::alreadyOpen (QString fileName) const
+{
+    bool res = false;
+
+    QFileInfo info (fileName);
+    bool exists = info.exists();
+    QString target = info.isSymLink() ? info.symLinkTarget() // consider symlinks too
+                                      : fileName;
+    FPsingleton *singleton = static_cast<FPsingleton*>(qApp);
+    for (int i = 0; i < singleton->Wins.count(); ++i)
+    {
+        FPwin *thisOne = singleton->Wins.at (i);
+        for (int j = 0; j < thisOne->ui->tabWidget->count(); ++j)
+        {
+            TabPage *thisTabPage = qobject_cast<TabPage*>(thisOne->ui->tabWidget->widget (j));
+            TextEdit *thisTextEdit = thisTabPage->textEdit();
+            if (thisTextEdit->isReadOnly())
+                continue;
+            QFileInfo thisInfo (thisTextEdit->getFileName());
+            QString thisTarget = thisInfo.isSymLink() ? thisInfo.symLinkTarget()
+                                                      : thisTextEdit->getFileName();
+            if (thisTarget == target
+                || (exists && thisInfo.exists() && info == thisInfo))
+            {
+                res = true;
+                thisOne->ui->tabWidget->setCurrentIndex(j); // activate the tab with the already open file
+                break;
+            }
+        }
+        if (res) break;
+    }
+    return res;
+}
+/*************************/
+// Check if the file is already opened for editing somewhere else.
 bool FPwin::alreadyOpen (TabPage *tabPage) const
 {
     bool res = false;
diff --git a/featherpad/fpwin.h b/featherpad/fpwin.h
index 940cca0..b733c64 100644
--- a/featherpad/fpwin.h
+++ b/featherpad/fpwin.h
@@ -217,6 +217,7 @@ private:
                    int restoreCursor = 0, int posInLine = 0,
                    bool enforceUneditable = false, bool multiple = false);
     bool alreadyOpen (TabPage *tabPage) const;
+    bool alreadyOpen (QString fileName) const;
     void setTitle (const QString& fileName, int tabIndex = -1);
     DOCSTATE savePrompt (int tabIndex, bool noToAll,
                          int first = 0, int last = 0, bool closingWindow = false,
```

**Comment by ralf3u** [comment]
@probonopd 
>This almost does the trick for me, but it breaks if one uses "Always open in separate windows", [...]

I don't activate `Always open in separate windows` in the `Preferences` in `Windows`, so I would like to use your code.

Is the whole code necessary to do the trick?
If I copy your code, which whole name should have the document and where should the document be located?

Thank you in advance for answers, and thank you for sharing the code.

**Comment by probonopd** [comment]
What i posted is a diff that needs to be applied to the source code like this:

```
cd FeatherPad
# Put my patch into a file "do_not_open_twice.patch"
patch -p1 < do_not_open_twice.patch
```

**Comment by ralf3u** [comment]
>What i posted is a diff that needs to be applied to the source code like this:

OK, so that means if I just use `sudo apt install featherpad`, then I can't use the code.

**Comment by probonopd** [comment]
Correct. This change has to be applied to the source code.

**Comment by tsujan** [comment]
To leave no cause for misunderstanding:

Each app has a sort of "personality", which distinguishes it from other apps of its kind. Opening the second (third, …) instance of a file as uneditable,  having separate widgets for search and replacement, supporting soft and hard text tabs at the same time, etc. are among those properties that will never change or become optional in FeatherPad.
