### ISSUE TITLE
What's he complaining about in this review?

### ISSUE THREAD

**Issue by stevenpusser** [tsujan/FeatherPad#69]
We got a great review for MX 17 from a picky reviewer: https://www.dedoimedo.com/computers/mx-17.html 

but he complained about this issue for featherpad 0.6.3:

>  The text editor (Featherpad) has a weird focus problem where it does not jump lines when you press Enter, so you have to manually scroll to the bottom of the written text. You're better off with an alternative like Mousepad, for example. 

Will this be fixed if we upgrade to the upcoming 0.7 release?

**Comment by agaida** [comment]
it is fixed as far as i can see - and yes, it was very annoying.

**Comment by tsujan** [comment]
Yes, that's already fixed. It was a side effect of some new features. V0.7 will be release next week.

And please report any issue you might find in FeatherPad here! Although it's my only text editor, I use it my way, while some issues may show up when it's used in other ways.
