### ISSUE TITLE
Unreachable code in detectCharsetKorean()

### ISSUE THREAD

**Issue by cepamoi** [tsujan/FeatherPad#695]
Hello,

This issue was found by Coverity:
In file encoding.cpp and in function detectCharsetKorean(), the code looks like this:
`if (c < 0xA1)`
`...`
`else if (c == 0xB2 || (c > 0xBD && c < 0xC1) || c == 0xD2
                         || (c > 0xDD && c < 0xE1) || c == 0xF2 || c == 0xFE)
                {
                    nonjohab = true;
                }
`
The condition in the else if can never be true because all the values in the comparisons are greater than 0xA1.
So the statement `nonjohab = true;` is never reached.

**Comment by tsujan** [comment]
Thanks a lot for telling me!

However,

 * That block was taken from an old code, as it was. I didn't change it.
 * Probably, its coder included those lines just for the sake of logic. After all, they're harmless.
 * But, most importantly, *all those functions are excluded when FeatherPad is compiled against Qt6* and will be removed when Qt5 is considered old enough. Qt6 doesn't support legacy encodings anymore — all documents should be in UTF-8 (or UTF-16 or ISO-8859-1); if not, they should be converted to UTF-8 by using appropriate tools (like `iconv`).
