### ISSUE TITLE
Multiple cursors

### ISSUE THREAD

**Issue by Ved-un** [tsujan/FeatherPad#698]
Hello.
Thank you so much for the project!

How hard would it be for you to add _multiple cursors_? 
Or does it make the code too complicated?

That would be a very useful feature  :+1: 

![multicursor](https://user-images.githubusercontent.com/48730277/209879553-da9577f0-3000-4c91-8531-2179df15760f.gif)

**Comment by tsujan** [comment]
What do you mean by multiple cursors?

**Comment by Ved-un** [comment]
Here's an example [link](https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor)

**Comment by tsujan** [comment]
Oh, you mean something like https://docs.kde.org/trunk5/en/kate/katepart/kate-part-multiple-cursors.html.

No, for now, I have no plan to add such a feature (I don't know about future). Qt doesn't provide it, and the amount of the needed code isn't justifiable for a lightweight text/code editor.

But thanks for the suggestion.

**Comment by Ved-un** [comment]
I understand, sorry for the inconvenience.

**Comment by tsujan** [comment]
> sorry for the inconvenience.

No need to be sorry; the feature you requested was quite valid.

FeatherPad is made based on Qt; it uses no external library for text editing. Some features may require replacing of fundamental Qt classes, in which case, a huge amount of extra codes might be needed — I think multiple cursors are among such features. That would contradict FeatherPad's lightweightness, among other things.

That being said, if I "magically" find an easier way, I'll add it.
