### ISSUE TITLE
Crash on closing about dialog

### ISSUE THREAD

**Issue by tsujan** [tsujan/FeatherPad#7]
I quote @OlivierDuchateau's comment at https://github.com/tsujan/FeatherPad/issues/6#issuecomment-252470676:

On FreeBSD with revision c7f6246, FeatherPad crashes too. It happened when I closed the about window with following message.

QXcbConnection: XCB error: 3 (BadWindow), sequence: 2170, resource id: 15500847, major code: 40 (TranslateCoords), minor code: 0
Bus error (core dumped)

**Comment by OlivierDuchateau** [comment]
Using the latest revision [9f667ba](https://github.com/tsujan/FeatherPad/commit/9f667ba533492d02a92a9795a64c9f7cb8b7c28b) fixes crashes, but message still persists each children widgets are opened (e.g., preferences dialog, about and so on).

**Comment by tsujan** [comment]
That message isn't specific to FeatherPad. Its source is in Qt's X11 support. I've seen it with many Qt apps.

Anyway, I'll change how dialogs are shown, either by making all of them application-modal (in which case, opening a dialog will prevent interaction with all FeatherPad windows until it's closed) or by making them windo-modal (in which case, interaction with other windows won't be blocked). I think I've encountered a Qt bug regarding the second method. Will add a commit soon.

**Comment by tsujan** [comment]
I took the middle ground with the latest commit (https://github.com/tsujan/FeatherPad/commit/e39f011c150544b9744e7b5831c5fdcd2415b039). Now dialogs allow interaction with other FeatherPad windows but on opening a *second* dialog, a proper warning is shown instead.

After that commit, no crash should happen anymore. The extra messages shown in terminal don't belong to Qt.

I close this issue. Feel free to re-open it if the problem happens again! And thanks for the report!
