### ISSUE TITLE
fp.conf:sessions tab order not respected

### ISSUE THREAD

**Issue by mzdaniel** [tsujan/FeatherPad#703]
Thank you for this text editor @tsujan.
Being using FeatherPad for a while and seems like session tab order is not being respected somehow even with a fresh installation in alpinelinux (v 1.3.5).

**Comment by tsujan** [comment]
FeatherPad doesn't order tabs (please read https://github.com/tsujan/FeatherPad/issues/503#issuecomment-813046548). You might want to use the side-pane mode.

**Comment by tsujan** [comment]
BTW, in the git source, the side-pane action also appears on the tool-bar (in addition to File menu) for being more accessible. This change will be in 1.3.6.
