### ISSUE TITLE
"Start with files of last window" does not work properly

### ISSUE THREAD

**Issue by ralf3u** [tsujan/FeatherPad#704]
Condition
"Start with files of last window" is activated in the Preferences in Files

Steps to reproduce
1: open 1.txt
2: open 2.txt
3: close FeatherPad
4: open the file-manager
5: mark 3.txt and press enter

Result
3.txt appears in FeatherPad, but not 1.txt and not 2.txt

Expectation
1.txt, 2.txt and 3.txt should appear in FeatherPad

System
FeatherPad 1.0.1 in Lubuntu 22.10

Remark
I don't know how to install FeatherPad 1.3.5; so, if this issue does not exist in FeatherPad 1.3.5, then I'm sorry for this report

**Comment by tsujan** [comment]
The option "Start with files of last window" does what its name says: if you start FeatherPad, the previous session will be opened.

I contrast, when you open files explicitly, you've started a new session with new files; FeatherPad shouldn't (and doesn't) open any other file.
