### ISSUE TITLE
How can I disable cursor blinking in the editor by editing a configuration file?

### ISSUE THREAD

**Issue by grantsimongrant** [tsujan/FeatherPad#710]
I'm using v0.15.0, my package manager only provides v0.15.0, but I don't know how to disable cursor flickering.
In addition, I chose featherpad for its powerful shortcut function.

**Comment by grantsimongrant** [comment]
I am looking forward to your answer ! @tsujan

**Comment by tsujan** [comment]
> I'm using v0.15.0,

It's very old and absolutely not recommended. The latest release is 1.3.5.

> but I don't know how to disable cursor flickering.

That's a global property called "cursor flash time". It's set by the DE and should not be overridden by apps.
