### ISSUE TITLE
[Feature Request] Option to print Filename at right side of menu bar

### ISSUE THREAD

**Issue by internet-police** [tsujan/FeatherPad#711]
Hello tsujan,
i love this editor thank you very much

i think it would be a usefull addition to have an option to show the filename at the right side of the menu bar
since there is a lot of space maybe even the whole filepath

my problem is that i usually have multiple instances of featherpad open and i lose track wich window is which file
the only way to see the filename in fullscreen is to open "save as", or i am missing something
i know it is in the window title too, but on my setup i usually dont see very much of the window titles

here is a edited screenshot to illustrate what is was thinking
![screenshot](https://user-images.githubusercontent.com/46171565/226148179-88aa9d2f-b234-4a42-83a9-a4ce727661d2.png)

i dont know how these menubar works, maybe the bar at the bottom of the screen would be an alternative

**Comment by tsujan** [comment]
You don't use tabs (you've checked "Do not show a single tab"), or the side-pane, or even the title-bar ;) 

The file names are on tabs, which have instant tooltips for showing the file paths (the tooltips have been made instant for this very reason). The same is true for side-pane items. And the title-bar shows the whole path.

Showing the whole path on the menu-bar is possible as an option, but it needs a special kind of label. I'll work on it.

**Comment by tsujan** [comment]
This is possible:

![title](https://user-images.githubusercontent.com/981076/226185262-a6fd5974-1d5d-41d6-8da0-57d8b1c0e1de.png)

If there isn't enough space, the text will be elided at the middle (as in the screenshot). To be distinguished from the menu-bar items, the text is made bold and italic.

It might take some time, but I'll implement it as an option

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/8be21eac6ea2eb44072a4e6ebae34d97e33cbb02
