### ISSUE TITLE
Crashed in Pinephone Pro within Manjaro Plasma

### ISSUE THREAD

**Issue by MarkG-108** [tsujan/FeatherPad#716]
It installed fine in Manjaro Plasma on a Pinephone Pro.  However, it will not open.  Here is the crash report:

           PID: 5541 (featherpad)
           UID: 1000 (mark)
           GID: 1003 (mark)
        Signal: 6 (ABRT)
     Timestamp: Sun 2023-03-26 17:44:10 EDT (1min 23s ago)
  Command Line: /usr/bin/featherpad
    Executable: /usr/bin/featherpad
 Control Group: /user.slice/user-1000.slice/user@1000.service/app.slice/app-featherpad-9d32879da5504e4b81da3f03946732c9.scope
          Unit: user@1000.service
     User Unit: app-featherpad-9d32879da5504e4b81da3f03946732c9.scope
         Slice: user-1000.slice
     Owner UID: 1000 (mark)
       Boot ID: 57436bdb2f84488cbe6272454c3d280a
    Machine ID: 9a5f2c4d39e94117aef4e1988eec40b8
      Hostname: manjaro-arm
       Storage: /var/lib/systemd/coredump/core.featherpad.1000.57436bdb2f84488cbe6272454c3d280a.5541.1679867050000000.zst (present)
  Size on Disk: 376.5K
       Message: Process 5541 (featherpad) of user 1000 dumped core.
                
                Stack trace of thread 5541:
                #0  0x0000ffffb92a2790 n/a (libc.so.6 + 0x82790)
                #1  0x0000ffffb925b6fc raise (libc.so.6 + 0x3b6fc)
                #2  0x0000ffffb92478b0 abort (libc.so.6 + 0x278b0)
                #3  0x0000ffffb97298e8 _Z6qAbortv (libQt6Core.so.6 + 0xb98e8)
                #4  0x0000ffffb9729d40 _ZNK14QMessageLogger5fatalEPKcz (libQt6Core.so.6 + 0xb9d40)
                #5  0x0000ffffb9e6c2b8 n/a (libQt6Gui.so.6 + 0x1bc2b8)
                #6  0x0000ffffb9e6ea68 _ZN22QGuiApplicationPrivate25createPlatformIntegrationEv (libQt6Gui.so.6 + 0x1bea68)
                #7  0x0000ffffb9e6f400 _ZN22QGuiApplicationPrivate21createEventDispatcherEv (libQt6Gui.so.6 + 0x1bf400)
                #8  0x0000ffffb97b5664 _ZN23QCoreApplicationPrivate4initEv (libQt6Core.so.6 + 0x145664)
                #9  0x0000ffffb9e72b00 _ZN22QGuiApplicationPrivate4initEv (libQt6Gui.so.6 + 0x1c2b00)
                #10 0x0000ffffba6f84e0 _ZN19QApplicationPrivate4initEv (libQt6Widgets.so.6 + 0x1884e0)
                #11 0x0000aaaab1ecc2b8 _ZN10FeatherPad11FPsingletonC2ERiPPcb (featherpad + 0x5c2b8)
                #12 0x0000aaaab1ec06a0 main (featherpad + 0x506a0)

**Comment by tsujan** [comment]
That crash is not caused by FeatherPad. You have a more basic problem, probably at the level of platform integration.

What happens when you compile FeatherPad from the source and run it from the compilation folder, without installation?
