### ISSUE TITLE
Support Windows

### ISSUE THREAD

**Issue by hgntn** [tsujan/FeatherPad#718]
Using the patch by Brecht Sanders it seems it's possible to build FeatherPad on MSYS2 MINGW64:

https://github.com/brechtsanders/winlibs_recipes/blob/main/recipes/featherpad.winlib

The problem is it seems the program is very unstable. Brecht Sanders has done his best. FeatherPad was designed with no portability in mind. To have it working on Windows, I know I have to ask it developer.

**Comment by tsujan** [comment]
>  FeatherPad was designed with no portability in mind

FeatherPad is in Qt and has been ported in macOS, Haiku OS and OS/2 — but not by me; I only support Linux.

> Brecht Sanders has done his best.

Obviously, I'm not responsible for others' works.
