### ISSUE TITLE
Highlight common C/++ stdlib types

### ISSUE THREAD

**Issue by isf63** [tsujan/FeatherPad#727]
\<stddef.h\> / \<cstddef\> define the type `ptrdiff_t`.
7 C headers, and their corresponding C++ headers, define the type `size_t`.

Technically those names are available as user-defined identifiers in the absence of such headers, but using them in that way is really bad style.

Currently they are not highlighted as types; because they are very common types in C/++ I propose they be highlighted.

**Comment by tsujan** [comment]
Yes, I wanted to add them several times but forgot later. Thanks for the reminder!

If you remember other similar cases, please tell me.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/b617d7a9d215d3db40e585320b47f14b888cc64d

**Comment by tsujan** [comment]
Also added `wint_t` (defined in `stddef.h`) with another commit.

**Comment by isf63** [comment]
Sweet, thanks!

**Comment by isf63** [comment]
How about `time_t` and `FILE`?

**Comment by tsujan** [comment]
I might add them, but there are also lots of other keywords here and there. Adding all of them would take an extra CPU time on syntax highlighting, and that might not be negligible with files that are large enough.

I'll think about it. Thanks!

**Comment by tsujan** [comment]
> One possibility is to handle all *_t

It would even take more CPU time, due to searching inside strings.

I'm adding `time_t` and `FILE` though.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/9aa6fa6b85e26b9f93833305b94f0c33e8c95652. Also, added `clock_t` and `ssize_t`.

**Comment by isf63** [comment]
Lastly I found `uint{8,16,32,64}` and `uint{8,16,32,64}_t` are highlighted but not `int{8,16,32,64}_t` (the signed versions). In fact those are more common than for instance ptrdiff_t/ssize_t/time_t. I'm thankful for the continued development.

**Comment by tsujan** [comment]
Thanks for mentioning these details! Added in https://github.com/tsujan/FeatherPad/commit/2add9ca03a415303db7139c6ac5cdb6397b9b17d
