### ISSUE TITLE
add the shortcut "enable/disable the menu-bar"

### ISSUE THREAD

**Issue by ralf3u** [tsujan/FeatherPad#732]
In the editors Kate, Geany and Visual Code one can disable/enable the toolbar & the menu-bar at the same time. Through openbox one can even disable the window-bar, so that the tab-bar is at the very top of the screen. That's really cool because then there is a minimalist design, a super efficient environment to work.

Unfortunately a shortcut to enable/disable the menu-bar does not exit in FeatherPad 1.3.5.
And unfortunately it is like this that either the menu-bar or the toolbar can be disabled, but not both at the same time, because the shortcut "enable/disable the menu-bar" does not exist.

**Comment by tsujan** [comment]
It's intentional — for reasons you could easily know if you don't assume all apps should be like each other.

**Comment by ralf3u** [comment]
It is important for me to add this line to this subject:

FeatherPad is a minimalist editor (that I like to use), but it is a pity that it does not offer a minimalist design, so without menu-bar and without tool-bar.
