### ISSUE TITLE
add a small border on the left side as option

### ISSUE THREAD

**Issue by ralf3u** [tsujan/FeatherPad#734]
On a eInk-display I can't see the cursor when the cursor is completely on the left side of the text, so at the left border of the window. With a thick text cursor I can see where the cursor is, but I have difficulties to find the cursor.
I could let appear the Line Numbers to see where the cursor is, but I don't need line numbers.
In the editor Geany and in the editor Kate there is a small border.

If a small border will be added as option, I would prefer a white border.

In the Preferences there could be in the tab `Text` this text with a checkbox:
`add a small border on the left side`

**Comment by ralf3u** [comment]
In the editor Kate and in the editor Geany it is like this, that the numbers are completely on the left side, while the small border is on the right side of the numbers. I must say that I like this order.

**Comment by ralf3u** [comment]
To the width of the small border:
When the Line Numbers are enabled and when there are only numbers from 1 to 9 in the Line Numbers, I think that this width should be enough as width for the small border.

I think this text in the Preferences would better:
`border on the left side`

**Comment by ralf3u** [comment]
>Will add it.

Cool!

**Comment by ralf3u** [comment]
Yes, it looks pretty good!

In the Preferences there could be in the tab `Text` this kind of text with a checkbox:
`Border`

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/a2efd7fa6babfa84bd7d1407d29d6ea7e49343e4

The new Option is under "Text" (almost in the middle): "Add a small margin around text"

**Comment by ralf3u** [comment]
The setting "Add a small margin around text" should have a connection to the setting "Dark color scheme", because if the setting "Dark color scheme" is activated, then the small margin around the text should also be shown in dark mode. By deactivating "Dark color scheme", the small margin around text should be white again.

**Comment by tsujan** [comment]
The margin belongs to the text view. So, its color is always the text background color.

**Comment by ralf3u** [comment]
>At last, I decided to add an optional 12-pixel margin around the whole text.

Now I can see the effect. But in my opinion the margin is too small on a eink-display because the text is to close to the border. The margin on the screenshot in https://github.com/tsujan/FeatherPad/issues/734#issuecomment-1535742180 is much bigger than the margin what I see on my display. If the margin is now 12pixel, my suggestion would be to increase the margin to 20px.
