### ISSUE TITLE
Different behaviours in the Preferences when scrolling

### ISSUE THREAD

**Issue by ralf3u** [tsujan/FeatherPad#735]
This happened to me many times: When scrolling in the Preferences I recognized later that something was changed although I was not aware that I changed it, like the tab-position. This was specially the case when I changed something in the Preferences. Yesterday I recognized that one field is different than many other fields. It is in the tab `Text` the value `Show vertical lines starting from this position`. If I move the mouse over the setting `80`, and then if I scroll upwards or downwards with the scrolling wheel of the mouse, the value stays as it should be.
This is not the case with many other values, like `Background color value`. If I move the mouse over the setting `255`, and then if I scroll downwards with the scrolling wheel of the mouse, then the value is sinking.

By the way, because there is no reset button, I would add also the default value in brackets on the right side of the values, for example like this:
`80 (default:80)`

**Comment by tsujan** [comment]
This isn't a "bug" in FeatherPad but how Qt works. You use the mouse wheel to scroll and the cursor goes over a spin-boxe. I agree that it can be annoying; will try to find a workaround for it.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/2d4e2d700c28ed5a6aeb28b1d2e6d8e007fee021

Thanks for bringing this up! It always bothered me and I wanted to add a workaround, but later I forgot.

**Comment by ralf3u** [comment]
Did you also add the default value in brackets after each value?

Reason:
Sometimes I like to play with the values, but it can be that I forgot to note the default values. If the default values are noticed in the Preferences in brackets, then I can easily reset the values manually.

**Comment by tsujan** [comment]
It had nothing to do with any value.

The problem was that spin and combo boxes were changed with the mouse wheel when they weren't focused (Qt's default). Now, they change only if explicitly focused.

**Comment by ralf3u** [comment]
>The problem was that spin and combo boxes were changed with the mouse wheel when they weren't focused (Qt's default). Now, they change only if explicitly focused.

Yes, I know. The default values have nothing to do with this issue. I just wanted to mention it. If you want, I can open a new issue for that.

**Comment by tsujan** [comment]
There's no issue to fix. The default values aren't sacred.

If you want to reset all defaults, close FeatherPad and remove `~/.config/featherpad/fp.conf` — editing that file with FeatherPad won't work.

**Comment by ralf3u** [comment]
I just recognized that instead of brackets it is better to have a Reset-button for all values of the Preferences. I will open a new issue for that.

**Comment by tsujan** [comment]
> I will open a new issue for that.

Please don't; it'll be closed. Read above.

**Comment by ralf3u** [comment]
>If you want to reset all defaults, close FeatherPad and remove ~/.config/featherpad/fp.conf

Ah! OK.

**Comment by tsujan** [comment]
BTW, what did you mean by "brackets"? Which brackets?

**Comment by ralf3u** [comment]
Instead of this:
Show vertical lines starting from this position: 80
The idea was to have it like this, so one know what the default value is:
Show vertical lines starting from this position: 80 (default 80)

But if there is a reset for all values (what can be realized by removing ~/.config/featherpad/fp.conf), then this solution is even better than the idea with the brackets.

**Comment by tsujan** [comment]
The default values of most spin-boxes aren't important. Those which may be important are already handled. For example, if you put 0 in front of "Start with size", it'll be restored to default (700×500).

There may be only two other spin-box whose default values can be important to the user ("Whitespace color value" and "Show vertical lines..."). I'll add a "Default" inside them.

**Comment by ralf3u** [comment]
>> I will open a new issue for that.
>
>Please don't; it'll be closed.

What about the idea to add a new tab in the Preferences that is called `Reset`?
In that tab there could be just this text:
`To reset all values of the preferences, close FeatherPad and remove ~/.config/featherpad/fp.conf`.
So everyone is informed.

It should be not so complicated to code than a reset-button.

**Comment by tsujan** [comment]
A reset button makes sense only where the default values are practically important, e.g., syntax colors have a "Default" button which resets them, because the user's chosen colors may not be readable to him.

Cluttering GUI's with redundant buttons isn't a good idea, although some devs may do it, like KDE devs.

**Comment by ralf3u** [comment]
And what about the tab `Reset` with the text mentioned in https://github.com/tsujan/FeatherPad/issues/735#issuecomment-1537168527?

**Comment by tsujan** [comment]
→ my previous comment

**Comment by ralf3u** [comment]
I'm not talking about a reset-button. I'm talking about the possible tab `Reset` where everyone can read how a reset can be executed.

**Comment by ralf3u** [comment]
This is how the window of the Preferences could look like when the tab `Reset`is active:

Window Text Files Shortcuts Syntax Colors Reset

To reset all values of the preferences, close FeatherPad and remove ~/.config/featherpad/fp.conf.

**Comment by tsujan** [comment]
Any app is will be reset if its config folder is renamed/removed while it isn't running.

I'm adding code so that if the user empties any spin-box, its value will be reset to its default. More than this would be an overkill.
