### ISSUE TITLE
Change color of 'Line Numbers' so that there is no black background-color on eInk-displays

### ISSUE THREAD

**Issue by ralf3u** [tsujan/FeatherPad#736]
On a eInk-display in the most cases I don't use dark mode, because I use the eInk-display without any light, what means that when I disconnect the eInk-display from the notebook, the image is exactly the same like when the eInk-display is connected to the notebook.

At the moment in FeatherPad 1.3.5 the Line Numbers are shown like this on the display of the notebook:

background-color: #000
font-color: #fff
highlighted background-color: #ffeb82
highlighted font-color: #000

On a eInk-display in Text-mode (Text-mode has only one color, namely black) the Line Numbers are shown like this in FeatherPad:
background-color: black.
highlighted line: font-color is black; background-color: no color
I would prefer that it would be shown like in Geany or Kate.

In the editor Geany 1.38 and in the editor Kate 22.12.13 the line numbers are shown like this on the eInk-display in Text-mode:
The font-color of the numbers is black.

In Geany on the notebook-display Line Numbers are shown like this:
background-color: #edeceb
font-color: #000
no highlighting

In Kate on the notebook-display Line Numbers are shown like this:
background-color: #f0f0f0
font-color: #a0a0a0
highlighted background-color: #fff
highlighted font-color: #000

If the background-color will be changed in FeatherPad, so that it is more gray, I can check if the gray-color is shown as white on the eInk-display in Text-mode.

**Comment by tsujan** [comment]
> I would prefer that it would be shown like in Geany or Kate.

We had this talk several times and you know my reply.

**Comment by ralf3u** [comment]
Maybe I didn't explain it so good in my report, so I will try again:

The best view on a eInk-display (when Text-Mode is activated) is when the black color is used as less as possible, because in Text-Mode the color black is the only color. That means to avoid black background-color as much as possible.

So, if the background-color of Line Numbers would be changed from black to a special gray (see for example Kate or Geany) and if the font would be changed from white to black, there would be no black background-color any more on a eInk-display.

**Comment by tsujan** [comment]
I understand it. But if a display can't show dark backgrounds correctly, it has a problem. That's too personal to deserve an option. The colors have been chosen with care to distinguish the line numbers from the main text as clearly as possible.

BTW, I dislike Kate's GUI and its number strip. And if other text editors were usable to me, I wouldn't make another one.
