### ISSUE TITLE
featherpad is really long as application name

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#74]
is it possible to shorten it to fpad? Right now i have a symlink featherpad -> fpad in debian packaging. Really useful for cli usage.

**Comment by tsujan** [comment]
I'd noticed `fpad` in the deb package and thought it was a good idea. I prefer to keep the binary `featherpad` but will try to add the symlink `fpad` with installation.

As usual, a good idea :)

**Comment by agaida** [comment]
thanks :)

**Comment by tsujan** [comment]
Now, the symlink `fpad` is added.

After finding no reliable way to make a symlink only with `qmake` variables and thinking about a switch to `cmake`, I asked myself, "why not using `coreutils` directly?" After all, `qmake` uses it.

I tried with Arch's `makepkg` and the symlink was created correctly inside the archive. Your test with Debian's `dpkg` would be appreciated.
