### ISSUE TITLE
Featherpad wont open files as tabs

### ISSUE THREAD

**Issue by JefMcD** [tsujan/FeatherPad#751]
OS: Ubuntu 22.04.02
Gnome Version: 42.5
Windowing System: Wayland
File Manager: Files by Nautilus

Ive installed a fresh Ubuntu 22.04.02 system then installed Featherpad.

On my old system (Kubuntu 22.04.01) Featherpad opened files as tabs which was great. But now it always opens them as new windows which is not great.
I think Kubuntu is based around KDE and normal Ubuntu is Gnome so Im guessing that might be the problem but Im no expert.

Running Featherpad from the terminal produced this message
"Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway."

You can see it in action here
https://rumble.com/v2yzxng-featherpad-not-opening-tabs.html

**Comment by tsujan** [comment]
Most probably, you have an outdated version of FeatherPad. The warning message you pasted also shows that you may have an old version of GNOME. If you want a better experience with Wayland, you'll need the latest stable versions of apps — which aren't provided by LTS distros.

FeatherPad opens all files as tabs by default — whether under X11 or under Wayland —. unless the option "Always open in separate windows" is checked. The latest release is 1.4.1.

**Comment by JefMcD** [comment]
I just installed Ubuntu 22.04.2 Yesterday and I installed Featherpad today. Everything is up to date and I have the latest versions. I havnt changed any settings on Featherpad. Its not opening in tabs its opening new instances in a new window as demonstrated. Thats its default out-of-the-box behaviour. If its abandonware thats fine, no probs.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by tsujan** [comment]
> I just installed Ubuntu 22.04.2 Yesterday

Ubuntu 22.04.2 is an LTS distro. It doesn't matter when you install it; LTS (Long-Term Support) is old by definition.

> Everything is up to date

The version provided by Ubuntu 22.04 is [1.0.1](https://packages.ubuntu.com/jammy/featherpad), which is very old. See Help → About.

**Comment by JefMcD** [comment]
The appeal of Featherpad (to me anyway) was that it was lightweight and no fuss. Its a shame its lost that aspect, but I dont have time to get into all the minutia and tinkering about to get it working,   But no worries, Text Editor does much the same thing but doesnt open a new window every time, so I'll go with that.

**Comment by JefMcD** [comment]
Btw previously I was using Kubuntu which uses an earlier version of Ubuntu (22.04.01) and it was working fine on that. Like I say no worries

**Comment by tsujan** [comment]
> Text Editor does much the same thing

I'm not saying 1.0.1 can't be used. But there have been so many changes and fixes since 1.0.1 (see https://github.com/tsujan/FeatherPad/releases).

> Btw previously I was using Kubuntu which uses an earlier version of Ubuntu (22.04.01) and it was working fine on that. 

Older versions of Kubuntu might use an X11 session, while Ubuntu is based on GNOME, which has a Wayland session by default. The issue you see is about a minimal Wayland support in 1.0.1. That has changed in recent versions of course.

**Comment by JefMcD** [comment]
Just out of curiosity, how comes the Ubuntu version is so out of date? There's a ton more people use Ubuntu that anything else and there's easier options. Maybe I missed it but I couldnt find a .deb either so the only way to install it was to download the source and install al the dependencies and compile it all. No way. There's not many people willing to go down that road.

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by tsujan** [comment]
> how comes the Ubuntu version is so out of date?

LTS (mentioned above).

> There's a ton more people use Ubuntu

They may accept it as it is. And there's a ton using other distros. Anyway, let's not talk about distros here. I mentioned "LTS" because it's a general concept and implies "old".

**Comment by JefMcD** [comment]
Ubuntu 22.04.02 is the current version mate. Thats not old thats 'Current' and 'Up to date'

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------

**Comment by tsujan** [comment]
Not the first time an Ubuntu user can't read...
