### ISSUE TITLE
Feature request: remove duplicate lines

### ISSUE THREAD

**Issue by tim78245** [tsujan/FeatherPad#761]
Pretty much the title.

Imagine I had the following text in the file:

```
hello
world
hello
world
world
```

If I hit Edit > Remove Duplicate Lines it would become:

```
hello
world
hello
world
```

**Comment by tsujan** [comment]
The number of possible text modifications is virtually infinite. Your proposed modification is among those which are usually done by scripting.

Moreover, it may be useful only for special kinds of text — it could easily become very CPU-intensive with heavy files containing long lines.
