### ISSUE TITLE
Make "Show hidden files" activated by default, and/or provide permanent configuration option to do so

### ISSUE THREAD

**Issue by Abdull** [tsujan/FeatherPad#764]
(using `FeatherPad 1.4.1`, the latest *FeatherPad* version as of this writing)

In the *Open file...* and *Save as...* dialogs, dotfiles ("hidden files", e.g. `~/.bashrc`, and including ".dotdirectories" such as `~./config/`) are hidden by default.

In my opinion, in general hiding files doesn't fulfil a purpose, and hiding files is just confusing and leads to wrong assumptions ("why is there no file?",  "oh, this directory is empty, so I can remove it", etc.).

**I think it makes sense to *activate* the *Show hidden files" option by default.**

**Also, it would be great if there was a configuration option in `~/.config/featherpad/fp.conf` / `XDG_CONFIG_HOME/featherpad/fp.conf` / the GUI *Options* > *Preferences* to set the default hidden file visibility state.**

Or maybe there is a more general (Qt?) configuration setting which could be used instead to achieve this?

Related issue: #19

**Comment by tsujan** [comment]
> Or maybe there is a more general (Qt?) configuration setting

For Qt's default file dialog, it's `~/.config/QtProject.conf`. But, as mentioned above, it doesn't accept any key for showing hidden files — an old issue no one has paid attention to, perhaps because Qt devs assume that main DEs have richer native file dialogs (which is the case).
