### ISSUE TITLE
Ctrl + Home/End shortcuts not working

### ISSUE THREAD

**Issue by birdie-github** [tsujan/FeatherPad#766]
In pretty much all visual text editors these shortcuts mean jumping to the start or bottom of the document. They don't work in featherpad.

Please add.

**Comment by tsujan** [comment]
> They don't work in featherpad.

They do.

**Comment by birdie-github** [comment]
I swear to God they didn't work a minute ago. I've restarted the application and now they work.

Sorry for the noise :(

**Comment by tsujan** [comment]
Also, see Menu-bar → Help → Help → Useful Extra (Hidden) Shortcuts
