### ISSUE TITLE
Feature request: easy date/time stamp of files?

### ISSUE THREAD

**Issue by stevenpusser** [tsujan/FeatherPad#77]
Had this come up on the MX Linux forums today. I think they want a key binding to add a date/time stamp to the file name.

A feature I would like to see is a display of the current character position of the cursor in the current line, in the statistics bar.

**Comment by tsujan** [comment]
> a date/time stamp to the file name.

With the last commit, each view tracks the modification time of its file. I added that for another reason but the time can be made available to the user. That being said, I don't understand what you mean by "adding date/time stamp to the file name". Could you please be more specific?

> A feature I would like to see is a display of the current character position of the cursor in the current line, in the statistics bar.

On the one hand, I don't want to make the status-bar more occupied than it is; on the other hand, those kinds of information that continuously change aren't good for the statusbar (high CPU usage).

If you want the cursor position to be remembered, you could add the file to a session (see the session dialog) and always open it from the session dialog. The cursor positions of all documents that are opened from the session dialog will be remembered.

**Comment by tsujan** [comment]
I might add the cursor position info to the right-click menu. Would that be OK?

**Comment by stevenpusser** [comment]
That would be fine.  I just would an easy way to see it.

I think I got the time/date thing wrong.  They wanted an easy way (hotkey?) to insert the current time and or date into the text itself, like Pluma has.  Different format choices for that like Pluma would be even better.

**Comment by tsujan** [comment]
Oh, by format you meant x/y/z, pm, etc. OK, that's meaningful. I'd mistaken the word "format" with formatted text.

**Comment by stevenpusser** [comment]
Thanks for the responses!  Also, congratulations for having Featherpad in the Debian Sid repo now!

**Comment by tsujan** [comment]
I added an option to show the cursor position on the right side of the statusbar, separate from its main label. A screenshot:

![cursor](https://user-images.githubusercontent.com/981076/35777904-4ea58f22-09cb-11e8-9aa3-aef793945916.png)

The option (disabled by default) is at `Preference → Window → Show cursor position on status bar`. Statusbar texts are all selectable and can be copied.

Your tests would be appreciated.

Later, I'll see how to handle date and time.

**Comment by stevenpusser** [comment]
Actually, I, and I would guess agaida, would just like the character position form the beginning of the current line, not the total character count from the beginning of the document, if that's not really hard to implement.  Debian policy is to have text files in the packages with lines at 80 characters or less as much as possible, so that they would be readable on a 80 character console...so it helps to know where we are in a line if we are writing a description of a package, for example, or cutting up code with backslashes to fit in that limit in the debian/rules file. That vertical line on the right in Atom mentioned in the "missing things" issue would be another helper with that.

**Comment by tsujan** [comment]
> if that's not really hard to implement. 

That's so easy to implement. Now I understand why you want that number.

> That vertical line on the right in Atom mentioned

Will try to add them later, after implementing enforced syntax, as @agaida explained at https://github.com/tsujan/FeatherPad/issues/78

**Comment by tsujan** [comment]
All done, except for the date. Please test and tell me if something (other than the date) is missing.

I'll think about the date insertion soon. The insertion itself is trivial but the GUI needs some thought.

**Comment by stevenpusser** [comment]
The character position readout is working fine.

I built from today's git and enable the vertical guideline feature at 80 char, but it doesn't show up after restarting, no matter what monospaced font I use. I also tried the light and dark themes, and in a Stretch based distro with and without qt5ct.  Nothing at all shows up when I start fpad from the command line.

**Comment by tsujan** [comment]
> I built from today's git and enable the vertical guideline feature at 80 char, but it doesn't show up after restarting

Is showing of white-spaces disabled in Preferences? I guess the source you tried didn't include https://github.com/tsujan/FeatherPad/commit/44c2edab17762d16c57044ccc1c83bac8a34b38c; did it?

Another thing: the vertical line is only for syntax highlighting, i.e. it appears only when a file with a supported programming language is opened. I saw no reason to enable it with a normal text because the position button is enough for it. Its check-box also belongs to the syntax highlighting option.

**Comment by tsujan** [comment]
> Nothing at all in terms of messages shows up when I start fpad from the command line.

Oh, most probably, that's about the second case I mentioned above. See it in this way:

All this is about *syntax*. Therefore, there should be a syntax in the first place -- a normal text doesn't have a syntax, by definition but a debian `control` file does, for example, and FeatherPad sees that.

I've intentionally set those check-boxes as sub-options of "Highlight syntax by default" in Preferences to show that they're about syntax highlighting.

**Comment by stevenpusser** [comment]
Yes, I just opened up a control file, and the guideline does show up. OK, it's working as intended. Nice!

**Comment by tsujan** [comment]
> OK, it's working as intended

Thanks for the confirmation!

> here's what repos now have Featherpad

And thanks for the link!

**Comment by agaida** [comment]
omfg - my name in devuan, shame on me :D

**Comment by tsujan** [comment]
> omfg - my name in devuan, shame on me :D

Not important! The important thing is attaching that suspicious file at https://github.com/tsujan/FeatherPad/issues/82  ;)

**Comment by tsujan** [comment]
To not add to the weight of FP, I'll implement a minimalist date-and-time pasting only in the context menu and without shortcuts but configurable, like these (the format could even contain `\n`):

![context_menu](https://user-images.githubusercontent.com/981076/35919016-f6d548f4-0c28-11e8-86ea-a1c384fa47fa.png)
![preferences](https://user-images.githubusercontent.com/981076/35919018-fce59cb2-0c28-11e8-866f-183c3bae6206.png)

**Comment by tsujan** [comment]
Added it to the Edit menu too, with the fixed shortcut `Ctrl+Shift+V`.

I'll test the recent changes for 2 or 3 weeks -- without adding a new feature -- and, if no bug is reported, will release 0.7.1.
