### ISSUE TITLE
Inclusion of carriage return in highlighted char count

### ISSUE THREAD

**Issue by transmitthis** [tsujan/FeatherPad#772]
Using MX Linux, which comes with featherpad, Latest version, on live USB system.

Highlighting one line and looking at the doc properties CTR+Shift+D Shows the correct count

Issue? 
Highlighting more than one line increases the count of characters, I'm assuming that's the carriage return being counted.

Is this expected or can it be fixed?

Would also be great if there was a refresh button on viewing the properties.

No issue if there is no development or inclination, as there are other similar apps I could include in my live build - just shame not to use featherpad, as it is there and almost does what's needed.

**Comment by tsujan** [comment]
"newline" *is* a character; it can even be copied (alone or among other characters), pasted into the search bar or replacement dock, and searched or replaced.

**Comment by transmitthis** [comment]
Thanks for the Reply Tsujan
Shame you felt it should be closed without chance to respond, but whatever.

Just looked at the default "text editor" that comes with Tails.
They show these Document Statistics. for both selected and document

Characters (with spaces)
Characters (no spaces)

Don't need Notepadd++ functionality here (where we can display spaces and returns) just a count of the visible characters.

If you don't think users would like the option of knowing the actual number of visible characters selected that's fine - I'm using tails now anyway so it's mute point for me.

Still I thought I'd be asking for it the other way round, and being told no one wants invisible spaces or returns counted. :)

**Comment by tsujan** [comment]
Reports are closed when there's no bug to fix. Comments can be added to closed reports, as you already know.
