### ISSUE TITLE
Your editors are sorely lacking three buttons

### ISSUE THREAD

**Issue by T-Shilov** [tsujan/FeatherPad#773]
Dear friend,

It is with great pleasure that I use your two editors **FeatherPad** and **FeatherNotes**.
They're great in work!
But unfortunately, for comfortable work, they are sorely lacking three buttons on the tollbar: **Cut-Copy-Paste**
Because of this disadvantage, me have to make an excess right-click, which is extremely inconvenient.

Therefore, there is a big request to you:
- **please add three beautiful Cut-Copy-Paste buttons**, which are, for example, in the Kate editor,

Thank you so much for understanding the situation!
All the best!

![edit-cut](https://github.com/tsujan/FeatherPad/assets/61428202/24d2e0ea-9ca4-4e6b-93a3-a68e66a739af) ![edit-copy](https://github.com/tsujan/FeatherPad/assets/61428202/3fedd551-c9a6-4039-b5d3-fb56f525f53a) ![edit-paste](https://github.com/tsujan/FeatherPad/assets/61428202/fa63dd61-d61e-4f7e-85bd-078fe9c6ab5f)

![Kate](https://github.com/tsujan/FeatherPad/assets/61428202/88f6546f-81a6-4800-9872-3d7df7508749)

**Comment by tsujan** [comment]
> have to make an excess right-click

Most people use the best known shortcuts in all operating systems, i.e., `Ctrl+X`, `Ctrl+C` and `Ctrl+V` —  because they're typing.

I avoid cluttering the GUI.
