### ISSUE TITLE
CMake errors:  FindQt6.cmake, CMAKE_MODULE_PATH, XKB, Hunspell, CMAKE_PREFIX_PATH, cmake_minimum_required, FindHUNSPELL.cmake

### ISSUE THREAD

**Issue by jlj2** [tsujan/FeatherPad#774]
Building under a **Qt5** environment on a Debian derivative tracking Bookworm (stable) on aarch64 architecture, the following dependencies were ensured to be installed, inspired by the _INSTALL_ page:

```
sudo apt install cmake g++ libx11-dev libxext-dev qtbase5-dev libqt5x11extras5-dev libqt5svg5-dev libhunspell-dev qttools5-dev-tools
```

Then, choosing to build, say, into an `/opt` folder in one's home directory:

```
cd ~/opt
git clone https://github.com/tsujan/FeatherPad.git
cd FeatherPad/featherpad
mkdir build && cd build
cmake ..
```

Errors began:

```
[...]
CMake Error at CMakeLists.txt:9 (find_package):
  By not providing "FindQt6.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Qt6", but
  CMake did not find one.

  Could not find a package configuration file provided by "Qt6" (requested
  version 6.2.0) with any of the following names:

    Qt6Config.cmake
    qt6-config.cmake

  Add the installation prefix of "Qt6" to CMAKE_PREFIX_PATH or set "Qt6_DIR"
  to a directory containing one of the above files.  If "Qt6" provides a
  separate development package or SDK, be sure it has been installed.
[...]
```

As **qt6** hadn't been installed, I tried _INSTALL_'s proposal:

```
cmake .. -DENABLE_QT5=OFF
```

No joy, so tried to install various **qt6** packages.  Some may or may not have been necessary:  **qt6ct** although [helpfully inspired](https://github.com/tsujan/FeatherPad/issues/640#issuecomment-1186459168) and warned not to be used under LXQt or KDE; and **qt6-tools-dev**;  but **qt6-base-dev** was a [game changer](https://stackoverflow.com/questions/71448984/cant-build-qt6-with-cmake-on-ubuntu), suggested for Ubuntu; and therefore perhaps the _INSTALL_ file could be changed to propose **qt6-base-dev** (and **qt6ct** and **qt6-tools-dev**?) for **Qt6** builds under Debian:

```
sudo apt install qt6-base-dev
```

Then, a different error appeared:

```$ cmake ..
[...]
CMake Error at CMakeLists.txt:9 (find_package):
  Found package configuration file:

    /usr/lib/aarch64-linux-gnu/cmake/Qt6/Qt6Config.cmake

  but it set Qt6_FOUND to FALSE so package "Qt6" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find required Qt component "Svg".
```
  
**qtdeclarative6-dev** was suggested for a [somewhat related Ubuntu issue](https://askubuntu.com/a/1375070), so searching within this Debian derivative...

```
$ apt-cache search qt | grep declar          
qt6-declarative-dev - Qt 6 declarative development files
qt6-declarative-dev-tools - Qt 6 declarative development programs
```

...Therefore tried:-

```
sudo apt install qt6-declarative-dev qt6-declarative-dev-tools
```

...but this led **CMake** to a similar error.  Then, **QtWebView** was [considered](https://orum.qt.io/post/737438).  I therefore searched again:

```
$ apt-cache search  qtwebv
qml-module-qtwebview - display web content in a QML application
qml6-module-qtwebview - Qt 6 WebView QML module
qtwebview5-doc - display web content in a QML application - Documentation
qtwebview5-doc-html - display web content in a QML application - HTML Documentation
qtwebview5-examples - display web content in a QML application - Examples
```

One of those packages, **qml6-module-qtwebview**, indeed resolved the error, so that might be also be helpful to be considered as an additional dependency under Debian (the earlier packages might have been necessary also:  **qt6-declarative-dev** **qt6-declarative-dev-tools**).

Now, that error got cleared, but there were two other errors:

```
$ cmake ..
[...]
-- Could NOT find XKB (missing: XKB_LIBRARY XKB_INCLUDE_DIR) (Required is at least version "0.5.0")
-- Could NOT find Qt6Svg (missing: Qt6Svg_DIR)
[...]
```

Installing some **Qt6 svg** packages made the second error clear...

```
sudo apt install libqt6svgwidgets6 qt6-svg-dev
```

...and therefore **libqt6svgwidgets6** and **qt6-svg-dev** may be additional dependencies currently required to be considered to build **Featherpad** in Debian.

Next, regarding the _XKB_ error, [one webpage](https://github.com/sddm/sddm/issues/79#issuecomment-21830821) under somewhat comparable circumstances hinted to searching for packages providing `xkb.h` :

```
$ apt-file search xkb.h
enlightenment-dev: /usr/include/enlightenment/e_xkb.h
fcitx-libs-dev: /usr/include/fcitx/module/xkb/fcitx-xkb.h
fcitx-libs-dev: /usr/include/fcitx/module/xkb/xkb.h
libwpe-1.0-dev: /usr/include/wpe-1.0/wpe/input-xkb.h
libxcb-xkb-dev: /usr/include/xcb/xkb.h
```

But installing one of these didn't clear the error when attempting **CMake**:

```
sudo apt install libxcb-xkb-dev
```

I am not clear about my notes, but apparently [another webpage](https://github.com/sddm/sddm/issues/79#issuecomment-21827110) was helpful to resolve the _XVB_ error:

```
sudo apt install libxkbcommon-dev libxkbfile-dev
```

At about this point, _cmake_minimum_required_ and _Hunspell_ errors needed to be addressed:

```
$ cmake .. -DENABLE_QT5=OFF   # or was it "cmake .." at this point?
[...]
  No cmake_minimum_required command is present.  A line of code such as
    cmake_minimum_required(VERSION 3.25)
  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
[...]
CMake Error at CMakeLists.txt:18 (find_package):
  By not providing "FindHUNSPELL.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "HUNSPELL",
  but CMake did not find one.
  Could not find a package configuration file provided by "HUNSPELL"
  (requested version 1.6) with any of the following names:
    HUNSPELLConfig.cmake
    hunspell-config.cmake
  Add the installation prefix of "HUNSPELL" to CMAKE_PREFIX_PATH or set
  "HUNSPELL_DIR" to a directory containing one of the above files.  If
  "HUNSPELL" provides a separate development package or SDK, be sure it has
  been installed."
[...]
```

For this, **qtcreator** was [encountered](https://doc.qt.io/qt-6/cmake-get-started.html):  _"[...] There are different ways you can tell CMake about Qt, but the most common and recommended approach is to set the CMake cache variable CMAKE_PREFIX_PATH to include the Qt 6 installation prefix. Note that Qt Creator will handle this transparently for you. [...]"_

```
sudo apt install qtcreator
```

**qtcreator** may have been necessary, but that didn't resolve the error.  I then realized that **hunspell** was missing ...even if **hunspell-en-us** had been previously installed!

```
sudo apt install hunspell
```
Various pages in this github repository suggest that **pkgconfig** and **pkg-config** would help resolve **Hunspell** errors under Debian, but they didn't resolve the issue here, despite both being installed from the outset;  that the current platform is a Debian derivative may not be relevant. 

N.B.:  The only `.cmake` file found in this release was at `FeatherPad/cmake/Modules/FindHUNSPELL.cmake` .  I think that @tsujan  would know whether whether preparing  `HUNSPELLConfig.cmake` and `hunspell-config.cmake` files for this _Modules_ directory in the future would be required or not.

Trying to specify the path to **hunspell** in the cli, as kindly proposed in [a different case](https://stackoverflow.com/a/33318071), didn't help here to specify the location of one of the requested files (`/home/myusername/opt/FeatherPad/cmake/Modules/FindHUNSPELL.cmake`):

```
cmake .. -DENABLE_QT5=OFF -D CMAKE_PREFIX_PATH=/home/myusername/opt/FeatherPad/cmake/Modules/ .
```

Other variations, such as the following didn't help either, which I attempted only as a layman:

```
export HUNSPELL_DIR=/usr/include/hunspell
```

Those two _CMake_ errors only resolved when adding two lines to `/home/myusername/opt/FeatherPad/featherpad/CMakeLists.txt`:-

(1) **The solution for cmake_minimum_required was reported clearly enough:**

```
A line of code such as
    cmake_minimum_required(VERSION 3.25)
  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.
```

So I added the line `cmake_minimum_required(VERSION 3.25)` that is somehow missing in that `FeatherPad/featherpad/CMakeLists.txt` file in the current release.  Note to the developer:  There is another file, found later and by the same name, that does supply this line at the top:  it is in the **parent folder** instead (`/home/myusername/opt/FeatherPad/CMakeLists.txt`), and **CMake** didn't seem to have picked that up.

(2)  **To help specify _CMAKE_MODULE_PATH_, I noted that `FeatherPad/featherpad/CMakeLists.txt` declares _CMAKE_MODULE_PATH_ in relation to _CMAKE_SOURCE_DIR_:**

```
set(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${CMAKE_SOURCE_DIR}/cmake/Modules/")
```

So I tried to crudely set where _CMAKE_SOURCE_DIR_ is on my installation;  the developer may know whether such a line may be required, prepared in a more appropriate way than what I tried, maybe with a reference to the parent directory, which is the _CMAKE_SOURCE_DIR_:

```
set(CMAKE_SOURCE_DIR "/home/myusername/opt/FeatherPad/")
```
For clarity, the four first lines of '/home/myusername/opt/FeatherPad/featherpad/CMakeLists.txt` then looked like:

```
cmake_minimum_required(VERSION 3.25)
set(QT5_MINIMUM_VERSION "5.15.0")
set(QT6_MINIMUM_VERSION "6.2.0")
set(HUNSPELL_MINIMUM_VERSION "1.6")
set(CMAKE_SOURCE_DIR "/home/myusername/opt/FeatherPad/")
```

**CMake** then completed 100% although it started off with a warning:

```
cmake ..
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

```

The Make stage proceeded ok then too.  Maybe those dependencies and added lines might help someone.  Thanks for your software, @tsujan !

**Comment by aragon5956** [comment]
you have to install with library : `sudo apt-get install qt6-base-dev
` answer me if you have an another question
