### ISSUE TITLE
Avoid syntax highlighting for .log files

### ISSUE THREAD

**Issue by maplee0** [tsujan/FeatherPad#777]
Hello!
Now highlighting is applied to time parts in .log files
For example:
14:26 - is in green
33:31.30 - for some reason 33:31 is in green
Would be nice to disable highlighting for .log files.
Thanks!

**Comment by tsujan** [comment]
> Would be nice to disable highlighting for .log files.

It won't happen.

The user can check "Support syntax override" and choose "Normal" in the syntax button.
