### ISSUE TITLE
Set text direction

### ISSUE THREAD

**Issue by avidseeker** [tsujan/FeatherPad#780]
On Firefox, it's possible to force a text direction for input boxes using Ctrl+Shift+X as a shortcut.
This is essential when editing Bidirectional text documents.

* Relevant: https://doc.qt.io/archives/qtjambi-4.5.2_01/com/trolltech/qt/core/Qt.LayoutDirection.html
* https://github.com/openwebos/qt/blob/master/examples/declarative/righttoleft/layoutdirection/qml/layoutdirection/layoutdirection.qml

**Comment by tsujan** [comment]
The text direction is determined by Qt, based on the text, for RTL, LTR and mixed texts. And it's correct:

![text_direction](https://github.com/tsujan/FeatherPad/assets/981076/212482ba-71c7-4b6c-b3a4-ad1882e0e2c6)

**Comment by avidseeker** [comment]
Yes. The final result is displayed correctly, but while editing, it is useful to *temporarily* force a certain direction. Please take a look on: https://gitlab.gnome.org/GNOME/gtk/-/issues/173

**Comment by tsujan** [comment]
A rich-text editor, like that of [FeatherNotes](https://github.com/tsujan/FeatherNotes), should have not only actions for setting text direction but also other actions for text alignment and more.

A plain-text/code editor should work with text directions that naturally come with paragraphs/blocks/lines (different names for the same thing) because there's no way of saving such info inside plain-text.

**Comment by avidseeker** [comment]
> there's no way of saving such info inside plain-text.

Such info need not, and in fact should not, be saved inside plaintext. Again, it's a temporary forcing of direction. Try pressing `Ctrl+Shift+X` in Firefox location bar. Here's a demonstration of Windows old Notepad having this feature (it's not rich editor):

https://github.com/tsujan/FeatherPad/assets/67508272/d075ae7a-2d38-4013-ba4f-93827eb8506d

**Comment by tsujan** [comment]
> try pressing Ctrl+Shift+X in Firefox...

I understood what you said. Actually, FeatherPad had a shortcut for that ages ago, because Qt had a bug. I removed the shortcut as soon as I worked around the bug. There's simply no need to such a thing — whether devs of other apps like to have it or not, that's up to them.
