### ISSUE TITLE
Confusing symbol in the preferences dialog

### ISSUE THREAD

**Issue by sdicke** [tsujan/FeatherPad#79]
In my KDE setup (Debian, Breeze Dark theme) there is a rubbish bin symbol on the close buttom in the preferences dialog. That is the same with the build from Debian repository and a buiild from this repository`s source code. Maybe that is a bit confusing.

**Comment by tsujan** [comment]
Yes, it was so senseless! I changed it to `dialog-close` in the latest commit (among other things).

Thanks for reporting!
