### ISSUE TITLE
FeatherPad's window size change interferes with WM's window placement instruction

### ISSUE THREAD

**Issue by w-jablonski** [tsujan/FeatherPad#792]
Not sure this is a valid bug report

I use SwayWM therefore Wayland. My config for `app_id="featherpad"` goes `move position 970 300, resize set width 235 height 590`. FeatherPad's window obeys the size set by WM and gets placed around where it should, although a bit off. More to the point if I change values in FeatherPad's `Start with this size:` config option, the window will now be mis-placed by the difference in the value. And similarly when using option `Remember window size on closing`, the newly opened window will be also mis-placed if I have resized the previous window. Again, new window's size obeys WM's setting.

I would expect FeatherPad to allow the WM to fully override it's window placement logic.

BTW ♥️♥️♥️ **Thank you** ♥️♥️♥️ for this great app! Best in class it seems!

(there's another little bug around multi-line selection, I will report it when I have time)

**Comment by tsujan** [comment]
Sway is a Wayland WM. Under Wayland, no app can set its position; only the WM determines it

My wild guess is that Sway's window placement and resizing somehow interfere with each other, but don't rely on my guess. What I know for sure is that positions of windows are decided by Wayland under Wayland, and only by it.

Thanks for the kinds words, BTW.

**Comment by w-jablonski** [comment]
Yes ofc in Wayland no app can set its position -- and it is not what I'm describing here.

I hope you understand correctly what I have tried to explain.

In other words, if we could have FeatherPad to neither `Remember window size on closing` nor `Start with this size:` then what would it be then? Maybe it wouldn't interfere with WM...

Or maybe it's a Sway bug -- but other apps behave correctly...

**Comment by tsujan** [comment]
> I hope you understand correctly what I have tried to explain.

I did :)

An app can request a window size. What the WM does with that request is completely out of the app's control.

> but other apps behave correctly

That's never a good argument, not even under X11. As I said, Wayland always has the final word when it comes to such things.

**Comment by w-jablonski** [comment]
Okay and thanks again.

A tidy-ish workaround would be to have a command-line option to `Open window with size x,y` overriding the config. Would it be time-consuming to implement it?

Coz now, say I wanna have FeatherPad to open a tiny "Notes" floating window precisely in the corner (btw I know of your app FeatherNotes!) in addition to a general-use floating window in the middle of the screen. Each time I resize the latter, I have to adjust WM's geometry parameters of the former. Now with the aforementioned option available, I could utilize it when opening my "Notes" from cli, and thus make it immune to any geometry changes of other windows...

Thanks again for your time

**Comment by tsujan** [comment]
That's possible, but I'm afraid I can't add WM-specific workarounds. Each program needs to do its job correctly.

**Comment by tsujan** [comment]
BTW, the problem you see in Sway isn't reproducible in LabWC (my favorite Wayland compositor) or Wayfire (which I sometimes use).

**Comment by w-jablonski** [comment]
> I can't add WM-specific workarounds

I see. I've seen apps having this command-line option, so I think it may be of general use to ppl. 

Thanks for the LabWC tip 👍

**Comment by w-jablonski** [comment]
Or maybe you would be more inclined to consider a command-line option `--config-file=` which should have pretty universal use and would help me keep things tidy... Ofc I guess I can currently modify XDG_CONFIG_HOME and acheive similar result, but this feels un-tidy...

I have submitted a reqeust https://github.com/tsujan/FeatherPad/issues/793

Thanks again
