### ISSUE TITLE
Feature Request: Column selection and editing

### ISSUE THREAD

**Issue by baal-lgln** [tsujan/FeatherPad#801]
Some editors allow the selection of a column or block of text while holding down shift+alt keys (eg visual studio code).
This allows editing multiple lines at once and really useful in html or csv files.
That is a feature I often use but couldn't find in featherpad.

**Comment by tsujan** [comment]
Please see https://github.com/tsujan/FeatherPad/discussions/789

I investigated it after adding that comment. It's beyond what Qt provides currently and needs either using an extra library (not an option with FeatherPad), or a great amount of extra codes (for which I have neither time nor motivation).

If at some point it's provided by Qt, I'll add it, but I don't think it'll happen soon.

**Comment by tsujan** [comment]
I found a way of adding a kind of “column selection” without needing a huge amount of code. It supports copying/cutting/deleting a column, prepending text to all lines of a column, deleting the preceding text by using Backspace, and copying on a column (the latter is somehow unusual but possible).

I should test it to make sure that it can really work as planned, but, for now, I reopen this page.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/520917204989cbdf3eabf708e03e3f64a14497fe

See Help for the usage.
