### ISSUE TITLE
FeatherPad doesn't get focused when opening a file with it

### ISSUE THREAD

**Issue by ludg1e** [tsujan/FeatherPad#805]
OS: Fedora 40
DE: KDE Plasma Wayland (kwin 6.1.3)

Issue: when opening a file with FeatherPad, it doesn't get focused, and so I can't know if the file has been opened or not until I open manually the FeatherPad window (I use tabs).

Thank you.

Could be of interest: https://github.com/wez/wezterm/issues/3619

**Comment by tsujan** [comment]
On Wayland no app can activate its window(s). Until Qt (QtWayland) does it with some compositors at some point, I have no intention to add Wayland patchworks to FeatherPad's code.

I've just added a line of code to git for _requesting_ activation under Wayland. What it does depends on the Wayland compositor — kwin_wayland adds an "urgent hint" to the task-bar button, while LabWC and Wayfire do nothing.

**Comment by ludg1e** [comment]
Thank you.
