### ISSUE TITLE
Compiling issue

### ISSUE THREAD

**Issue by Duolabs** [tsujan/FeatherPad#808]
I tried to compile it on Windows with QT Creator on 6.4.2 verson and it raises this error:

` Could NOT find HUNSPELL: Found unsuitable version "", but required is at least "1.6" (found HUNSPELL_LIBRARIES-NOTFOUND) C:/Qt/Tools/CMake_64/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:592 (_FPHSA_FAILURE_MESSAGE) cmake/Modules/FindHUNSPELL.cmake:13 (find_package_handle_standard_args) featherpad/CMakeLists.txt:9 (find_package)`

I simply ask why you create what looks like a great tool, yet compiling it immediately raises some issues. The installation guide is not as clear as it should be, especially when using a CMake file. Creating a qmake .pro file makes life easier for everyone, especially for those who are not familiar with your code dependencies and represent your user base. Unless you decide to publish the code just for yourself, in which case, use GitHub private repos.

Sorry for being critical, but it is very frustrating when there is a lack of information, and what appears to be a great piece of code starts with errors, requiring hours to achieve the first successful run. That's the way it goes, and if someone is kind enough to post a possible solution, it would be appreciated.

**Comment by tsujan** [comment]
> Sorry for being critical

It would be appreciated if it was a real criticism…

You could learn basic things about compilation or, at least, read the included documentation, instead of wasting time by complaining.
