### ISSUE TITLE
yaml hightlighting

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#81]
is that possible?

**Comment by tsujan** [comment]
Everything is possible. I should study its syntax and dedicate some time to it; it might not be ready for the next release.

**Comment by agaida** [comment]
not that imporant, but a usual file format

**Comment by tsujan** [comment]
It's good to cover more languages.

**Comment by tsujan** [comment]
Added yaml support (in https://github.com/tsujan/FeatherPad/commit/69d8e9f511519f35eddc09a340585dc3604ab332) -- maybe experimental because, although it works with all combinations I tested, I'm not a yaml user.

So, if you found any problem in the syntax, please tell me!
