### ISSUE TITLE
Please support Windows

### ISSUE THREAD

**Issue by vmz9poa5** [tsujan/FeatherPad#811]
Many KDE applications now run natively on Windows. e.g: Kate, KDevelop,...

Kate is a good editor. But the problem with it is it's too much bloated. Notepad++ is good but I can't use it on Linux. It's cool if you can use the same piece of software regardless of the platforms. Geany and GEdit are good solutions (yes, GEdit, things changed too much, that now there are always a port of some Linux specific software for Windows). But the problem with them is HiDPI support. Qt is very good at that, so I'm finding software written in Qt. I found casm's ndd first, and it's indeed very good, but the developer doesn't interact with the users outside of China much. They are limited to their own domestic market. I did a bit of distro hope and I found MX Linux. And FeatherPad is the default text editor of MX Linux (even though Geany is also come preinstalled). I'm really impressed with FeatherPad.

I don't mind having to compile from source on Windows. But please make it possible to compile FeatherPad on Windows first. Previous FRs about Windows support (#587 #718) are all led to nowhere.

p/s: I don't have the ability to patch FeatherPad to work on Windows. Btw, please keep this issue to open so anyone interested could help. Thank you.

**Comment by tsujan** [comment]
I support only Linux and, indirectly, Unix. A few other OS's are supported and maintained by contributors.

**Comment by tsujan** [comment]
BTW, FeatherPad isn't a KDE app. It's based on Qt and doesn't depend on any KDE library.
