### ISSUE TITLE
FR: Syntax highlighting for the Adept language

### ISSUE THREAD

**Issue by vmz9poa5** [tsujan/FeatherPad#814]
The syntax of the language is very similar to Go. Here are existing syntax highlighters for some editors:

https://github.com/IsaacShelton/AdeptVim

https://github.com/IsaacShelton/AdeptVSCode

https://github.com/AdeptLanguage/AdeptSublimeText

https://github.com/geany/geany/issues/3917

**Comment by vmz9poa5** [comment]
Is there an existing syntax highlighter for Go? I can't find any in https://github.com/tsujan/FeatherPad/tree/master/featherpad/highlighter!

**Comment by tsujan** [comment]
> Syntax highlighting for the Adept language

Sorry, I have no plan to add any other language. FeatherPad supports the best known languages (and more). Of course there are many languages that it doesn't support.

> Is there an existing syntax highlighter for Go?

Yes. Enable the language button by checking Preferences → Text → Support syntax override
