### ISSUE TITLE
FR: Syntax highlighting for the JavaScript language

### ISSUE THREAD

**Issue by vmz9poa5** [tsujan/FeatherPad#815]
Is there an existing syntax highlighter for JavaScript? I can't find any in https://github.com/tsujan/FeatherPad/tree/master/featherpad/highlighter! I'm currently on Windows so I can't test to see if `.js` files have syntax highlighting or not. Feel free to close this if there is already support for JavaScript.

**Comment by tsujan** [comment]
> Is there an existing syntax highlighter for JavaScript?

Yes, of course. You can enable the language button by checking Preferences → Text → Support syntax override
