### ISSUE TITLE
fpad is unusable with markdown files and blocks lxqt completly

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#82]
something blocks nearly every keyboard input, after a few minutes fpad segfaults i guess and take the terminal with him. Sorry, cant describe it better right now.

**Comment by agaida** [comment]
hmm - couldn't reproduce right now

**Comment by tsujan** [comment]
First, it's Impossible ;)

Second, I use FeatherPad to write the formatting of markdown under LXQt.

Third -- and most importantly -- please give me a step-by-step way of reproducing it! You're the one who wrote those templates for LXQt and I'm sure you know how important it is.

**Comment by tsujan** [comment]
In the [other report](https://github.com/tsujan/FeatherPad/issues/81), I said, "Everything is possible." I was wrong ;) This one isn't.

**Comment by agaida** [comment]
gosh - i can't reproduce it right now, i tried - i opend just a bunch of different files (qmake, cmake, python, bash etc.) all went fine until i hit this markdown file - all i can say that there must be some kind of loop, featherpad terminated after a few minutes - the only possible input was the bug field in firefox (gtk) - try to reproduce it, no luck so far. :D 

VERSION: Debian sid with latest git LXQt and fpad :) 
btw. the changes are great.

**Comment by tsujan** [comment]
This is very strange. Even if FeatherPad had a hang, it couldn't block input. If you remember the file you opened in that time, please attach it as a zip; a check wouldn't do any harm.

**Comment by tsujan** [comment]
> all went fine until i hit this markdown file

Attach it here!

**Comment by agaida** [comment]
no chance - but i found another annoying behaviour (blocking) - ok, i tried really hard :)
To reproduce, take a dir with some files in in, in my case work/code/pkg-main/ - thats where my debian packaging lives. 
```
% find . -type d | wc -l
45424
% find . -type f | wc -l
187546
% find . -name \*.md | wc -l
386

agaida@ramme ~/work/code/pkg-main % find . -name \*.md | xargs fpad
QLocalSocket::connectToServer: Der Verbindungsaufbau wurde verweigert
agaida@ramme ~/work/code/pkg-main % find . -name \*.md | xargs fpad
The X11 connection broke (error 1). Did the X11 server die?

short video: https://youtu.be/aa7dcA0eNHk

**Comment by tsujan** [comment]
`QLocalSocket` is used by fp. The message "QLocalSocket::connectToServer: Der Verbindungsaufbau wurde verweigert", shows that a fp process we killed in the previous session.

Apart from that, in your video, I see many tabs. The question arises as to *how many files were being opened in fp?* If 200 files, for example, it'll take a while for them being loaded. I've tested with Kate and seen the same thing.

So, how many md files were there?

**Comment by tsujan** [comment]
In other words, if there are so many files, its normal that the process takes a while to be completed. 

However, the input issue is bad and I know its cause: each file sets the focus on the window -- I can reproduce it by dropping the contents of `/usr/share/applications` into fp. I'll fix it tomorrow.

**Comment by tsujan** [comment]
Didn't wait until tomorrow (although it's "tomorrow" here) and fixed it. Opening of hundreds of files doesn't block the input anymore.

BTW,
(1) I was aware of this but never thought any user other than myself might open hundreds of files simultaneously ;) Got confused by Markdown because it wasn't the cause.

(2) Tested with Kate: It took the same time and the same transparent window appeared for a while but the input wasn't blocked, as isn't with FP anymore.
