### ISSUE TITLE
highlight systemd files as config

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#83]
if possible, highlight *.service, *.mount, *.timer (all unit files) as configurations

**Comment by tsujan** [comment]
Yes, it's possible and is good; it may just take some time.

I should change the layout of the new language menu later, when the number of languages gets too high.

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/368a14a81e6d6e26472d304798b36c74692e5f64
