### ISSUE TITLE
Unable to render the Terminus font

### ISSUE THREAD

**Issue by birdie-github** [tsujan/FeatherPad#831]
After I upgraded from Fedora 40 to 41, the app now shows nothing when using the Terminus font.

I mean there are symbols but they are all invisible.

Components used:

`featherpad-1.5.1-1.fc41.x86_64`
`qt6-qtbase-6.8.0-4.fc41.x86_64`
`terminus-fonts-4.49.1-26.fc41.noarch`

![featherpad](https://github.com/user-attachments/assets/b8cfb4fa-9bd1-4622-9c0e-0c89fabc32b0)

**Comment by birdie-github** [comment]
I'm glad it works on your MacOS. I'm using Fedora 41 and this is still an issue.

The fact that you've speedily closed this bug report doesn't suddenly mean the bug is gone.

But it may indicate you're not interested in fixing it or even assisting in fixing it.

That's sad.

**Comment by tsujan** [comment]
It isn't macOS but Arch Linux ;)

BTW, I was wrong about Terminus. The screenshot shows "xos4 Terminus". Terminus is like you said. But that has nothing to do with FeatherPad.

> doesn't suddenly mean the bug is gone.

Of course, it isn't. Here is FeatherPad's bug tracker and the bug isn't in FeatherPad; hence closing.
