### ISSUE TITLE
Broken font selection dialog

### ISSUE THREAD

**Issue by birdie-github** [tsujan/FeatherPad#832]
Issues:

1. It doesn't list Terminus, instead there's empty something (a)
2. There's a ton of unselectable white space, as if there are 30 to 40 invisible fonts

![font selection](https://github.com/user-attachments/assets/9a29527a-61c3-4127-9e03-f57c4517e586)

Software info is in bug #831

**Comment by tsujan** [comment]
1 is so here too, but 2 isn't.

Exactly like https://github.com/tsujan/FeatherPad/issues/831, the problem isn't in FeatherPad.

**Comment by birdie-github** [comment]
You're right. I've installed qterminal and it's affected by both bugs as well.

What's the Qt version in Arch at the moment?

**Comment by tsujan** [comment]
Arch's Qt is 6.8.0.

Most probably, Terminus has a problem with Qt6. I don't know why I also have "xos4 Terminus"; it may be provided by another package, and it doesn't have the problem of Terminus.

**Comment by tsujan** [comment]
Interesting! "xos4 Terminus" is provided by the package `terminus-font` in Arch.

The situation of Terminus seems like a mess. I have it here only by chance; never have used it (preferring DejaVu Sans Mono).

**Comment by birdie-github** [comment]
I've installed `terminus-fonts-legacy-x11-0:4.49.1-26.fc41.noarch` and now everything works. It contains `pcf` files (Portable Compiled Format).

The existing package, `terminus-fonts-4.49.1-26.fc41.noarch` doesn't work. It contains `otb` files (OpenType Bitmap). Looks like OTB fonts break Qt6. Qt5 could use them just fine.

Perhaps I'll to need to file a bug report against Qt6.

**Comment by tsujan** [comment]
BTW, I'm on Wayland and can't log into X11 for now, so I don't know if Wayland can be related to this.
