### ISSUE TITLE
Is this expensive or bloat

### ISSUE THREAD

**Issue by AcarBurak** [tsujan/FeatherPad#84]
Live count of found strings on Find-Replace pane.

I find 20 strings and it shows on the pane. I start navigation or replacement; I'm on the first find and the pane shows 1/20; I'm on the second find and the pane shows 2/20…

**Comment by tsujan** [comment]
A long time ago and based on experience with searching/replacing, I came to the conclusion that the number of found matches doesn't have an informational value, while the number of replaced items does *only when all of items are replaced at once*.

When you have an entry in the search-bar and have pressed Enter, you could paste the entry string to various places of the doc, remove it from various places, or change the match-case and whole-word settings repeatedly. So, neither the number nor the order is a valuable info.

That isn't the case with the a global replacement, especially inside a code.

**Comment by AcarBurak** [comment]
Fine, thank  you.
