### ISSUE TITLE
One vert line should be enough

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#87]
![wordfence](https://user-images.githubusercontent.com/1162845/35939951-f3780a64-0c4d-11e8-9ff8-0751f29a91c3.jpg)

**Comment by tsujan** [comment]
Enough for one job, as in `atom`. Multiple lines with equal distances from each other could have other jobs too, depending on how they're used. After all, they don't do any harm.

**Comment by agaida** [comment]
ok, i just dont see the sense in a vert line at 80, 160, 240 - but ok
