### ISSUE TITLE
Add context options for link handling

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#89]
when over a link? Only if possible - otherwise nobody will notice that one can work with links in featherpad

**Comment by tsujan** [comment]
I'll add an "Open Link" menu-item when the user right clicks on a link.

**Comment by tsujan** [comment]
Working on the right-click menu, I found that FeatherPad lacks a "natural" behavior that Kate has: When a position is right clicked, *if the text cursor doesn't have any selection before right clicking*, Kate will move it to the right-click position.

Terminal emulators don't (and shouldn't) have this behavior but it seems OK for text editors. I'll add it to FP.

**Comment by tsujan** [comment]
All done in https://github.com/tsujan/FeatherPad/commit/9a843546023465c4dc0b9267c7778cb24ad378d4. Also added `Copy Link`.
