### ISSUE TITLE
Tabs: Jumping from last to first and vice versa would be beneficial

### ISSUE THREAD

**Issue by pmattern** [tsujan/FeatherPad#9]
Right now no further actions takes place when the outer right tab is active and the keyboard shortcut to switch to the tab at the right, by default `Alt+Right`, is hit. IMO it would improve the usability a lot of FeatherPad jumped to the first tab in this situation.
Same thing the other way around with first tab and shortcut to switch to next tab at the left.

Maybe the feature is a matter of taste to some degree and should as such be implemented as option.

**Comment by tsujan** [comment]
You mean wrapping around? Good idea! I can make it optional in the Preferences dialog.

By the way, since you've found bugs that I couldn't reproduce (but fixed and will fix), could you please do a little test on https://github.com/tsujan/FeatherNotes if you find some free time? Thanks in advance!

**Comment by pmattern** [comment]
> You mean wrapping around?

Yes. Wasn't sure about the term.

> a little test on https://github.com/tsujan/FeatherNotes if you find some free time? 

Sounds interesting. But may take a while until I find time to look at this.

**Comment by tsujan** [comment]
> Sounds interesting. But may take a while until I find time to look at this.

I don't want to bother you with it. There's no haste at all.

**Comment by tsujan** [comment]
Done by https://github.com/tsujan/FeatherPad/commit/9ab42313530d668f3b9aac14ff2e2cbaba6d110a.

**Comment by pmattern** [comment]
Feature is indeed available and working as expected in 9ab4231.

**Comment by tsujan** [comment]
Just needed a small fix (https://github.com/tsujan/FeatherPad/commit/0bbb71e9e1b4069a994109daf00f6d81774adcb7 -- resets the tab wrap setting).

**Comment by pmattern** [comment]
> By the way, since you've found bugs that I couldn't reproduce (but fixed and will fix), could you please do a little test on https://github.com/tsujan/FeatherNotes if you find some free time? Thanks in advance!

Did you receive the mail I wrote you on that matter some two weeks ago?

**Comment by tsujan** [comment]
> Did you receive the mail I wrote you on that matter some two weeks ago?

Thanks for telling me about it! Gmail had wrongly removed it from my inbox. I corrected that. I'm reading it now.
