### ISSUE TITLE
Option to remove trailing whitespaces on save

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#91]
One of the reasons i use atom on debian foo from time to time - imho a must have.

**Comment by tsujan** [comment]
Good idea!

But first, I should really replace all occurrences of `QRegExp` with `QRegularExpression` --  a tedious job that I've started and should be done with care. After that, I'll think about this feature.

**Comment by tsujan** [comment]
I implemented it in https://github.com/tsujan/FeatherPad/commit/01e702c4246b9764c3ddec83a634a7a6473daba0 after finding the fastest way of doing it.

It's a very useful feature :) Thanks for telling me about it.

**Comment by tsujan** [comment]
The option is near the end of the text tab of Preferences and is disabled by default.
