### ISSUE TITLE
Diff Highlighting

### ISSUE THREAD

**Issue by tsimonq2** [tsujan/FeatherPad#94]
I think I'll finally be able to switch from Kate to FeatherPad full time if diff highlighting was there. It would also be nice to be able to override (like Kate) which highlighting should be used, but I guess that's a separate issue.

**Comment by tsujan** [comment]
Diff highlighting *is* there. What do you mean by "if diff highlighting was there"?

**Comment by tsimonq2** [comment]
Oh, I might be mistaken... hmm...

**Comment by tsujan** [comment]
No text editor -- Kate included -- can know which syntax a pasted text may have. You have 2 ways:

(1) Use the new language button on the status-bar and set the language to diff;
(2) Save the text as diff.

**Comment by tsimonq2** [comment]
OK, thanks.

**Comment by tsujan** [comment]
You're welcome.
This is an example of diff highlighting:

![diff](https://user-images.githubusercontent.com/981076/36182270-0eb17050-113e-11e8-8bea-afdf72b93037.png)
