### ISSUE TITLE
Allow the saving of a not changed file

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#95]
because it sucks to use "Save as" if i only want to remove some trailing whitespaces. Saving the same file again and again seems senseless, but isn't, also in one other regard - if saving a not changed file again one can modify the change time of a file without using touch $file.

**Comment by tsujan** [comment]
I understand what you say -- actually, I encountered it too -- but strongly disagree on allowing saving of a unchanged files -- the state of the save button is very useful on the toolbar .

A very easy and fast solution I found was adding another trailing space and saving the document. Try it!

**Comment by agaida** [comment]
:)

**Comment by tsujan** [comment]
OK, if this is about timestamps (https://github.com/tsujan/FeatherPad/issues/117#issuecomment-382191823) and not just removal of whitespaces, I should think about it with caution to find a solution that doesn't break other things.

**Comment by tsujan** [comment]
Replying to https://github.com/tsujan/FeatherPad/issues/117#issuecomment-382192578

So, if I correctly understand, both cases are about saving a file over itself when it is *not* modified and *without* any prompt. Am I right?

**Comment by agaida** [comment]
it is a bit specific to debians workflow - but having featherpad ready for that would save me a lot of time - featherpad is fast enough to replace pure cli editors like nano or vi - and yes, in the end it would be about touching the file. A plus would be if things like removing trailing spaces would be processed if enabled. 
As it is optional i can't imagine a situation where it could be harmful.

**Comment by tsujan** [comment]
> As it is optional i can't imagine a situation where it could be harmful.

No, it couldn't be harmful as an option. It was just it seemed peculiar to me at first but it makes sense with your explanation. An option to... I should find a good description for it and then see how to implement it but I will add it.

**Comment by aramazano** [comment]
> An option to... I should find a good description for it

"Always save on close" ?

Maybe with a tooltip: Check this to unconditionally and automatically {save|update the last modified time-stamp of} a[n open] file on close [even when it is not modified]

**Comment by tsujan** [comment]
@aramazano I've implemented what @agaida wanted; just didn't have time to make a commit.

"Always save on close" would be a bad option, IMO, because it enforces something dangerous -- although "optionally"; it's like telling the user, "Use it at your own risk," which isn't good.

**Comment by tsujan** [comment]
Yes, exactly. And it works like a charm here. Tomorrow, I'll make a single commit for this and https://github.com/tsujan/FeatherPad/issues/117 -- 2 options will be added for them and you'll have to translate them later ;)

**Comment by aramazano** [comment]
:)

**Comment by tsujan** [comment]
Done in https://github.com/tsujan/FeatherPad/commit/e2b185ecfa3887952000e8098297af315d811561

The option is under Preferences → Files (last checkbox). Later, I may think about disabling it with auto-saving, although that doesn't seem important.

@agaida 

Please see if the problem you had is solved by it.

Also, don't hesitate to tell me if FeatherPad can be made more suitable in any way for the kind of work you often do with it.
