### ISSUE TITLE
Links again

### ISSUE THREAD

**Issue by agaida** [tsujan/FeatherPad#96]
is it possible to handle mail addresses like links - aka open a new mail and make it possible to copy the address similar to http links?

**Comment by tsujan** [comment]
It's quite possible. As a matter of fact, every non-email link can already be opened by its assigned app -- test with a link to a file and start the path with `file:///` 

I'll tell you after investigating the CPU usage.

**Comment by tsujan** [comment]
Happily done in https://github.com/tsujan/FeatherPad/commit/11ffa8709b84c8b02520896076acf4c2e261000e

**Comment by agaida** [comment]
Works like charm - thanks
